# MD LOTTO v5.4 FINAL VERIFIED - MOBILE + PC
# Upload only this file and requirements.txt to GitHub/Streamlit Community Cloud.
import base64 as _b64, zlib as _zlib, json as _json, tempfile as _tempfile, sys as _sys
from pathlib import Path as _Path
_EMBEDDED = 'eNrNvWmTI8eRIPpXUi2jElmVyMLZB7qz37bI1ojv8dB2UyvOQ8NgWUCiKllAAswE6uiaWiNnemXcEWdFzYo71GyTxtnlrGZkWjOOSImSDfeLfsp+7Kr+D8+PODMTVdUk9Wx1dCHj8Ijw8PBw9/DwOL4yGw+n8+VyvjUcJmmyHA6DxdGVnnNlONyPszyZp8OhEzpuO2gEDfdBesV3dJXtaLS3jPOlqDLJ5jNnOJyslqsshmrJbDHPlk6UpvNltARQ+YNUpGVROp7P1Ge6mi2OnCh30oXvLCAPfsL/FuMHKQHNR8niKMgBSi6hbifpfIaNiyJ2LgDcjrMhpckC88UymSUP40wWkgnDnWgWq2J5MltNqbuy3Gga5XkyOZIllqs0SXdkLnzFw4M42dld5r7zo7sv/tn3Xxu+9OJ379259+cPUvzvOJ44s2g52h2O5qt0WRvNZ9tz/yBJEYzXy2LAV+pM47SWxyLX+w7+lEU8CWWYQ8/i4SxeZskor9GXv4yynXjpb8/TVR6+Mk9jP5sf0A+v9yB14D+7yTIP+1YXRC3PmcwzZ+QkqUPABlxhvlqGx+42YNftzaLDGgLwfLe9mK5yt5evZrXd22Gb6u5iXZHfsfI7pfwl0MFU5GPKCbeWTBzqvJMAAcyXDnZd9Bz/A7SyB92Xs6D6ziMujeAm9r7vLjI1s+4gxCazb4VuCqBdqpFhDQLt6aagJ4A7sx9AvWMnmk5rEwHxODlxqer8IEhgUg4JWiKg7cS1pn/V84zu439mgM0mIrPpu6107PZagMwM/rYBactdt9fx3S7+7Z7cBPo/QvzDerOB2L0utCB7j/kz6vRiHMAg0qiGPQV06RHM+tngxIVOiqY2w8l0Hi2xYL9QaODZzTBqqRZglX8IhI/mOaY1G43GBtEyzoYnMrN5Ank1rlA3yntbxge3JdYDpCuyZ3bB1F/L0h2f5tUH0hzOgU1No4VF76PdeR6nYR9oIVou49kCyF8g82A3mca01riQd4tA8TSLsrdaMIaGgeBRuFwtpnEth/Uej7EDQR7NMEVOeeeqh9Pu6QY3w6ZFV0Sh3GZvNE+XSbqKrQLGYMoEmB7VFH9g3nDoebfNKkgdh7oNr6IRzgmixSJOxwDHQjdnSowfRNO9IYA8iLJxbTzxgZFmy+Eyi5I0bDcajH+Ya8iIF2GTZgKZMaZBYhyPw6udrs9YGhJLy8MuYNUXU5nFCy5rzmHbF3zUmk0gy5zmEpZbMoJmp0m+FJg3+uUjgsYTj7rkef266lNPEBYt1DEhSYAy5pjHNp4EyXQ+6vegHLSIjFQmcQqznvA4SeV6SZEjDLwyG7jmwWJmrixKB8yxbjppHpo7VI0aN5babBzamxOX8NNcYJ7p30av9cVzgP9sQsctLBu/Fb7FX5sVIkJnY7FCKuhpNgsLG9JsHFDzwXJOk+RZrBr3JRg8LJ+QqSC4R39q2M0NZByNBvYWy2zTjGfbY/irW0QcDzWODVoqctxsW9J5oYvreAlRXLm7XhHs+BnhGtg+H/wsjtJwGs22x5GzFx/5UZb1mC+niwAza/1D4uOYCUlplHp61UPpgQltEWejGCZsGodFIH3e2Ae3wtlM/taAYIQWoCweweY1zqKDYTp3e5KSRQJs6iANCkFBQaNEEhbEBkx5LD1wZqeY2RGZhV0Ny5LUMCTpRZZmQYJBmRs9ZBKKrN3fb3glsGKysLtDRAvURORw//1sG8YlioyT/fXFxmshYzXGgFmPUcAVzZKdUsmOUfKcJgRujIqMmnITBkas8hamKpsTEzzUJDXcz4catNvTOapJXJNuz/g4sVgLCQQkq8yKCzceBavFGBfRMU0vCxs07VLwoHknkYGSWXigRARLaSRw+GUZqQqJDNbGCrdURiPAtQpiO1TqxFwzsGNJNgHjsTdakMteiJbR9zJAOS6lXEn3IKTOIpoOqVjVtpeSsQl+DAlh2JA6w7FLG5zbawj0gsbAuw0UDMTE3YafVcTsBSgVo8wyned5XKp368J6ywR3Y+5VHZuuMyTuyzgeJXmyH4eYs8k5IN2GSnND/Sb3ZTE/6HrBYj+armIcrEx24mkeO82gcROSpssoD7mHFleo213Vq8JUZwSqRH8V4xLTyVxSj565pbeWEajyVdmqskGAmicKNQjRze0ZrFLg1i/zkfhwEY9A/KxuWvMaCaHQdKe66c75TXcu0XTn/KYh3ZysIc0ichBaTgRGwuUJ1pinujbbKVfSU7aWQ1VOx24cIRUN6S9SotsjenSZUoFQ6C9orQl+4b++myc7KQmVw8WQSFX2YmEDj/eTcZyO4uF8MozHO1Bsez6f1ha3gkaXJHps6ja3YNcEuR9Ku3cPF9N5Fi3n2VHg3HFQTASBKhmBKnrkYC+SCXykS1CtcyiEGcBg8tV0KZWHRTafTxz4H9tj4DsGmXeJS2oxP4izwNXqt8FokSkDSkfz6WqWmgIyZFqMmeeUubA5E5iiSEmVk2zcLMlpFURT2H2yOJoCVxTcnSFUgKiX2t8q92hNKwY5S2Ivd7l6y/gKkPUmUgVb5kqqPfHW6cUpECKAO1dZu2ooa1pLa3X8JE1B/0A5DvKuF3SJZqugql03tDpLZZP704Mr+N9XV8s4c1bpcr4Cvjx2qLWbThyNdrHjkIcNOnk8BUzkjlA7nFWOBrV5CrQdR9k0QRsddo/00LoYGlXNA27oK6mGz64V8uo6KuqFaPMbh6blryZKWmg1fl9ab1svsqz9z6VUPUM8AU0nXKCmlo6A+Pqy53KMpOkOBj4wmXkWD8nIFb6WrWIDxPYytKgOrY4m2SHCBVzPGrphKPiKaDCp0vj9jAovzWDfFZ+WnUtLWmXRFIUPQlJjADruEBlqDdXVeNR3mahxPRJQkLjnE9iK3IFsLAUMuANRmmmDZRJVwkq8+ZXlSJiDZbxzBKwXCkI27Pbn2XD0nLQbRT5wtbFu4Vvsod2w+cB9gE2Lnxet7+SUkIz24qVDJmgfN6Q6SHnTCDYm2WfYZAPnlbkaAtJ27ix3Y2F4IXAWC9AVw2M9Xe7LLzjb0TSCLRikFtsoD1qqzBn4jnt/ma1GuEPWQRLYPyqXzmUBS6FwXyEDTh334mi6ti7lUjvPwxyN6xGeqsTlgiPMHYpcq50fRAm0soy2k2myPFrX0AJKoTFpGwlObOzRzk54vNfTSoJPiusQNiz6KCjWDWXgbyhTfuOE+OMemdcVpjX8vvs8EkS0E9eRewMlf73WDMAvJHQANUmAOoTEtxZ6UAE/MFoIjDYC2cqfas+otCSadkPTonihAfEiUyHWesOv4TL3DzysHkP5GKeqZiyqZBnP8lrpYIKsVd+srXGj3dx842KDY8GwJpguHxp8K1xncuTDlKpjsGrDIxrkQyQnxA8eB/QFAQ02wyZ9KiqCFGXA4oIWQXG2MDxRvrBnUbr4TekdI1381gP4tmMtmB6I6qYIn4/gB4hC6jxxsppOnU63zjQAkvt8ehMYKINw5ttvxCzSjzP4NxeCVTJPA8PsP9+/1Awj7GEOhcKS5f686e60L5zsY8VDUfmEtSgpmrkjpij+RVyOkoglIlMo780wJC8URHIBcUDRC0ijyML+D6CSahM5ofvGjSYKHLP80oZxLPz1jdamTVjgrYpDX4S8gjHaNkDPaASzfEAHaRW4LdcWqK6srlBfriayKqt11lfrVFezlBG9QxBPjsg6v7MjObC5UeBiqWl8+TSzhsxH64bkILdHwOTuZ9RhIwlb4C1cby39kvElFnVtvGJJy1ofGcb6TiFDoODkImE0wMNStpHktb7Ry8peDfwoH8GQgfeF34umeewFWZzHS9Y+auNsvpAqiOWBMoZGn9375I18nvoOcDLoPoimbwLLidu+gwe3KLHDr2QWC2+PRbTcnSbbEtwP4FPBsT1VpGtL/OYK50bUl59BNI4WoAArF5Xvv/baD+5wmii6yqbQUjtYLZMpDH+ZHcmy9/ADxfvv3rl/d/j8qy/98OVX7juh01cHMz7/QvMM/E6b+E8L/2njPx38p4v/XIV/6PgJ2c0P7r34/1rgKp0Z9NmQ5QQBe5N7QApLTt8eALz7+mv37lj942nOo2mcD6MZCv7QgWgFupOoC595PEuGhbRZlK6gokwA2BqqiYQH6avf+96Lz79456Xh/33/1VeGP7z3EhapMXW6u8vlIu9tbR0cHATjXaSZODuC/SDYy7amS9BptnjH/EG+fAk/X0wn82A8/7/ybLT70vLuIh+HxwLFMOKvAfSV+OA8uEDXL794796r94Z3XnoJB4E+V7KdfDbfu9ENdpLl7mo7SOZbTPts7su3ouk0QIp2FYyX7rx29/5rzwgGt4B8KSEprN67e/+HL5VgzdYMnIG52u9pmMc5epHVPKd+Wy+G+5wqmCEo8oWMmmYv2VFI5F8jUgK9EwQaIIrREn9mcTTGv3hgMp9MhpNoBKJUGFyrMCCg/AysDKh5FKMkENY6rRt+FxTcbqMF/2/D/zuej94+8wNQ42GT3J2P8xDW5sM4RZ+Lvvtnd19zFcPPAyLomsIKrAljVddwF8UBoG5KA8ENxqp0qTqyMTRUw1rQRtgf5qB/3tkB9d7tuS/PHybTabTVDRpO7eUX6i/h5Dr7bbQKxxGQ3U08E4bJBSlzBfzVXWtice+MRvECYcI2NAWxFJnnFvHMZXy43FpMUXjc2NpwC5tArqcd+H5CvRxPetbm4BMNJBkKkyDc76zmq7znoHFc8H0kE7OCIJFZkqONMOyPtL+XxQzJxQbt3pABCpawXw+UiVsAAGkoSvLY+Xe4Md3NsnkGTO1lznOk0ds5FqWBqzGAvThehGZ7m2ZHLD66aTNB6fpT6hMeSo0nfYQ8gKzFkaR5Bdbk7pfi6La1vj8aoJkP2CophMmoxol+jMPOQ5cw4XpBlC+PFnENVNNiD84ZWK/s3YSWeIXCy3RgNMcDG4ljcgTTu5isix+4H9eK+WvAQG+KJYMkT6MaDDQFJFdQgPtiSgTrqDrOOF7ykVcVVJiRQTBe8eKIx+dBfkGWckTNEmRhS/AziUIQRjIUoSxZETAIwiV5X5xvMgAJPE9D4amGtcraE7KyPPVAzb7qoJgKiwY9HJu3wsNboPvp/R4KFU2g5cUjcSecVYXrLUhFbKxz2FVKOYycwOrCbqmlpXDgpwXrRQoCMRFSEC3RWOLLgYepYYnWDlbCvcoaLw4OBkY5NDhoSTib4vh6542Iy60bh0G2IZ1BGfKuIpP1Yqx02CxxQzoexGkCoCb65emRaa/CLmHborlgltAxZykZ1AzP22x6Nm7MIlI5/lYo2ykq1swRxcmGoC+kJFneq+OXAbPkO7We8RKCBeFo7stt9XvtxkBh2z4E480GlQBEMm/wpS2HthS01IsRjUNjd/LQmiJRT3NjuVuMLzMD4yr8jyuwb7U1LuE+VLi3xsreVzmf2nOnQEpxoS1CEKcX+6AHwA4U5Bduz4eLskYlBOpwJQTH1SMQZ9o6oXgGCmXRbLSMh6jeUFNNUUkARlKv6n0YNinvHNgsrjKD74GaLGFgAo8goCm+HCp2o1x4SCExgaIL/JC3bbmjrdkU0YddybrjZKc2337D34uPcsNvJwFiBtpMRzHlIimaZEUGdn+f2P/2GxV2AgGGjPAIWnr/7Bf8w0PqwD43X6o+sdzrBYgJFwN5uNRNpMliN2Une99Yy+ILcwxELqIsR9+JSTJKQAtE2RN9x6fzaNxD9PlSkwAxHWcdCfgvEAY7Dtdvm8sd8rl/AoJ/7E5JBSOl+eAVqTzTjwyEc8wg3YgKSSEXqakM595k+uczBekFVr8RmvhJcMTvGMCJ8hIo714FqNuQRp2hXPo1XX7XSlQAWC4wjyVsccCYqf1COxPs8/KVOSnzE+6p/lr+KEnV14H8XbDF7lszS52Rtitc1vueZ3FTEkdA6jA6lcdvlpCKHQFlkjoAA6bGX0rIdCSEDD57yyV+X5njT7F/FPtokDU05gOr8HqGOHVo2DeyOJjATo2LP3MfPBhvuj5UIQYCMgSXRiFi0O9dNYyvxdWDzfDqWdMOFDBAoLMb7n+ASkYjUaxN4JUlUZYhYdX4VhdpZMIavJcl1R+m+WqxoH3dkSvPQZsKapCLOSjATr4bLZScTUMry5nWpqVchvHDM21UzLLxsKffazYG/sbGsZDuemm1OIhtgEB4IlcAO7GRxGfw4EmMPmaKc2CDNdETrOCjJgHCA/4Omy2bUwh9Av1JYE0qw8VNrXv33XvxJM7iDGTQS5iBlDVELk60ME5pxlKnbLeyzhCPipJ3mJNrswQRALxZtJSDC5VDthhhKP6iSTmg2UbLh5SRiqIZT1ol383IJFTzfNmCKRChocC5S3/wwlyUO0C/jEfJCCbusewzyv6xFuWIBO+tUuypIMJXJeERndNkOpMomYI46ribrvMXjhu8MQcZgdvgm3Fi05glmDYE1al2SLuEPbsmvSLpCO95orLDvuIeA23NL/q9HxrqX5mYMZe0TUHRBoa/InGjpz5+cYPi1Hqc7CdIl3nItwFcleB6uN7X7gVXPVtlT26Rl46qXlL1zNtgpHWpov2k3hwYjvYun1v0bYNwdQVp0dU7Q5WNmCalR0Crsgdy8BV5AvDBSJaRfcJTwCQlaxaj6vhETXXftkkPwoMRV8ZkObwKQ7UuqPJU6aIJWxXljIJGA1WYlpVWk+R0zquXI4u8tRILk8KP5YHzXShajycTPD7girymJNgjh84c0LVGcXvhQLqIdmLLx8bmRpnBG2lAFbbiZ+ZCl9iQa7AjHzf9LuzvD/KNp3//rutnAVokPfPklLGJCgBtSmQDgB9a9Be8vsC6eiUQUiTVu4pgMFXT0LV5TQlFJcP8JRF0U7Fmg7tJjuwVtz1RBtFl9q7dgN5V2FTX9VIcQVy6i0J0C2W/LLpWurZ1RNi3uLUx4wIW8NeyZUSaTvS10PkB+xDgkV8tg1HSPc2e1QH0gsHGX4NRQJ9nC2nEIelDKom+t8l3PC9hYvM2a6a9yTe6lMXoVQn7VS0+RH/tdKdnWb+zeDZfxlYa9NpYvMJkhZxZQvCkkQ4TGYC8NC5oWRs0VJ1AW520MQomUBcVkNYUBGY5m6dhzHec4V88umTXEhg4JUoVBma+X9xQuTqOpjBJcYCeT+kAxNHi9MkcLRYD6EoDHeLOyeerbBSjXYoOkZ15ajrSkMkExA0A0e+1DAMS7nw0eTwwtnXcwqTYSqoy5t4jlMmWQcieT0EqBB4apQ50HpoVPq+4bCfs1DyeH6Q7GUiPgWvQCTDgZHI0XIJoAxvEUkusaL2yKIacJXkZF/TaohlrNx7txeOwcZMkJkApi7JKqjUcE9iyoexPULyGhhd2zBQmJk/Zpc6VS6HjYZXQzRThiTu0fdVaGHLOQPrRlswFRbqYH5SJBVB0P8ZDshq0ipMlh2yqn2nRAilQZF3NvqwMmxaEV6nmqFEL4G5P/PB1lqRRdKGQHS1aoFRhIo0EAbF5jaGROQyZgKzvGfC5s26P//Z77YFplYqW81kyGh5kyRK4ab5fIjF0ceihY4PNijA5AI0gTpfBbG+cABelD+bDPrGa4XzPNGhPxv5ytgilIwVUy/F3bQHLITkMCSKmbLpDUK1XE0x0A6ji+gA/JE6tW0XqmefBaDrP49pk7FUJI+YawNMiHB/A89lrnY4UfcwfsroUus/9ef25Wf25scvAsxg0E9DZsQ42LQcCguJ0emRLzFCcekcjz7EKHk/kwSqdJukefWu059H+OdiGkf6FifGqSfKxAOFDBwDBvZGyi1Cs7b1i68WDclXRK/aTXWAu11VBHKHuHUgAl6YTYE4xTEM0Hg+BdSb78XiICUjROIViioGGFgHxRSaSGhFJMN42uDgmiJmAacAvMQ9SAYDq0rcnEC4DNEe4wvHbtG1CF5B6oHhNWNt9LOInkyG3EbqCUlyTtDzTyzJNoT/xaAWIdJ+/dxdEPeeHr7z4b39413nxlRfuvo6HfEN5CPjqK7xDSfXdU6dJBZIszdRROpKiF/9hg+ifZKrWzIOrpylggkUpvIbCXzBezRayZ36c5uiLFeWjJBFrEZEHe1nLhxFFoGzgmveg4GhOvl/uajmpX69amwYiaBGYiCgO3tglzcFbEpZJPJKZn2gOI5JoTNgeNMJriIZa6q+3RqswIKtpxI4LOcHuuS8UNdua7UthQe80lkhAYmvfWrc4/oGlDd6LJ7DCdtmdWDQOBDWJp0fBAyFG7neCRo8UwsVqe5qMnO3VdM9hOR0UqiPo3Y6zjVcy0F1WiFiB4/woRocSJ1myiWtXaFjTOUg/hkS2PR8f+ZidOttZMt6JnZjUUHHY56AUwioqDLq+fVRHAybqqGJSTEUV9uTFHBDgbMfQZiw5HYLhQC7ITPmqZLQPqYGJi6pVQY7/IDyZekKQgm6yfBi6d/Ik2roPKpDS2aWYHWp+TJqmJirWNy2dRxwkWW4klXuaONqaxcso1Bprtfhllq3SUr3iKa6RSZKYAcA0b60XkHrnQZRKsyEdmraLcK1Rw2hQloHpEA6J7HxoteQXABD6D83jiEHJD0ADrvRqsC2Rz8N0j61qphnFdF4QVztQbdAt8KkjV5DWeCIJlLM13j2/UM0zsccqWlhS7r1SEf7T5z9S1L4Vctds9yKjVkEXPEflVrvcKsP9Ygi9Zp8Lq8HCybHQMHncDXNg33a+yywARlNmADmbptRqZ33Lp8mgO6KITL4IZvkg6b45t8SslG2att+81Ijkvqz0fAPYZlO4wG82vYqoW6bD9jmnD175XBRrVgHkyTFuaIrpKTtZn39J8yvNtG0jrphiOqD/VthEq8RaEvhWWI3/okpdHv1Eatlyl0pS6UbQc5pBcMyAT5Q3hu+4VVB2gFiO1/b/BACt7fxJAWBhTRYtPMKo45W5XrhezRfzQFt5WLnBF3x1RF6/UqscXOympU5WWL9kr05lPQHdVrXw4EpFEw+usAnFOLmVCo6kTqPDLJeZFzJZx91zeyRouigEgegfLfnsRGy/JScPXvluzxXMj8SXTb2rEGJZmnBLDiJokBmygMDnKXLC1rArbW9b6yYiNksesdsT4ZyKbjXmPuX27G1rndYv3VnUTuD2CnmFqhsbBbcnQYX+xoasqCuclKzbYtK4brXwSpaQw17JfVDhqXiXsHLS1cSz/L925l0yXnBifFgVTsElg9pwFGFkAeGnQ9RUQoXqoQ3kpPLQs2w7tbCilpOU39eorkWbboW9nXY19O5czudTdQ/EOJbKtUehbdvDdmwT3vAb9BfdiRZQdrseUX7kb2OJh8mCTyXxn36zNzBPWbZXeJEbKmHsiykIGumtcDfRtkU+esHP6dzfpRb70Fqz4fm1ZtNv4d9W02/j33bT7+DfDvztegPTr4LuA0Er6XPNhg0cj+gBsRTXs2l228RmTQDwW7TGozDcNi+xjej88zjazmtRfdtbC4Ww0PJOvHrXthiY97TwGjJ2hkbuu/PxmLm4SH2uVUAO0Pt+nBbKhGGjWGytk/50fmDVvhW2ym3sJju7VqnbYatdKkXEwIFeKaWOe+QFzY/QIWS0wrunQ7y7KcK+AhGh7965dETOi3gFDOiOayEBelvd9a2hpyKVxj5SaWAkMP9DnmHVA7ojF41kaJ5otBYkHckzGQ+Pk83midvbF0fz+/bRvKB176R85U3KZ7gKq/18bZmNiAaEtgg4Tdj0CjYBEHSAK4PQCSxfyQkFAwEiIo0PWPnne2rylK97WVuAeTJstOnwvZKKY2GpbStLwfNok875yENIyKzYywvbuYizyn7U0GEh1xOLFVL7nfQIcpYH82xva5VG+7CVY/SCehofLutkBwBo44QDMaNal9YnMKrpBbq8OByZmKq5OKgiUSAUN/DXOLtOtLpCTGI8jnUIStqiDJW8cOtWTI7Fhg+X1Q1uNktNNs91/5kfVB6zQAOlc9rCAU1qiP/2ISwAHVToJeQ+nsYq0InUYL4VQmsVCst2Fkd7djLg31gf44mPCvmFygrUMvc9O5OmQnJc6MiFfkh2dZ47ki4KgI3uJxNuplch5sIgFjYHgBQz5IiWbm3Rk//K1GgC27VwiruYCs1AINSzofAFpw/fNXmGEKDoD1c7KdyWnU2f/a6sEZpdBmPfm8ZRlgaLZBFPE1DFRclZtAd7gUgsls3iRTYfxazpiwr3l3h/NhvfB7yoS7CyBgKJsuFsPo6nssJL8x0KgnYv3snYcaFQSdxrl+Wn850hxljzYfmMhtFqNMT4CvElIsY/SL93985rP7x3937Ydx9yNdd3pVUA9yJfb2KQgXvssNVQP7v6Z7PRwPur4jROioxD9N2bSF5RjPKBp1nWhRLOlWan18M078se2uad1/u6X4Pw9UB+BJNkOk2j2rWga1Px6+KCFoCgC+/qrGl7lUwxCloaT4vhg5rdhg/LcJiMD9lGLUbFwrkVvVkWk3QNJC6SynYxkaFCr8jB4jH2Ef1L6yUZF1yeORJLOYSLgFdwfLP6Wgq1LYBZhYru7niCZRWgUC6mQ3BeWacw+UaAmAqn+XW9rGDA5b5Q90omymeNPqMBvK4tXJHJeY+OwnQRPIyzeV7rdP0xXiTEFGjoulWsD4m46lBZqQm9mUvjtcN6c2CeyR/J1o6OTLuwmPsABATMpBFsdLr2uc7rZU8uaBpDsh/Vag0iLblwPBBFIS/Ksuio1h/YH9YagYx9IKzRXu11KsUbW5ziRnXE9XKuKTupn2wgDqZ0M+WfZvDKms0Ia55fZnQkXCDyMIq6/3wYdP18Pt2Hb3e6PdnJXX1GTLQ/jJFz8EZaWroUzwi/9IUuhEoWiEkWkZdPGLS6stOrPFbxjOq1cu1NowGvN1gjCxu72+3zYTBHgBbPuzyXL0PkGeZ6x120y3OMV5y3ttqShzBfkgd8r/tHvuIkJpuDWoCsAjejfwsXGfCwOXlzhbPv3WopP3uVrMgAco1ovUrKFeYQ0R+uFFZUv+mAjhVyah+H1/TlLTBO9DZqzbo1cUDVsJzkuRKFohLQboUjfK2BD2JE2u3RSvAJotNQkitsF8va630CMPCPxA9Pytu4Bqag2VHpQIQWxYh32xHWghbQDdpvDvxmXL/mN+v4RzmM5TRWEAkAz7WrW8A4cEALOVnTqQi9Ivfv2hGDBAEMMLK9Ph9Be0UPHQPpLJ7xAkGTCcth9K1ClrKFT2fG64KHulKowEig88mQgyTJmJ6WxGEOoGyn5EEUwUynvovjQQ4xlIVAmoT0MgQCoCLrymoIpL5NgFDzRGs/XlFZDkUNeRlvegsK8S2K4uMPw9m0KnagFTJQLeQDWKmgp3S6ja/4dsNXC9A5JEh0ANfwoWS90KG6yZ7sqoqtaTi4H282B+fyHj7fRnGeFpOMdgkLr5gvulbBqPDxCw1ja6tlamI2v1I8q8ivsFHfaEgJZRrwOcyskqGNFdeqePChgkX45hZ9WJBxsH9CytE9GnjVgokubJS9tIRytDxHEgHxcflMEsj5HA6Uz3XMbR2DU2JK8ciwcMekEgn6tYU15ixX84ciZ1xW8Bxdr4LBlAEwV10LA7jcGqZ3ftvL+eLqEN+B4pHzDMG8oN4Dm0G/frU3GAjWe2ILeXRyunZX9Y0gkczI+zIkJmwdWsjL+hpvA+N5JagyoH3GLlvGVanShTuPDkFP57dChywhf1oVsVxFU187advn16vYH0QwbdomvHWVefNQrRq30Xnr8Nbsj9SoQR0qklrWJ6Ipoa8agkEnZTg682JoTAv4b9Ewop6G+6ov2aFlFgODXeaIpzJ4mLBIiPCP5Xq8pHxWHEQxOr0HZajSniEDKi6NqDwjaJKsa0OM9VgzLQ4+BX5sNdYYJNYFqLnI7iF/t9EGUgwZI6L1YLSYNMdgMQ15MRBGHNZSaFXbW7bwu8qYwWwaQzZlYdOTm+i3nXsi7hE9lybDi1NwYZieGYjGSNVOxH5qABNnArBLPmTCGuQ8uDKG/e9KIHHSx7OSPRm3chDW6tApYR4K8CDJw0Due7XFaMniwkbQ7jqbDg5F4qRUotldG+zaqNmuqtlw6owtWIHbtaa3pg+t81qA9lGHqKmWusWG6ohlgrzRKkjXUCmd4l4KUh1SkG8hyAsYj2aEIXWrwPBQ13TJEUZrSJ52CFI/0wfOHAgMFxxF9iRtCGvgE2zaPRgL3bIjlypPT+qBdcgnLoZKMFLHjOM0xLAmXvH1OMzxbhWgY2IQjce1dc/F0bjwnTgbi9QdgmisVRGU1Ahkio0oHGQJAMy5czedN1fRWH3QaZjZbbVgRUcNOQeLyohiVQgZeX6Lnnrh9i4o2vZkXy4o2ClpaSx+ypM8mlL8CVukyBE94DzxoXOpUc6jn+ad8ELwWxnvXoW/bTaM2LetYgj0Nj5Lti4GetV7dXwy9WcZ1DjiAMuO3l/kEdpru7EzgfEtUTnZiZ2XX6DYvzE/7qg5tYiZnjvjOB/BoPHAFdkY1s/RFQlDpwMAocNHh9QOcrJsB+8wGLGCJ067TibOjowmDEwDqCT3ka6BUSbIDnfidJXIAy6qDByxDq3DkjbiDQPX2ZVXn2Yx9Fu+QziFDiyrXW6ro9oiwWL4t+LmlPuoNamJQQla0bbe3NRsknsVq6QikJxQbeQzBLfDbqN4C1S1mYeXZkKi5vIwrNqLTepiAhacBCd3HPZLW3pt5AMsSUjGa6a6bwMTBB0L4Btw8q24w95hH19J4TOKgZ/FFETeVFe/7fw/cQwbnLOdzaMxsMYF0CUo0vALo/DvwxbL0CkCsg4izWfBsIRi9q2WtCTmNt+FrlAkRe5av4czRtyRvtm5FR/T5IW20eo2POlGYrzRiZyvLZkXfnTMj5b8yOIZq/WhatgSS5g5q1Iqjpb10KfB+yhUbkJL9yZ/AHmHoMw1r4vvCg9sdhGgR2JNJwHVatEpSj4dSjfCiYpc1C1GzJ9HZbu/fOpzlDvfceihT13vghc/y5t8dQD1BaPUYs0jZvOLdlUWsfVFpyqrUzw/TuODFhlEFq06TR8+dxkftDmtTWltTutwWofSOgU4OlC6A5wCW8TXwxSbJEKlk9vcwYPCOr7PFBROvmE6O0FjA5sCQacZdPFnG2WeFv1s4c9Ge0M/f2sspPLUALzbkk6qjsElCcH/b0rqSkxSqmGbPvYB/+nYZhiuoKPAFE7V6RolPjeiSC1YzBc1rkWhxSopzdjq/1SzTrMs9/tFSyzbtkppy1WtUjq2LaTvAjbEzj/wVYLc8I0k3uUHoUJpAY4SmtRGBYUppFNNzo7foruy5ku4eMNUe97ZdzZ4aVnGf3SxKDETjlK4xBAxB1GG0wMtT9xXkUyPZa0T3ISPqeqJw+8O5/iuF0VQJ+MsWgdB23JVdyRQOTKAWpIM+5pFFJnCgLZB/s2bn7QpGrBxo8Nwm/Bn3UtTGLQyg1VIp1KokV9WljLFpe454tILZgNOfLgbrXISNKCtOspEhCFNhNpNSYtK2LAhYCU5SzRC/9sytrVVSj/4SkEEwu0K30ebb4vnBxyglWSGj69VORtdVliRt2i/UYHlGcUOQ8C5tM7zJ5RU2MMAtrQHVySjfXBl4F346JWoRkEqHlzRj0k8uOI3vGetbj0+8ZUg2I9VMIgqGBWimBJ7tGYmhAlGWsWr48jZHlyhBY7IqhQeqgUHo9YziQ5lsSETew8/4AyAcVEB3NAQsDab654azype8OA6tysf8TC2vktzZDNIwXwhDgiRyUlCEz5W+CT3cjmfVZaguyGwWy2ilI6TkPlwcTT13/Ds+MoPrkzmo1XOZ0SIjJoFTtT0thAcPm/tBbwVNb0iCwaSQuZ7xWTCZq48zB8PLVOixL9afxWA8fwCCz64YvNwzWKRnTcbSkkzeL9lIxUc5xkspM9gDDW8zPyCZVQZROiFrCzJ99gU4qng8dKsQKlAnlAkbATSmAhfzmbo8OmgcJVuN7UTdO7VO95GI2g1ZICtyaTaHT73LUd4I5oy1aGwpT1qcBPav9a1O4BNj6Vz9JgicFAtaLrZUL5SVQ7v6O0uodSu1mWjojSwHgDRuKY9GKewIT3XtZzJ6RkY0bGu7YkCNN8MGj7mGuanS20y1j6e440DUaIvj+0qbxzwoY5ygjbOAXlNIiR5FgGLcWwm58sxOkoC1KacYTzvTHMzjo3tLCf4vX2kqjAj+9Wx4qM9DNHeye0CfA5N4ytPQHoqZieSbMYoYXoIIq+e7YRGrvbMoxyuPdvhu8PjANZOGtE36q6zndti/78WdK27Vbzv4OlUfLio1YN2d+Mhd2gonrbTed2NGnrMbwHUetPb2Gjxc4V4CV9OfXkQ2m/R28KD6g08w9xoBlfZR9UoQKfyUFNGyaX+mt01sd9PB2EAgNQQNrHrRrc3YRVucO+09AT8Z763WoTHIupSxAGWs2Db8+S5ozTCe+blGDZu6usxJ4RmTCx5/Wl7oy0lK/MkEN+QiVRd+6K0fOz28rF60YqG6fbML/G2FQ/C7RkfZlAAJdJIWQuZGcpbXkX4QsnpxKqBUn2zgwNaNCoVumjKZfg6kCKPBtGHurhSF289beVjIhWxnYzHYfUtlpsCJJY4bveafqsX3Gj5Hfq32Quudv0u/dvowUz7V/Hfkz6UHsgYAQfhutsrEjaWuTxsKC1gyztKdMmnlgLxb20VrxGdqFa4NC8JX1TdknpqvqB3RiouyMjqokQBrZRYb7e8rRsGOmUAZKLcoN3ZUNNC5K8wuhk0r24oHGziOY3ZVyOBGzK4tyXilinK7oI6TiWKsQh5ACvWCuq1PR9oR0MWg6vJVaxZAmnS/8AOc0aJ8iRfso2HYR+5L2dy0FPzPOUQZG0QuA0h1jJOUE9acpOuHKlmnI0NdcT/kI9l9PlLSf2RY6xUY9XDhuJJY4wvaT17F3TKD9/BfJefvguaLfX4XdC6fqLeORWgwnOYxU2HQYfnUwDb0cPKCbzJklbYrJckLvP4DXeFmhhs3xzoYEN/bKoC9sChDP3Q+QUkDDYwQWczOgYb9Ld4dMS2j55FJNxhfoGc9+weC9/Ue6AP35ocIZjDmHQqFSpMmFGOUrBMwcugOJ26CuYQUEas1S3Mp2S8aViUvJPZakqU+KzCN+zKwuahxO/ncevG2xbr/RfUY/Oq0isYPGv6AiQaC2Qa5XkyOart0LM+IjK3zxGo5aqYhVJaxVLed/CXKGnEBp+F4VXFlNxmLkMmc1aXdmj1aAcC0oVb6dgurLPamZ3V0Vmd5a6V1dZZXZUlU1JY5caLVjMUhoE/ZtN5jV9LdPQEoQGMzgsdeWCoPCHXHX6x3azP1LvDbG1HDlRaVMh6iTp3KOYPD0RA40cPR4z4x3FwBWaH4sxQ+lPMs3GchceEWPSJQpzBfkoI6gGvQWz02j4NvdfxecC9royGRMAKjVfefzPQYMrSINtN89A4BTdEblAHbkrSIaMGFcbY6KSoY3B8TjHjrdMRadjXBOhL4mPaq0ahMreIDu/lPXNs/WxgxQVEjJM4QEV9w4yV9QihUMG7qSemj79sENCrnMSb7FshI7XQAW/NxG2GWFVNMH/elvoprr2ktrDVFb1Ca16QpPvD0XhSC25c6+JRS2jMjGm3Zx+K/M1siU79tQX6gSxwc91KdeTZGmvOi/rDjTz2fFYY/cUmfXoGeaIBFd+b1ijZGxi8K9cvSRP+ShK2Lgkitf4QDz2TX4lho3V7qtGyv5osf6M7Stwe9AkQtu+ZL22oyvK9jZMiFEQ+R7+2WhVzYg6s0mutMKWwPVXN9HlgDOIcZhRmHAZiUiyg11xzG8hqieKFcGTg2lA1lrsx7DvLhJyGoStT9otQN1TGcTqfGd41na5yq5FzZVxKJJ7S3KJK5mVF4jFXy+nEc2oa+lW/6220r3vlksSVrJIdb0N/tm/g2VW5WrdUrV2o1i5UK2235PD2De60z2AHm5nPi1pXL9d7DeajZHFkO/+NdpMW7MQJDBJPGPTkS/KbUpQyff9QzGz/UhEjTB0b/eeVgj0wfLq2d4eTcVZb7EdTtRuQV7W8KUU5bHsgHsVXQLR6EIbq4kz5XhZvaZa/8E2Hj4nCRZ9yQQt+M1RXv1LVEjo8hMp4VBgfqIk+/c/r2ftNmGw2b+J9dtoTEIYv2usng410C3+j7xO3DWkDvMosWtuPpsXrZOS0+Kbf8JsVapu4Aurz9YU8rLXwjUofbwy0Gw3PPjn7dzE+eQl8aiy9Fg35rbbfDrrOy69+98WX7jrfu3P/Nc8K7A5UCxvpebY6cQ0+y/CtQiw+0NdFTR/75lV8l3NxZMXFZE0BJxYAFFzzcHpLN/Xs6+nH0pDXUzYpkAXYrRuP3uSHaXPDbx1cAvqWRumFpzsumqDQkiPKKztfrxE0+GkSbv744ATSCFF0ZiMm6OTkghaqrI2SlCdTjIeaYWj1/VjFdqP2ckTuNgbAwhdDsSAeMwI+d5a7Yeequo2F1jkZw0c8UUY43lgI3XFs7PQih/d6AWIW0+MXu8lCX6IQmhJIsPoyBV4XGsrNIDPuONBKpLFRLe2JqSH3s8zHIeBNC/3OGhv7hmK4xwc9owKZWQ58htgzrMYNrzwF697gXm/jxcMp7DReS8K7IdA3ENJw8DWjEz0feILpDIJmX+pSvVlHbmmA6WNJeS5gpAujItUyTsJwd0AmiK3jWYBVxfb8WLcUsAOMO4ycbq4LtniovC0xLwVCtdcOQtvBJ9+LpfSKErZi2XVpppeDVhliyNULUK23IjS07o/H8wk6cpdB3m6eC1QtWnGpQY29rp4oRLsmws3HIr5C0DixtQOTpiofRNGMYCAiIBoE3D8Y9AvkYt710Y4ma59N15uB4TJAW4HyFqDTZONxszws7eroDWQoiqAoLa2Tj8Qf2/5rBKf42tuiZFwTxpUxOgX3nFF/gQoPw4ffYVJk+wwWdkHy7gnpKpS3UetudTqQWmRWVOhmeQ1XBWUydciW2XGOqDfq16CWx5bwEu+jhogB0i+mNcozCcxUr5iYLEKy6Mhws9oXxzpK+hJh9ZmdihaDBQV2oIb11JKhw+iHklLKl8bwjULQjEALEvzA7XEzruyj21MREt1pMpEFtmQqRWKQv89ZV+X19bCw5UpuiGRA5lrCPQpRvruQsZgW+yfrnKwE4QvpQKODHxF2QYwcvinADEIpWOIZtwCuJRKv9EqoFUVD3FfBF+jxIT134Ef5iI9Rwz5fHaN7WvjPYP3TrfqiPTqo6TWKL3Iy+TXWrVdrWa5dvBULqB3aKs2WpaC1vYplw2fM9A7G6Dx3/DH57ct3ro+qPIXM1db2ilRLxMOVAgSgpkEpofRqpfkS4QiUV/slwVsKexUXTysW1b5cUO1vZDHt9RsDWk97/Sb8GOGP1kCtrX1zXQku0v4q1C3dVah3/z+SOg7pPHI/n+atnq+PbN03GvNVBxTiNL58e6TmAzpkG03jPB9Gq3FyQYycm858OwfpAPYQdX0JpJ9iRBtjq5Hl+cqikpsPW6E6IsKcmiynWf7GRkvxTl4CNvdUHifR+I0VPtwYHrY2ap3OVvsGLmABHzXzIAdRTxTyO+WrMOKCpbgTD1gDoTCfp8PD1pBe6z1swayK+pCIwaAEMHc8cXudjkmYRasSiVOglbL5wu3hBRp8GyNZHg3TOcY2fYNniw7Lb6MjTZcH6IIqm8QHwzH84cpF2ClFRXVflndPJvSIZTo6cmguyWn7JgaKH89jPoBfZPN9fA1xHONShKL0ZqW4bS1sboFrvu8IdAMTNIuyI2S50XSxG4XQRWVisHwtKwQn4K55+Cycu3inF1vEB4Lhjzi7M271UmRCSqSOJjspxdpFFkL3ZRd5YFD+LYKy7vqs6KQBfYnQRXI1/OUzwJd+yj33voLDzxoZd422eOZgyml2pMcsRjQbwXYvjhutKZInaLExUWr/u9DgcJM9HaS14Sb7FdHLsobX0E1ySpDvzU6PasI2n/fy51pe2b9o7dpCBwnUYaTWYPoece6bzYaV+eYK0I3xn4Nm2XOUa9xYV+MG1qDgoOiWx3MGXwF+od2eA+5BERkOWL/OXYwVV7RaLlfps3nnnXcNeX1gNC6g7rPJQvYVO6SEH9198c++/9rwpRe/e+/OvT+nqMCu8PKBLfQbOhpH7CtIcQls93oZbLMSbMMA2xJgRY0CzFa3DLNTCbNrwGwwTD74jcgruAS53arobbcCcuO6htzpMmRVaFoBuHFJwO1Sl090GCu6bFCj+4wiHr5c1Hj9PuzLg96R9x2RrT3EqdZAXka7P5vPl7v6MiEevmKsmRz4QIaB33fwaqEIPO5sr4DLwPKZOrtApDwAfOxtnoEgA9xFvENirXNc/7sbu9SBXewAdtHbbG9Qxu2wXcxptmRWp5ClhP1VGg+FP4JyhKSnPUUErVZHX4Gwb5A2u+svkOLOIwJzXW/Yht0XETgF46mLYDzGzbz5BLhwPgNhx8ftsj6OR1NA3lj4oYA4vg3I1I+70EWUMb2bh/O4xNtT/HYKhXpdLfEyp3okFPaAVQ5CEt0bpLcZrIsWArgwLmIn+Npnji+I0qV7gDbG2GUwf9DTCd6FBb6BMi/0cTXCZEDBJFmuuSpauApxS6Fp83rZanzspoB42McUf/FdMVNuz+ZDfV0GhHvSZ6HM8QlG0sSplIFDlNONDCykOuCb/aobBCB9wXI8AwWpSWs/dhdOOAKXOp2vjmBoNWO/wIfEInKMCII3S7F0VP4lIv3dLEnXxWhJWOsNv4aY9g8823pkD1CeqJbiwyMTCAuXsRmn6voQO1TYy8e+gkvrCP/ZhGFtNK9tvmGtKOO3ctM6KF/lI2aF/fFCcQOB566P4xtshha7IzV7rgIXSO5nzAnOpzr6Z88BoBkGSa4D/DPQ1Qqki3XWEy25FmhyFXBtkqU/QijAdb5FYoF8aCoY5fsoGAgZwlcPoPpp009bftr2046fdv30KjtRPEibreYNv9VoXa03OvVm02/6LR92jdZ1v33DR5tDE8vALq3KXIcSLfgfF+r4nbbfvEqFmqoQZF71m5BxnQo1/PZV/waVaYky3Xqj5Xd8bPEagoNtsdMEcFSorQvdAOAEpoFF2m3sVoub66hSUOQGFYIeXANdCzveuk6FuqoQQL2OxW5g1zEMPYKjMldVGehpR/QcenUVO99hBFwTZfB/gKRmB/uFo29ie00GdF0VAgjYvxs0dhhXl0pRoRuqEIwJJB0segNBta9hnxiX7YYudc3nniPurmMRVGehiET3NcA4orJNvbpO7V33m1yopQohqmlumwyqg5NC/W63dSGcXRwrIgk7BD9o4todVQZymgKOGBrUv0aFJLav1xtNwOM1mt8ukRK2QWWu6jLXqUc8b4wCSOFS11QpbKlBPWpLLCE9UanrqhSOSFAc0gnhqdWiQjd0oRvUobYgOKSmq/71gog9TqKddE4Hq18zjvKfUPb2S5FDlAiH770BG80yss8K7hyZZ/KROOqTZpNtM3PbypQBJ/I9OgHOJ0mKT0hG3nfMT/ngQhRGfSw7QJjb/NPa6SPvVofeOV7QIVDk4fUV/b3tVZ4Xm4b6oqcvDnQ0jyc02D4sqIGOyapUBvbiLt4kKj5DToXWusDQ2w9K3avlllLomsql9D8uFAEN0ARwKNzsD/nijlV0Oj+wiiq/+arC4l0HccsENyT2XC8UE97uKvgY+csfmv7yDPxEVTsxEMmRa9H9YAj6em1Cjw4IWcSXlpx5ppA8DqlIvy/eJtvURQbqxcc+ORVM/Dr/Hfg80V6AJsk0AlXZDPwg48qCmAiDvM7BRHXDm22vSmYsR41LhV0APXSBcDDMPr6NyfJh1pLuAUI2PArHcgzlCNoct3rcNwdXWWi2EjG65ck2nVi9zotAp/QhMWyoEIWvPwxrr9dnKzyHEr2BlKP6kTRdbNWO+KoU3ZQSbd2hoIZkqx1yNGPE8zwFMQzH/fpDmODXHw6UT9+SeMMUTXk7wRTEizdrd/yjh36GYWfY+V2934wDDe/8m211Jz/PM2HyrNWOHtYxn+5ACGMUDCpfmgWOHsq+G6XEmmuFzTrA28rxMb0J1pQ3oyoYgLk0SwH4jCnGCRW3hywn7uLcL2RwPXwhMdlsSgnaX9hCsEFxJ4Vlgm+GzWZxOubrBBGwHny/QW8n54dYbYn4KWH3Qk8W/WqBKUFfb5xzK7/tF12VWRH7vn66Ex/kRImxHu3G0bgwnPp+XucROXpESu+8G412BTdQquVOnBLKxhzFg7Y10BqnCexpUl51nOeBf8fs2oiKo5xjGRDb2cWoQ2gviA+BaaQRPRZn4NSXBuY5vp5WtCmvVTnHE+9WaMzF5VhHFkc5WdOTlF7KJeqRwrcr6OFrxMC1DvdgwHN8WJeC5whi2k74UvklQuaKoNBm+PlCmBEjQnx1qFZ2hbhcYNaLFMtKtdCm80olURO0DrtQUDgvq0YW6q3RJ3Wh8nV2qUs21t6kNz0UqD/C478oa4yKZrOC9jkwX9F8hRBbn8b78bSwLBWVOPu5IBJ87We6wsUTFPwl8orYueYudX4QOcvXatRzpONNvWn7w3P6Ft9Z52h25nNc2MVL9oNaEi9MiprUnNmaHL98LoBbV3j0zKUjy3CKLmO/Wfrqagndjh0hVwdmKOmLLKA8XnM5kTs4VdTyHFkc5a0CIw/lGs4rImyYh4Y0W7JMAE2I7LBvlBud1zOsE+3voBmrcEHwsL9nRJjRsAemw7ns10nh1czSa5BW3GPgKOuiHLsKG8LnH3+WDssUOqWnfVUpGNZQXwgTeKdFpmNAaIc2fXdMLcZzHGUIuGl3N8HrdKsBo/ilmyhY8s1WrCyrIbvSpdsqnhCYjdl5VmuFapduzroXZ7ZlZFgNmRUuauXEZET74br4mhbNSreZIunawSqlq+U+OT/ZmRXRZUoBLavry+xzIIigl9X1ObNQ+6TASK0VW/R3jEewyeMqP95Db0fBFyzPHV1OAOGiEuKasuj+yQW560bxum7Fq2xmOx/q6jpIwxoQ6xwx45Hi7Zd02LnVfUZJcDmfDycYxozsszISOYBSjFFetQZBNzSMM3Lj8vX+pDq7oDebp+RqY/Iyv8h9/Ape4Vet6ZJKUVqJpQishaCrA7NrMJTjUc8YDfo1jQY++idpvmxsP3JEHBKanzQVS1W+PqxGLOYeDS6++kLrif5CA4n+YguI/pamjkGpgWfut9W5Quc1QkBfCctGEijlmzuWL5HgFfp1yepWXxStfNv5/moWpXWMDYAk6oyiVR7nW/xMTB7wmSB84Wkqky0UO3JyuksS5fl8xH4+UtIBQgfWGloKtjElPff0N+88/eD3T9//Z+fsk5+d/eTXzunv3jn78MuzP3zg+hWVyO7lPv3FW2e//NB58ttfn/3DpxfUIPOXe/bxW3/84slnH3NzzukfHp09/qcLagpbmCvr/ObnZ48f1c5++/j03bfq8Ofsx+96F4BQdjIX+vrk00dQ/NHZX67tsiVquC+/4Nzn1VQoY0oMrkDC2cfvnb1TBlfY+eVYzn7yMfwplS7u3e4PIME5e/+ds4/fP3v0L6Xy1ubrIlI//P2T30Nn/uFTmtFyn4r7mPsa/XLO/vWT0988Ov0fvz775VtVFcS25f5b+FtZWKx/QajnENzZ735+9pvHzumvf3f24btnH37gKAo8+/CR8/T9x4IQn3z6t2d/955z+qtPoRXn9JfvAfU4REaQT7QEhf/5yWePHJ7as8dfnv7DYzHBkHP6k3dOf/JJcA4Vd5/85t2zjx4B0Ednv/kcGjt79NhB0n7nA+fJp4/xz9N3/+npo8+xY60/ftH+4xcdSBf9e5b2eA00/32r5Ww5rfa/73TFCjj78HMc8tmv/pcE96tPGa8w6399+tNHp/8Ay4y6eQojlZUeXa5ZuYDO/tvbZx++JRbQ2S/g16P/rBMEtTD2/+nJv8Kof/pr+PX0/c8da7EBUh49+Q0VhCbP/svPnv7i5xf0QK+/ZuP0J/+ErYmFaNLQk0/fcp7+9R+AyOVcwsQ//U+/B0SfvveBjYzTzz4/+8WjcrPyMhHfJzR9qsXtYWvjkOfd9vMG5inIfvEonCFLaaS2J0Iw7evA8FygGEFxb78H/++jDRLY+wzdN9J4J6JAmaFDgfgzessAtdkcwzuzuwUpqDIiJG4CVYMS1xl77cJDDfvOLaeOQcqKtg2CpL2oJxFaP90ebxMgfaEZXdnwyIeaVzQ+zEwrG8oUHnZhmOZ1DruRghwsm3RP//7x6cdf4IJnFnr28dvO2X99D1iYc/Z3PwbmUPJVtbqG1/yK+ojoqgv0+uSLL52nP3t8+tnv5cJWBEbs+lNce0h40CzQmUg4/ccvHdgYnnz+FhAerDvn7NEnp7/6D0/fJyo8/dW/Pv0v75z99W8F7cGCeAuZwR+QX7wPqwGIE9It2qbl9tHj07/5xAHOfPbJW7iIn/z2PWrp8cdQwqBlW+iXIgE93SxiKIPGs5inaObGOO5LZwKyLNJMvjs/cEAGTTjSu8BSIOPcRHtV1CPFv8usBnIE2r9VspYh7HX0RLrNnr/nFahKrpzzTOPGZBKP/J+nv/pn3C0UygmBH8GO9wHxzR//LZQzdopXYvSudn5kuGIxIZz+Emb1Iya49w3ca4xf4lDCyBK+HPKJP9Q7rKMJsnzKe3p40d/MFOKBVB/woZ8D8mvOMh2RDD6Kp5NDw76ig2KqxIpXgeS7PNrkouvp1KqKkkpiFelBpljgTfaqi1rJRaj6ZIBhwnclSLOcmWidABHTcXv818xBChUCGOTjl3XgKlU8a1rYKd44ztgyTjHY4VGdtKw5y6D3HiBlzkxyF/di8smL30S7rhHSwQpjPKeosE6+iEfo3u1clQ8/cBQJySNKrsSwE+QJS/7P7OfwzO8gfW3HCN9662iNk4QdsPnrvrdUes2Z/AjouHs/ma8KgTEv4VZw6aCja0OEfkX3hILvgRXi73zfg0LMvm/Q96Acq8/wPRCbd5rHoxVFr7WMcOuCrFq1c2CdQ0ZkuXZz7ZXT3G+R1TECzIfh9nMF939XHBMNkQjMAeGRQM6hryR9eGy/lJ9WOMqy9dK4W4EPk6IemNNd4kLwjkudzA3M+4tyncuTSjMiSPE6oQVHnlWaTwlhpAvdP3WIiNeh8RnbrCrTNPItJvrxSMIUVjPTAIZP6YVzBfskQcPWBwq4Q+wPq4tB/1TBwmVwKdpMlFAjrJAEjk2Q+5VVRqUq0Pk1NfglNTZqsTGLjVjSeCXXiF9B9n4FMQ8q7bj8+B/3YDRBM+liYplny/bRS15UF3dVDGrKYmSnBjEZZ+utZzSjpnE8Hi4P5uLZwRNlW6sitnprPa3pa/nPSmj0UGz1YpFB3XGqcn1iZiDY+xNNsjIz8vMM+ahGcrI/n47xcRF/BbJ26LrmCh2HkFGHAsYhIkbuCd2z//EhyMJ05W8sXWvcJ5++B4o6J96Siac//QXoNG5pDifuMbV/0nOOoYXezskx9uDE+d8//lvnGNrVKbVjavXEOUbz/dhTOR63xS09C0DulOdKlOAzlcC8jJEjfrR50vVhamgyBv5I/jJ5OZe3zDdcB6eO6/AvQNJjt1zz7OO3uLEa2mk8rosTznX515q6loWSazKRcF3xu6LNv/v07Md/gx1GQx9XLNMSA6lKd8/e/Zuq7hBundO3P7RBV5Ak47IivQR6Ahh69PTv3wVF2ZFWzI9+ffqf/+Xso3+E+aaoJpP+gyvmloqvGJwgygScgWHn1gK0MTIp7I6ORtPYkqblXcQ0p8eS+c1dvPJMz0Djq5PDEoZuNwbKL8C8niLuQ8udkoDuRAu9d8oHD0Rr3u2mFa1CFZcF+m8M6vo3cC2+elHcfRU89aCWCMkgQYY141lqDVGGqJEJ4va+LGqMAl20pIfeeXjxikFgDLSoS9EEEc3MOmq6dCtQOPB0x/DT9vD7Kuq0lK/se5Ryp6jyN1CBLSpqNKtrqEaY3Fil3a+CqQrg/lIFQW5AAGJSBUDnj+x83n8gmX+YeVKjZBWaOKOZrXVPa2o53qAig0vUEHMrKomvqkGYlVTUoSLxehWibw4a3TRiRS8epqCIYWTGCV6sHU98J8XLM9vzLA+vFi7SfQ/WtqlkkyThHOBDIhQrLaZrazMgoZyUahZoqJiPCXSfcBZhjDX8TDJYkVPg4ag5isuH1X6EzdY36D3IvVoj2Nw8TyIyuiRDKOkXhaam4MNtmLIPOpVlY83Nvu0k/KqSgU/Coe8km03MOiBTIiEIg8wsA+fu4Wi6Giu8bsdkV3HwviDOor5ymO6l8wNpaFync9ix+RbrVQ7qVrXScdNJD6tQSe69hmuiiRseJcYZTM1kAORTlme6it0HvIAqh86voqSTz9GPlo30dRqTsw80JU5m0ZKiHrozPMvGKHsW3CFRbMql2FKfKgFmq90NGs5mdWGSV6gw/fK2WuvLknxCZenXuWWFPEKlpWyy1TyngjqDpyrqCyoF3XV1KuQVql2RjnDWtl0hnDD+yunn9sdS9QVWrSRCWaXDqFhQ6uyH90KcZs9PJ76lmm4aW45nL8jKZ0AbA/Wcyl4cipL8KqfijrSMRJbn2eH4sdqzqmfzIewu0/mOUs3krUsdtBMmZKvWCNrdzTFrQ2N/6A/ZhXMvHvimh6eovSXj6PNFACM40TepRPmFWZO6JW0qVsC0yihGInSfGOVEOkcO/cm60XFExCi1g82IoW5QkDvPbCCrLljDknUERJclTBsK972/t+lyWItBiH+qC+DDIHy5WQVIgyY9vxF0ukgSe/KFdolzsb55C+kEDc9CWGE5GkGTB9XDsCgEG6xe0VIhlXeqbfyqhaF6wfTI8VxcfiELS5Y6O4X9X8TYwDcl+7QNcQNDn/ckbqPfuz4YFBtRS8KOZsnWEi5l2okTxO0UxFOcDj8fyz3sYSg4AIewqguDKU4txvg6FLlQwXyBzLrrRrOnnh15uPHQfMbCNMtgJ/idB2mzkVZr6q7skmUJoeJGaaUgyKNDe5n4hLR+jQkmaDU8v8ZLNWi28Tct2KDZwt9i2YovtXiDxnX8rljCQbOLORULWdSxljMBHljKluw0LNWQ0IGL1i8vGr+4TMy3EenpCzI045N4/yeN1YPRbFij1MxLJ9s0xOccE1/na+KJxtFCLOYEZL3lEeBsn6TtND/nQlFR+t6P7fdDffnIOIakSCaTGEV/ZxEtoQy6q1HCCCSmUZyChDTPzVfTc770IwNNyNc9xXUfeskTT7Hi7KjqRU/1RvAaib11QUxi7Yj5NV8BtSNT2Q+Aopz+LG9/ivkwnv2UW9gFOpNWmbDfV2kaa82ulLS3trqKuxos4FzbKpt+w/NswtqoSuqe2Bs4nz2Yz1NKYXdqsKHArKHZsWl4+NpvoBrHH4WXTq33LfI4XPNaqn1TSKC+1OWCwX458ZEBw4xmQBslDm6yY8mojHZw+OcC7KK3i8HiLfbuHxtnIOQiP52GQfe6eCMbx2o9kr0ZdFoby0nFO9VY1Ha/XudNbw9QPdQzqXpcRzIi6/Ec0c+K8tpiQghY3zChBl9ny5Z5tbu8eNTWCuWrLfAR67uY7pcfVRUvtlpPc5cYDb7buPbl91vhee+3mj1ZJKM98Uoqhh7x+eIjqsLq/RLHDEmqD/sy/TwJD1acUXL1WsZ+O2qkcpx2IE/kwlll8OR1LZwHUD5SCXwJIVAsFfg/r39IMHlk6YFdwZFCEyP6KWJ8mMympoF/aNG2dk3LzLDh4ilcvEAGgrHYo0AMdM/+238gT9nfPj77+0/PHn3sFh8aj7xLdKqwGqhTxY4+e9fYiQ29Uz/8nB1RnQs7OZKWWotvrRPyNWNex+Z4shTjFwpfZNsESSEZLXxVDPbCoN3Q4YEL5U0qtpBa8gd7diyfAwOKK94yqFZbVPBB5TsfGoc0p+++dfbhz8RBWoFnP8tAqmi4OLivN5AwbJQHgt7D1WO5LE0SoPXEZ4RAl+EkYeHXDi3jH+1n/Cp3mZlT7ANzO2OpG1ESUgmup2Xxrme9+bETF4tKId4sSHIztBuHtaBzdcN8KLx4Dw7vYlV6KW4GrY5d07zJs7ZWs7uhh4RfqtPlzaWm+llJ6VVcqYz9Z+U6eFr4xy+Ek/aTLz5++sH757AbPPuhLAM2ureR3jGdz7NQ68NVYzBCldDe4tWvmzY4OidPMPQiVirREv4HY97RRp0SrDf1Dqtdkd6s2sFNREuXH2P3riNgz1/fdZ1VWrreOrZgjUVvIesbuR1a2PQuwXpMLrGGZi5NDPK2DPCK9985hwy0hMCiOU+mb5k6L7F5+6AWY5jNsCjrFB+g7/bM9+b1G9q2TFKglLXDnLh8qUCM0zk22tpsnlww7oQfVdJBRcqtZ2Rm38PXJzaN2+7Iw8PM5OUmC0BjrT7DkdNmdbxCfCn5EREY2XOXr7rIay10PQgd1CtEDbzlgb7WH/2j4ALO2UfvoEf86acfnH3wtmtpL1U9Wy+9XNDHJ599+eRfPiXn+L/8tXP2V28//avHzunffuKc/eSTs48f092TD98Vngjq9tXb6Mr900fkFc7NXNjD4l54fr8mRoWz3z1++sGjs//+5ZPff4otMk7owgz3URclxwic4f6DK6WNmvwjzt79G3Hj5sIuV+3gF8247jTdOcMrD3hZ4X15r+bsfb5XROUEPmlMnz0CfIo7Chf2rGrbuKBn9t02mHXhVgLj+uMX4mqS7g7QAQ7447fFRSm+cHExxiwOdhGu/uptfR8KO/TkN384+wPdtzr7BOn49J8/p6skgpwtolN4+irmA2RfeC8a6aR4UqXs12a6MHqCjtnslSWN0sB++bZ23sFbVZ/9FiiCbr/QKhOL7OlP/yNM3ZPfvet653SPjzBVr1Q0buyMlYpG2Et0zrj/97ndH2ul86074WJ1Xv/41FRjDSN3PwuyrMutJRxZfQLqgpWLHBR43dnHPzP7hUyfT9xgI3X++IXjBm/M8W1Sbg7vbK2/z65sBCI3iJbLDJ9c5lEBSHVeUSgR46EEBmoamjYzcaaibWFl0BTdHLpKweOhOpqNh8qc6xZfrlDv36F9kg48+UWDGbpBlJxJIeES9kUc0zdo/5SWjXhx3vJbe2IqtBC8C2J5hmFnzgMIKjgWOedozQi0hMCNHYYoja7EiU3Q2P0kI6fbkrRfnL73mFg3rIwPkZf/L+d4tNhoNhq9oDE5ee7sg7eMu2qnP//09MMvkX111fVgce8VmSnsWnpPoKu2QPz/8jmuydNffnT61z+X10T/7j28QSV3PHV9yls/KJP58GKna7/W4paehIIHqfEQJm2nQlrNsHP2guYEnQvtYYrrxfJO6wea3dFuhiwGZJ5P3iL5hi7kyQ3lsy+hBOKeb57Sfdiff3m5IVqyCgo8//WRU7xZXxyTZJw0FJgvv3D3uLqWZGdrEcB4lZNMexcO+r9/efrZW7TJspB79pPHp3/5Ad5R/OCTynvMpUc0inH59EJ2e7DGfMWcevhDXhzN3R4hCy8snfx/R8+0ow=='
_RUNTIME = _Path(_tempfile.gettempdir()) / "md_lotto_runtime_v54_final_verified"
_marker = _RUNTIME / ".ready"
_RUNTIME_VERSION = "v5.4-final-verified"
if (not _marker.exists()) or (_marker.read_text(encoding="utf-8", errors="ignore").strip() != _RUNTIME_VERSION):
    _RUNTIME.mkdir(parents=True, exist_ok=True)
    _files = _json.loads(_zlib.decompress(_b64.b64decode(_EMBEDDED)).decode("utf-8"))
    for _rel, _txt in _files.items():
        _p = _RUNTIME / _rel
        _p.parent.mkdir(parents=True, exist_ok=True)
        _p.write_text(_txt, encoding="utf-8")
    _marker.write_text(_RUNTIME_VERSION, encoding="utf-8")
_sys.path.insert(0, str(_RUNTIME))
import os as _os
_os.environ.setdefault("MD_LOTTO_DATA_DIR", str(_RUNTIME / "data"))

from pathlib import Path
import os, threading, time
from io import BytesIO
from zipfile import ZipFile, ZIP_DEFLATED
from xml.sax.saxutils import escape as _xml_escape
import pandas as pd
import streamlit as st
import plotly.express as px
from md_lotto.data import load_csv,sync_history,save_sqlite,dataset_status,save_sync_status,load_sync_status
from md_lotto.data import sync_incremental_official
from md_lotto.stats import number_stats,pair_stats,triple_stats,structure_summary,randomness_audit,fdr_summary
from md_lotto.optimizer import optimize_games, deterministic_top_games
from md_lotto.backtest import walk_forward,summarize_backtest,nested_walk_forward,strategy_tournament
from md_lotto.simulation import monte_carlo,theoretical_single_game
from md_lotto.ml import train_evaluate,walk_forward_ml
from md_lotto.diagnostics import recommendation_actual_diagnostics
from md_lotto.transitions import latest_transition_report, next_draw_adjustment_report, adaptive_priority_five

st.set_page_config(page_title='MD LOTTO 6/45', page_icon='🎯', layout='wide', initial_sidebar_state='collapsed')
ROOT=Path(__file__).parent
DATA_DIR=Path(os.getenv('MD_LOTTO_DATA_DIR', str(ROOT/'data')))
DATA_DIR.mkdir(parents=True,exist_ok=True)
path=DATA_DIR/'lotto_history.csv'; db=DATA_DIR/'lotto.db'; sp=DATA_DIR/'sync_status.json'
bundled=ROOT/'data'/'lotto_history.csv'
embedded_bundled=_RUNTIME/'data'/'lotto_history.csv'
if not path.exists():
    _seed_source=None
    if bundled.exists() and bundled.resolve()!=path.resolve():
        _seed_source=bundled
    elif embedded_bundled.exists() and embedded_bundled.resolve()!=path.resolve():
        _seed_source=embedded_bundled
    if _seed_source is not None:
        path.write_bytes(_seed_source.read_bytes())
_SYNC_LOCK=threading.Lock()

st.markdown(r"""
<style>
:root{--bg:#050814;--panel:#0a1020;--line:#1d2b46;--muted:#98a4b8;--blue:#1687ff;--green:#28d06f;--red:#ff4f6d;--violet:#9c5cff;--gold:#ffcc33}
html,body,[class*="css"]{font-family:Inter,Pretendard,"Noto Sans KR",system-ui,-apple-system,sans-serif}
.stApp{background:radial-gradient(circle at 15% 0%,rgba(22,135,255,.12),transparent 28%),radial-gradient(circle at 88% 15%,rgba(156,92,255,.10),transparent 26%),linear-gradient(180deg,#050814 0%,#070b15 100%);color:#f5f7fb}
.block-container{max-width:1120px;padding-top:.45rem;padding-bottom:6.2rem}[data-testid="stHeader"]{background:transparent}#MainMenu,footer{visibility:hidden}
.hero-shell{position:relative;overflow:hidden;padding:1.2rem 1.25rem 1.05rem;border-radius:24px;background:linear-gradient(135deg,rgba(29,12,28,.96),rgba(7,14,31,.96));border:1px solid #263556;box-shadow:0 18px 42px rgba(0,0,0,.35),inset 0 1px 0 rgba(255,255,255,.05);margin:.2rem 0 1rem}
.hero-shell:before{content:"";position:absolute;inset:-40% 35% 35% -20%;background:radial-gradient(circle,rgba(255,60,110,.22),transparent 60%);pointer-events:none}.brand-row{display:flex;align-items:center;gap:.75rem;position:relative;z-index:1}
.brand-target{width:56px;height:56px;border-radius:50%;display:grid;place-items:center;font-size:2rem;background:radial-gradient(circle,#fff 0 12%,#e53b49 13% 27%,#fff 28% 40%,#c80f21 41% 59%,#650713 60% 100%);box-shadow:0 7px 20px rgba(255,50,80,.32),inset 0 0 0 2px rgba(255,255,255,.55)}
.brand-title{font-size:clamp(1.8rem,5vw,2.55rem);font-weight:1000;letter-spacing:-.045em;line-height:1;background:linear-gradient(180deg,#fff,#eef1f7 56%,#b8beca);-webkit-background-clip:text;color:transparent;text-shadow:0 8px 20px rgba(0,0,0,.24)}.brand-sub{position:relative;z-index:1;color:#aeb8c9;margin:.65rem 0 0;font-size:.93rem}
.sync-ok,.sync-warn{display:flex;align-items:center;gap:.75rem;padding:.78rem .92rem;border-radius:16px;margin:.45rem 0 1rem;font-weight:750}.sync-ok{background:linear-gradient(90deg,rgba(18,82,50,.44),rgba(6,27,25,.72));border:1px solid rgba(45,214,112,.38)}.sync-warn{background:linear-gradient(90deg,rgba(104,62,11,.38),rgba(40,26,8,.70));border:1px solid rgba(255,180,55,.38)}.sync-icon{font-size:1.25rem}.sync-main{font-size:1.02rem}.sync-detail{color:#d7deea;font-weight:550}
.section-head{display:flex;align-items:center;justify-content:space-between;gap:.6rem;margin:1rem 0 .5rem}.section-title{font-size:1.27rem;font-weight:950}.date-chip{font-size:.83rem;color:#b8dcff;padding:.36rem .62rem;border-radius:10px;background:#0b2242;border:1px solid #174d87}
.lotto-row{display:flex;gap:.56rem;flex-wrap:wrap;align-items:center;margin:.55rem 0 1rem;padding:.28rem 0 .9rem;perspective:1000px}.ball{--c1:#FFF06A;--c2:#FFC400;--c3:#9A4E00;position:relative;width:70px;height:70px;flex:0 0 70px;border-radius:50%;display:inline-flex;align-items:center;justify-content:center;
background:
radial-gradient(ellipse at 25% 14%,#ffffff 0 4%,rgba(255,255,255,.98) 5% 10%,rgba(255,255,255,.40) 13%,transparent 27%),
radial-gradient(circle at 35% 30%,var(--c1) 0 16%,var(--c2) 46%,var(--c3) 100%);
border:2px solid rgba(255,255,255,.95);
box-shadow:
inset 12px 13px 18px rgba(255,255,255,.52),
inset -15px -18px 24px rgba(0,0,0,.62),
inset 0 0 0 2px rgba(255,255,255,.20),
0 11px 18px rgba(0,0,0,.60);
filter:saturate(1.65) contrast(1.14)}
.ball:before{content:"";position:absolute;left:8%;top:5%;width:52%;height:24%;border-radius:50%;
background:linear-gradient(168deg,#fff 0%,rgba(255,255,255,.98) 30%,rgba(255,255,255,.30) 68%,transparent 100%);
transform:rotate(-23deg);opacity:1;z-index:4;pointer-events:none}.ball:after{content:"";position:absolute;left:13%;right:13%;bottom:-10px;height:12px;border-radius:50%;background:radial-gradient(ellipse,rgba(0,0,0,.72) 0%,rgba(0,0,0,.36) 48%,transparent 78%);filter:blur(4px);z-index:-1;pointer-events:none}
.ball-num{position:relative;z-index:5;display:flex;align-items:center;justify-content:center;width:72%;height:72%;border-radius:50%;
font-size:2.08rem;font-weight:1000;line-height:1;letter-spacing:-.06em;color:#fff;
-webkit-text-stroke:1.6px #06080c;text-shadow:0 3px 2px rgba(0,0,0,.95),0 0 5px rgba(0,0,0,.78);
background:radial-gradient(circle at 40% 28%,rgba(255,255,255,.10),rgba(255,255,255,.01) 48%,rgba(0,0,0,.16) 100%);
box-shadow:inset 0 1px 2px rgba(255,255,255,.25),inset 0 -2px 4px rgba(0,0,0,.30)}
.b1{--c1:#FFF06A;--c2:#FFC400;--c3:#9A4E00}.b2{--c1:#61C8FF;--c2:#0066FF;--c3:#00165E}.b3{--c1:#FF7770;--c2:#F00000;--c3:#650000}.b4{--c1:#FFFFFF;--c2:#AEB4BC;--c3:#30363D}.b5{--c1:#70FF86;--c2:#00B935;--c3:#003D12}.bonus{width:76px;height:76px;flex-basis:76px;box-shadow:inset 10px 12px 18px rgba(255,255,255,.35),inset -14px -18px 23px rgba(0,0,0,.47),0 0 0 3px #ffbd28,0 0 0 6px rgba(255,220,88,.22),0 14px 22px rgba(0,0,0,.48)}.bonus .ball-num{font-size:2.12rem}.bonus-label{font-size:2rem;font-weight:1000;color:#eef2f8;margin:0 .08rem;text-shadow:0 3px 5px #000}
.legend{display:flex;gap:.9rem;flex-wrap:wrap;padding:.55rem .7rem;border-radius:14px;border:1px solid #1b2a43;background:#090f1b;margin:-.15rem 0 1rem;color:#d5dbe5;font-size:.78rem}.legend span{display:flex;align-items:center;gap:.32rem}.dot{width:11px;height:11px;border-radius:50%}
.kpi-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:.65rem;margin:.55rem 0 1rem}.kpi{position:relative;overflow:hidden;border-radius:17px;padding:.82rem .85rem 1rem;border:1px solid #24334e;background:linear-gradient(145deg,#0c1423,#08101c);min-height:112px;box-shadow:0 12px 26px rgba(0,0,0,.22)}.kpi:before{content:"";position:absolute;inset:0;background:radial-gradient(circle at 10% 0%,rgba(25,132,255,.18),transparent 45%)}.kpi.purple:before{background:radial-gradient(circle at 10% 0%,rgba(158,77,255,.20),transparent 48%)}.kpi.red:before{background:radial-gradient(circle at 10% 0%,rgba(255,65,106,.20),transparent 48%)}.kpi-label{position:relative;color:#c9d2e1;font-size:.82rem;font-weight:750}.kpi-value{position:relative;font-size:1.75rem;font-weight:950;margin-top:.55rem}.kpi-value.redv{color:#ff5c7a}.kpi-sub{position:relative;font-size:.73rem;color:#7f8ba0;margin-top:.12rem}
.menu-title{font-size:1.15rem;font-weight:950;margin:.5rem 0 .55rem}.menu-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:.55rem;margin-bottom:1rem}.menu-card{border:1px solid #243450;border-radius:15px;padding:.75rem .55rem;text-align:center;background:linear-gradient(160deg,#0d1728,#08111f);box-shadow:0 10px 24px rgba(0,0,0,.22)}.menu-card.blue{border-color:#155aa4;background:linear-gradient(160deg,#0c315f,#07182d)}.menu-card.green{border-color:#2e6f31;background:linear-gradient(160deg,#153b18,#08190d)}.menu-card.orange{border-color:#8b5117;background:linear-gradient(160deg,#4b270d,#1b1006)}.menu-card.violet{border-color:#67318b;background:linear-gradient(160deg,#351449,#16091f)}.menu-icon{font-size:1.55rem}.menu-name{font-weight:900;margin-top:.25rem}.menu-desc{font-size:.68rem;color:#bac4d4;margin-top:.15rem}
[data-testid="stMetric"]{border:1px solid #24334e!important;border-radius:15px!important;background:linear-gradient(145deg,#0c1423,#08101c)!important;padding:.75rem!important;box-shadow:0 10px 22px rgba(0,0,0,.18)}[data-testid="stMetricLabel"]{color:#aeb8c8}[data-testid="stMetricValue"]{color:#f7f9fc}.stButton>button{border-radius:12px!important;font-weight:800!important;border:1px solid #2b4772!important;background:linear-gradient(180deg,#123f73,#0b284b)!important;color:#fff!important;min-height:2.7rem}.stButton>button:hover{border-color:#41a1ff!important;box-shadow:0 8px 20px rgba(15,115,220,.22)!important}
[data-baseweb="tab-list"]{gap:.25rem;background:#070d17;border:1px solid #1c2940;padding:.34rem;border-radius:14px;overflow-x:auto}button[data-baseweb="tab"]{height:2.65rem;border-radius:10px;padding:0 .8rem;color:#95a1b4;font-weight:800;white-space:nowrap}button[data-baseweb="tab"][aria-selected="true"]{color:#38a9ff;background:linear-gradient(180deg,#102f57,#0a1b34);box-shadow:inset 0 0 0 1px #235e99}
.game-card{padding:.72rem;border:1px solid #22314c;border-radius:16px;margin:.55rem 0;background:linear-gradient(145deg,#0c1423,#080f1a);box-shadow:0 10px 24px rgba(0,0,0,.19)}.game-title{font-weight:900;margin-bottom:.2rem;color:#dfe7f3}.md-score{color:#ff617f}.small-note{font-size:.78rem;color:#8490a3}.game-card .lotto-row{margin:.4rem 0 .55rem;padding-bottom:.55rem}
@media(max-width:768px){.block-container{padding-left:.66rem;padding-right:.66rem;padding-top:.3rem;padding-bottom:6.5rem}.hero-shell{padding:1rem .9rem;border-radius:21px}.brand-target{width:48px;height:48px;font-size:1.65rem}.brand-title{font-size:1.72rem}.brand-sub{font-size:.82rem}.section-title{font-size:1.12rem}.date-chip{font-size:.72rem}.lotto-row{gap:.38rem;flex-wrap:nowrap}.ball{width:53px;height:53px;flex-basis:53px}.ball-num{width:74%;height:74%;font-size:1.60rem;-webkit-text-stroke:1.15px rgba(3,6,12,.94)}.bonus{width:59px;height:59px;flex-basis:59px}.bonus .ball-num{font-size:1.72rem}.bonus-label{font-size:1.55rem}.legend{gap:.55rem;font-size:.67rem;padding:.48rem .52rem}.dot{width:9px;height:9px}.kpi-grid{gap:.45rem}.kpi{min-height:101px;padding:.72rem .62rem}.kpi-label{font-size:.72rem}.kpi-value{font-size:1.48rem}.kpi-sub{font-size:.65rem}.menu-grid{gap:.4rem}.menu-card{padding:.64rem .35rem}.menu-icon{font-size:1.35rem}.menu-name{font-size:.82rem}.menu-desc{font-size:.60rem}.game-card .ball{width:43px;height:43px;flex-basis:43px}.game-card .ball-num{font-size:1.31rem}.game-card .lotto-row{gap:.25rem;flex-wrap:nowrap}.game-title{font-size:.9rem}[data-testid="stMetric"]{padding:.6rem!important}h2{font-size:1.25rem!important}h3{font-size:1.06rem!important}div[data-testid="stDataFrame"]{font-size:.76rem}}
@media(max-width:390px){.ball{width:50px;height:50px;flex-basis:50px}.ball-num{font-size:1.52rem}.lotto-row{gap:.29rem}.bonus{width:56px;height:56px;flex-basis:56px}.bonus .ball-num{font-size:1.64rem}.kpi-value{font-size:1.36rem}.game-card .ball{width:40px;height:40px;flex-basis:40px}.game-card .ball-num{font-size:1.21rem}}
.v36-badge{display:inline-block;margin-left:.42rem;padding:.14rem .40rem;border-radius:999px;background:#FFD000;color:#111;font-size:.68rem;font-weight:1000;vertical-align:middle}

/* ===== v3.8 MOBILE ONE-ROW FIT + VIVID GLOSSBALL OVERRIDE ===== */
@media (max-width: 640px){
  .lotto-row{
    display:flex!important;
    flex-wrap:nowrap!important;
    width:100%!important;
    max-width:100%!important;
    gap:4px!important;
    justify-content:space-between!important;
    align-items:center!important;
    overflow:visible!important;
    padding:.28rem 0 .72rem!important;
    margin:.45rem 0 .75rem!important;
  }
  .lotto-row>.ball{
    width:calc((100% - 20px)/6)!important;
    height:auto!important;
    aspect-ratio:1/1!important;
    max-width:50px!important;
    min-width:0!important;
    flex:0 1 calc((100% - 20px)/6)!important;
    box-sizing:border-box!important;
    border-width:2px!important;
  }
  .lotto-row>.ball .ball-num{
    width:76%!important;
    height:76%!important;
    font-size:clamp(1.35rem,6.1vw,1.72rem)!important;
    -webkit-text-stroke:1.25px #06080c!important;
  }
  .lotto-row>.bonus{
    width:calc((100% - 24px)/7)!important;
    max-width:46px!important;
    flex-basis:calc((100% - 24px)/7)!important;
  }
  .bonus-label{
    font-size:1.2rem!important;
    margin:0!important;
  }
}
@media (max-width: 390px){
  .lotto-row{gap:3px!important}
  .lotto-row>.ball{
    width:calc((100% - 15px)/6)!important;
    max-width:47px!important;
    flex-basis:calc((100% - 15px)/6)!important;
  }
  .lotto-row>.ball .ball-num{
    font-size:clamp(1.28rem,5.8vw,1.58rem)!important;
  }
}
/* Remove muted filter effects from the balls only */
.ball.b1,.ball.b2,.ball.b3,.ball.b4,.ball.b5{
  filter:saturate(1.75) contrast(1.15)!important;
}
</style>
""",unsafe_allow_html=True)

def ball_class(n): return 'b1' if n<=10 else 'b2' if n<=20 else 'b3' if n<=30 else 'b4' if n<=40 else 'b5'
def balls_html(nums,bonus=None):
    parts=[f'<span class="ball {ball_class(int(n))}"><span class="ball-num">{int(n)}</span></span>' for n in nums]
    if bonus is not None: parts += ['<span class="bonus-label">+</span>',f'<span class="ball {ball_class(int(bonus))} bonus"><span class="ball-num">{int(bonus)}</span></span>']
    return '<div class="lotto-row">'+''.join(parts)+'</div>'
def pct(v,d=2):
    try:return f'{float(v)*100:.{d}f}%'
    except:return '-'

def _xlsx_col_letter(n):
    s=''
    while n:
        n,rem=divmod(n-1,26)
        s=chr(65+rem)+s
    return s

def _xlsx_inline_cell(ref, value, style=0):
    if value is None or (isinstance(value,float) and pd.isna(value)):
        return f'<c r="{ref}" s="{style}"/>'
    if isinstance(value,(int,float)) and not isinstance(value,bool):
        return f'<c r="{ref}" s="{style}"><v>{value}</v></c>'
    txt=_xml_escape(str(value))
    return f'<c r="{ref}" t="inlineStr" s="{style}"><is><t>{txt}</t></is></c>'

def _history_xlsx_bytes(history_df, status_dict):
    d=history_df[['draw_no','draw_date','n1','n2','n3','n4','n5','n6','bonus']].copy()
    d=d.sort_values('draw_no').reset_index(drop=True)
    d['draw_date']=pd.to_datetime(d['draw_date']).dt.strftime('%Y-%m-%d')
    headers=['회차','추첨일','번호1','번호2','번호3','번호4','번호5','번호6','보너스']

    def sheet_xml(rows, widths, freeze=True, autofilter=None):
        max_cols=max(len(r) for r in rows)
        max_rows=len(rows)
        cols=''.join(
            f'<col min="{i}" max="{i}" width="{w}" customWidth="1"/>'
            for i,w in enumerate(widths,1)
        )
        xml_rows=[]
        for ri,row in enumerate(rows,1):
            cells=[]
            for ci,val in enumerate(row,1):
                style=1 if ri==1 else 0
                cells.append(_xlsx_inline_cell(f'{_xlsx_col_letter(ci)}{ri}',val,style))
            xml_rows.append(f'<row r="{ri}">'+''.join(cells)+'</row>')
        pane='<pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/>' if freeze else ''
        filt=f'<autoFilter ref="{autofilter}"/>' if autofilter else ''
        return ('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
                '<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">'
                f'<dimension ref="A1:{_xlsx_col_letter(max_cols)}{max_rows}"/>'
                f'<sheetViews><sheetView workbookViewId="0">{pane}</sheetView></sheetViews>'
                '<sheetFormatPr defaultRowHeight="18"/>'
                f'<cols>{cols}</cols><sheetData>{"".join(xml_rows)}</sheetData>{filt}</worksheet>')

    history_rows=[headers]
    for _,r in d.iterrows():
        history_rows.append([
            int(r.draw_no), str(r.draw_date),
            int(r.n1),int(r.n2),int(r.n3),int(r.n4),int(r.n5),int(r.n6),int(r.bonus)
        ])

    expected=list(range(1,int(d.draw_no.max())+1)) if len(d) else []
    actual=d.draw_no.astype(int).tolist()
    missing=sorted(set(expected)-set(actual))
    duplicate_count=int(d.draw_no.duplicated().sum())
    invalid_number_rows=0
    for _,r in d.iterrows():
        nums=[int(r[f'n{i}']) for i in range(1,7)]
        if len(set(nums))!=6 or not all(1<=x<=45 for x in nums) or int(r.bonus) in nums or not 1<=int(r.bonus)<=45:
            invalid_number_rows+=1

    audit_rows=[
        ['검증항목','결과'],
        ['파일 목적','MD LOTTO 앱이 실제 사용하는 전체 당첨이력 확인용'],
        ['최소 회차',int(d.draw_no.min()) if len(d) else '-'],
        ['최신 회차',int(d.draw_no.max()) if len(d) else '-'],
        ['총 데이터 행',int(len(d))],
        ['1회부터 연속 데이터','정상' if bool(status_dict.get('complete_from_draw1')) else '미완료'],
        ['누락 회차 수',len(missing)],
        ['누락 회차','없음' if not missing else ', '.join(map(str,missing[:100]))],
        ['중복 회차 수',duplicate_count],
        ['번호/보너스 유효성 오류 행',invalid_number_rows],
        ['최신 추첨일',str(status_dict.get('latest_date') or '-')],
        ['주의','이 파일은 앱 내부 분석에 사용되는 현재 데이터의 복사본입니다. 추천 확률을 의미하지 않습니다.'],
    ]

    content_types='''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/worksheets/sheet2.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/><Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/><Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/></Types>'''
    root_rels='''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/></Relationships>'''
    workbook='''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="전체 당첨이력" sheetId="1" r:id="rId1"/><sheet name="데이터 검증" sheetId="2" r:id="rId2"/></sheets></workbook>'''
    wb_rels='''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet2.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>'''
    styles='''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="10"/><name val="Arial"/></font><font><b/><color rgb="FFFFFFFF"/><sz val="10"/><name val="Arial"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF17365D"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border><left/><right/><top/><bottom/><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="2"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1"><alignment horizontal="center"/></xf></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>'''
    core='''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:title>MD LOTTO 전체 당첨이력 검증</dc:title><dc:creator>MD LOTTO</dc:creator></cp:coreProperties>'''
    app_xml='''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties"><Application>MD LOTTO</Application></Properties>'''

    s1=sheet_xml(history_rows,[10,14,9,9,9,9,9,9,9],True,f'A1:I{len(history_rows)}')
    s2=sheet_xml(audit_rows,[25,65],True,None)

    out=BytesIO()
    with ZipFile(out,'w',ZIP_DEFLATED) as z:
        z.writestr('[Content_Types].xml',content_types)
        z.writestr('_rels/.rels',root_rels)
        z.writestr('docProps/core.xml',core)
        z.writestr('docProps/app.xml',app_xml)
        z.writestr('xl/workbook.xml',workbook)
        z.writestr('xl/_rels/workbook.xml.rels',wb_rels)
        z.writestr('xl/styles.xml',styles)
        z.writestr('xl/worksheets/sheet1.xml',s1)
        z.writestr('xl/worksheets/sheet2.xml',s2)
    return out.getvalue()

def render_backtest_summary(s):
    c=st.columns(4); c[0].metric('테스트 회차',f"{int(s.get('tests',0)):,}"); c[1].metric('MD 평균 최고 적중',f"{s.get('md_best_mean',0):.2f}개"); c[2].metric('랜덤 평균 최고 적중',f"{s.get('random_div_best_mean',0):.2f}개"); c[3].metric('우위 근거','있음' if s.get('evidence_of_edge') else '없음')
    st.caption(f"승 {s.get('head_to_head_wins',0)} · 패 {s.get('losses',0)} · 무 {s.get('ties',0)} · Sign test p={s.get('sign_test_p_value',1):.4f}")
    if 'md_realized_roi' in s:
        a,b,c=st.columns(3); a.metric('총 구매비',f"₩{s.get('md_total_cost',0):,.0f}"); b.metric('과거 지급액',f"₩{s.get('md_total_payout',0):,.0f}"); c.metric('과거 ROI',pct(s.get('md_realized_roi',0),1))

@st.cache_data(ttl=1800,show_spinner=False)
def cloud_sync_tick(_bucket):
    with _SYNC_LOCK:
        try:
            d,ss=sync_history(path,verify_official_count=3); save_sqlite(d,db); save_sync_status(ss,sp); return ss
        except Exception as e:return {'ok':False,'error':str(e),'using_cached_data':path.exists()}

@st.cache_data(show_spinner=False, max_entries=10)
def cached_mobile_backtest(latest_draw, tests):
    _df=load_csv(path)
    return walk_forward(_df,start_train=300,max_tests=tests,sample_combos=1500,random_reps=50)

@st.cache_data(show_spinner=False, max_entries=6)
def cached_recommendation_diagnostics(latest_draw, tests, games, sample_combos):
    _df=load_csv(path)
    return recommendation_actual_diagnostics(
        _df,start_train=300,max_tests=tests,games=games,
        sample_combos=sample_combos,pool_size=20,max_overlap=3
    )

@st.cache_data(show_spinner=False, max_entries=8)
def cached_mobile_ml_holdout(latest_draw):
    return train_evaluate(load_csv(path))

@st.cache_data(show_spinner=False, max_entries=8)
def cached_mobile_ml_walk_forward(latest_draw, tests):
    return walk_forward_ml(load_csv(path),start_train=300,max_tests=tests)

# SAFE BOOT: render immediately from embedded/validated local history.
# External sync is manual so a slow/blocked network can never leave the app blank.
if not path.exists():
    st.error('내장 데이터 파일을 준비하지 못했습니다. 앱을 다시 배포해 주세요.')
    st.stop()
df=load_csv(path)

# v4.0 DATA RECOVERY:
# 1) On a fresh runtime, restore full 1..latest history when possible.
# 2) Then check official local_max+1 for newly published draws.
if not st.session_state.get('_full_history_checked_v54'):
    st.session_state['_full_history_checked_v54']=True
    if len(df) and int(df.draw_no.min())>1:
        try:
            with st.spinner('전체 회차 데이터를 복구·동기화하는 중입니다...'):
                df,_full_status=sync_history(path,verify_official_count=2)
                st.session_state['startup_sync_status']=_full_status
                save_sync_status(_full_status,sp)
        except Exception as _e:
            st.session_state['startup_sync_status']={'ok':False,'error':str(_e),'using_cached_data':True}

if not st.session_state.get('_official_incremental_checked_v54'):
    st.session_state['_official_incremental_checked_v54']=True
    try:
        df,_inc_status=sync_incremental_official(path,max_new=6,timeout=5)
        st.session_state['incremental_sync_status']=_inc_status
    except Exception as _e:
        st.session_state['incremental_sync_status']={'ok':False,'error':str(_e)}

df=load_csv(path)
status=dataset_status(df)
ns=number_stats(df)
latest=df.iloc[-1]

# Invalidate results that were created for a previous draw.
_current_draw=int(latest.draw_no)
_previous_basis=st.session_state.get('_analysis_basis_draw_v54')
if _previous_basis is not None and int(_previous_basis)!=_current_draw:
    for _k in ('md_games','md_recommendation_record','last_bt','corr_reg_diag'):
        st.session_state.pop(_k,None)
st.session_state['_analysis_basis_draw_v54']=_current_draw

ss=st.session_state.get('startup_sync_status') or load_sync_status(sp) or {'ok':True,'using_cached_data':True}
nums=[int(latest[f'n{i}']) for i in range(1,7)]; bonus=int(latest.bonus)

st.markdown('<div class="hero-shell"><div class="brand-row"><div class="brand-target">🎯</div><div class="brand-title">MD LOTTO 6/45 <span class="v36-badge">v5.4 FINAL VERIFIED</span></div></div><div class="brand-sub">과거 데이터·확률·조합 최적화를 연구하는 개인용 분석 도구</div></div>',unsafe_allow_html=True)
if ss.get('ok') and status.get('complete_from_draw1'):
    st.markdown(f'<div class="sync-ok"><span class="sync-icon">✅</span><span class="sync-main">전체 데이터 정상</span><span class="sync-detail">· 1회 ~ {status.get("max_draw")}회 · 연속성 확인</span></div>',unsafe_allow_html=True)
elif not status.get('complete_from_draw1'):
    st.markdown(f'<div class="sync-warn"><span class="sync-icon">⚠️</span><span class="sync-main">전체이력 복구 필요</span><span class="sync-detail">· 현재 {status.get("min_draw")}회 ~ {status.get("max_draw")}회만 보유 · 추천 잠금</span></div>',unsafe_allow_html=True)
else:
    st.markdown('<div class="sync-warn"><span class="sync-icon">⚠️</span><span class="sync-main">온라인 최신 확인 실패</span><span class="sync-detail">· 저장된 전체 검증 데이터를 사용 중입니다.</span></div>',unsafe_allow_html=True)
st.markdown(f'<div class="section-head"><div class="section-title">🏆 제 {int(latest.draw_no)}회 최신 당첨번호</div><div class="date-chip">추첨일 {latest.draw_date.strftime("%Y-%m-%d")}</div></div>',unsafe_allow_html=True)
st.markdown(balls_html(nums,bonus),unsafe_allow_html=True)
st.markdown('<div class="legend"><span><i class="dot" style="background:#f2b400"></i>1-10</span><span><i class="dot" style="background:#1687ff"></i>11-20</span><span><i class="dot" style="background:#ed3547"></i>21-30</span><span><i class="dot" style="background:#9da2aa"></i>31-40</span><span><i class="dot" style="background:#38b44b"></i>41-45</span><span><i class="dot" style="background:#ed3547"></i>보너스</span></div>',unsafe_allow_html=True)
st.markdown(f'<div class="kpi-grid"><div class="kpi"><div class="kpi-label">📊 분석 회차</div><div class="kpi-value">{len(df):,}</div><div class="kpi-sub">총 분석 데이터</div></div><div class="kpi purple"><div class="kpi-label">🗓️ 최신 회차</div><div class="kpi-value">{int(latest.draw_no)}회</div><div class="kpi-sub">가장 최근 회차</div></div><div class="kpi red"><div class="kpi-label">📅 최신 추첨일</div><div class="kpi-value redv" style="font-size:1.28rem">{latest.draw_date.strftime("%Y-%m-%d")}</div><div class="kpi-sub">자동 동기화 기준</div></div></div>',unsafe_allow_html=True)
st.markdown('<div class="menu-title">✨ 주요 분석 메뉴</div><div class="menu-grid"><div class="menu-card blue"><div class="menu-icon">🎲</div><div class="menu-name">번호 추천</div><div class="menu-desc">최적 번호 조합</div></div><div class="menu-card green"><div class="menu-icon">📊</div><div class="menu-name">FDR 분석</div><div class="menu-desc">패턴·확률 검증</div></div><div class="menu-card orange"><div class="menu-icon">🎯</div><div class="menu-name">백테스트</div><div class="menu-desc">과거 성과 검증</div></div><div class="menu-card violet"><div class="menu-icon">🧠</div><div class="menu-name">AI 진단</div><div class="menu-desc">종합 인사이트</div></div></div>',unsafe_allow_html=True)


st.markdown('### 📥 전체 당첨이력 직접 검증')
if status.get('complete_from_draw1'):
    _audit_xlsx=_history_xlsx_bytes(df,status)
    _xlsx_name=f'MD_LOTTO_1_to_{int(status["max_draw"])}_history_audit.xlsx'
    st.download_button(
        '📊 1회~최신회차 전체 데이터 Excel 다운로드',
        data=_audit_xlsx,
        file_name=_xlsx_name,
        mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        use_container_width=True
    )
    st.caption(f'Excel에 1회~{int(status["max_draw"])}회 전체 당첨번호와 별도 「데이터 검증」 시트가 포함됩니다. 총 {int(status["draws"]):,}회 · 누락 없음.')
else:
    st.warning('현재는 전체 1회~최신회차 이력이 복구되지 않아 Excel 다운로드를 잠갔습니다. 불완전 데이터를 전체 데이터처럼 보여주지 않기 위한 안전장치입니다.')
    st.caption('사이드바 → 「🔄 지금 최신 데이터 확인」 실행 후 전체이력 정상 표시가 나오면 다운로드 버튼이 활성화됩니다.')

with st.sidebar:
    st.header('데이터 관리')
    if status.get('complete_from_draw1') and ss.get('ok'):
        st.success(f"1회~{status.get('max_draw')}회 전체이력 확인")
    elif status.get('complete_from_draw1'):
        st.warning(f"저장된 1회~{status.get('max_draw')}회 사용 중 · 온라인 확인 실패")
    else:
        st.error(f"전체이력 미완료 · {status.get('min_draw')}~{status.get('max_draw')}회")
    st.caption('연속 전체이력 정상' if status.get('complete_from_draw1') else '추천 전 전체이력 복구가 필요합니다.')
    if st.button('🔄 지금 최신 데이터 확인',use_container_width=True):
        with st.spinner('전체 회차와 최신 회차를 확인하는 중입니다...'):
            try:
                _df,_st=sync_history(path,verify_official_count=2)
                st.session_state['startup_sync_status']=_st
                save_sync_status(_st,sp)
                _df,_inc=sync_incremental_official(path,max_new=6,timeout=6)
                st.session_state['incremental_sync_status']=_inc
                for _k in ('md_games','md_recommendation_record','last_bt','corr_reg_diag'):
                    st.session_state.pop(_k,None)
            except Exception as _e:
                st.session_state['startup_sync_status']={'ok':False,'error':str(_e),'using_cached_data':True}
        st.rerun()
    st.caption('동기화 실패 시 기존 검증 데이터는 보존됩니다.')
if not status['complete_from_draw1']: st.error(f"현재 데이터는 {status['min_draw']}~{status['max_draw']}회({status['draws']}회분)만 있습니다. 전체 1회~최신회차 복구 전에는 추천·시뮬레이션을 잠급니다.")

tabs=st.tabs(['🏠 대시보드','🎲 번호 추천','📊 FDR 분석','🏆 백테스트','🧠 AI 진단','🔎 오차 진단'])
with tabs[0]:
    st.subheader('데이터·무작위성 진단'); audit=randomness_audit(df); struct=structure_summary(df)
    c=st.columns(4); c[0].metric('전체 회차',f"{status['draws']:,}"); c[1].metric('연속 데이터','정상' if status['contiguous'] else '점검 필요'); c[2].metric('당첨금 데이터','있음' if status.get('has_prize_data') else '없음'); c[3].metric('균등성 검정','특이점 없음' if audit.get('p_value',0)>=.05 else '검토 필요')
    st.caption(f"번호합 평균 {struct.get('sum_mean',0):.1f} · 10~90% 범위 {struct.get('sum_q10',0):.0f}~{struct.get('sum_q90',0):.0f} · 흔한 홀수 개수 {struct.get('odd_mode','-')}개")
    _lr=latest_transition_report(df)
    if _lr.get('available'):
        st.info(f"최근 {_lr['previous_draw']}회→{_lr['current_draw']}회 변화: 직전번호 재등장 {int(_lr['current_features']['overlap_prev'])}개 · 연속수 {int(_lr['current_features']['consecutive_pairs'])}쌍 · 번호합 {int(_lr['previous_features']['sum'])}→{int(_lr['current_features']['sum'])}")
    fig=px.bar(ns,x='number',y='count_all',hover_data=['count_20','count_100','current_gap','z_score'],labels={'number':'번호','count_all':'전체 출현'}); fig.update_layout(margin=dict(l=0,r=0,t=15,b=0),height=330,paper_bgcolor='rgba(0,0,0,0)',plot_bgcolor='rgba(0,0,0,0)',font_color='#aeb8c8'); st.plotly_chart(fig,use_container_width=True)
with tabs[1]:
    _adj=next_draw_adjustment_report(df)
    if _adj.get('available'):
        _tr=_adj['transition']; _pf=_adj.get('profile',{})
        st.markdown('### 🔁 전회차 대비 변화와 다음회차 보완')
        st.caption(f"{_tr['previous_draw']}회 → {_tr['current_draw']}회 실제 당첨번호 변화 분석")
        _cols=st.columns(4)
        _cols[0].metric('직전번호 재등장',f"{int(_tr['current_features']['overlap_prev'])}개")
        _cols[1].metric('연속수 Pair',f"{int(_tr['current_features']['consecutive_pairs'])}쌍")
        _cols[2].metric('번호합',f"{int(_tr['current_features']['sum'])}")
        _cols[3].metric('홀수',f"{int(_tr['current_features']['odd'])}개")
        with st.expander('무엇이 달라졌고 다음 회차에 어떻게 반영하는지 보기'):
            for _line in _tr.get('explanations',[]): st.write('• '+_line)
            st.markdown('**다음회차 보완책**')
            for _line in _adj.get('actions',[]): st.write('→ '+_line)
            _cg=_tr.get('current_consecutive_gap',0); _ag=_tr.get('historical_consecutive_avg_gap')
            if pd.notna(_ag): st.caption(f"연속수 과거 평균 출현간격 약 {_ag:.1f}회 · 현재 연속수 미출현 간격 {_cg}회")
    subt=st.tabs(['추천 조합','번호 분석','시뮬레이션'])
    with subt[0]:
        st.info('패턴 인텔리전스 모드: 전체 과거패턴 + 최근 회차 변화 + 연속수 주기 + 유사상태 다음회차 흐름을 종합해 우선순위 5조합만 제시합니다.')
        if st.button('🎯 이번 회차 우선순위 5조합 만들기',type='primary',use_container_width=True):
            if not status.get('complete_from_draw1'):
                st.error('전체 과거회차 데이터가 아직 복구되지 않았습니다. 21개 내장 Seed만으로는 패턴이 왜곡될 수 있어 추천을 중단합니다. 사이드바의 「지금 최신 데이터 확인」으로 전체 회차를 먼저 복구해 주세요.')
            else:
                with st.spinner('과거 전체패턴과 최근 회차 변화까지 종합 분석하는 중...'):
                    st.session_state['md_games']=adaptive_priority_five(df,ns,pool_size=20,max_overlap=3)
                    st.session_state['md_recommendation_record']={
                        'target_draw':int(latest.draw_no)+1,
                        'created_from_draw':int(latest.draw_no),
                        'games':[list(map(int,c)) for c in st.session_state['md_games'].combo.tolist()],
                        'mode':'V5_4_FINAL_VERIFIED_PRIORITY5'
                    }
        games=st.session_state.get('md_games')
        _rec_basis=st.session_state.get('md_recommendation_record') or {}
        if games is not None and len(games) and int(_rec_basis.get('created_from_draw',-1))!=int(latest.draw_no):
            st.session_state.pop('md_games',None)
            st.session_state.pop('md_recommendation_record',None)
            games=None
            st.info('새 당첨회차가 반영되어 이전 추천은 자동 폐기했습니다. 이번 회차 기준으로 다시 생성해 주세요.')
        if games is not None and len(games):
            for i,row in games.iterrows():
                _scenario=str(row.get('scenario',f'{i+1}순위'))
                _reason=str(row.get('reason','전체 패턴 종합'))
                st.markdown(
                    f'<div class="game-card"><div class="game-title">{int(row.get("rank",i+1))}순위 · {_scenario} '
                    f'<span class="md-score">· 종합평가 {float(row.get("priority_score",0)):.1f}</span></div>'
                    f'{balls_html(row.combo)}'
                    f'<div class="small-note">{_reason}</div></div>',
                    unsafe_allow_html=True
                )
            st.caption(f"분석 후보 조합 수: {int(games.attrs.get('evaluated_combinations',0)):,}개 · 최종 제안은 5조합")
            st.caption('※ 순위는 과거 패턴을 참고한 프로그램 내부 우선순위이며 실제 당첨확률 순위가 아닙니다.')
        else: st.info('「이번 회차 우선순위 5조합 만들기」를 누르세요.')
    with subt[1]:
        view=ns[['number','count_all','count_20','count_50','count_100','count_300','current_gap','mean_gap','z_score']].copy(); view.columns=['번호','전체','최근20','최근50','최근100','최근300','현재 미출현','평균 간격','Z-score']; st.dataframe(view,use_container_width=True,hide_index=True); st.caption('Hot/Cold와 Gap은 과거 상태를 설명할 뿐 “나올 차례”를 의미하지 않습니다.')
    with subt[2]:
        sims=st.select_slider('가상 추첨 횟수',[10000,50000,100000,500000],value=100000)
        if st.button('🎲 시뮬레이션 실행',use_container_width=True):
            if not status.get('complete_from_draw1'):
                st.error('전체 과거회차 복구 후 실행해 주세요.')
            else:
                games=st.session_state.get('md_games'); games=games if games is not None and len(games) else adaptive_priority_five(df,ns,pool_size=20,max_overlap=3)
                with st.spinner(f'{sims:,}회 가상 추첨 중...'): r=monte_carlo(games.combo.tolist(),sims)
                c=st.columns(3); c[0].metric('가상 추첨',f"{r['simulations']:,}회"); c[1].metric('1회 이상 당첨',pct(r['any_prize_probability'],3)); c[2].metric('평균 당첨 티켓',f"{r['mean_winning_tickets']:.4f}")
                labels={'1st':'1등','2nd':'2등','3rd':'3등','4th':'4등','5th':'5등','none':'미당첨'}; st.dataframe(pd.DataFrame([{'최고 결과':labels[k],'확률':pct(v,4)} for k,v in r['best_rank_probability'].items()]),use_container_width=True,hide_index=True)
with tabs[2]:
    st.info('다중 비교 착시를 줄이기 위해 Benjamini–Hochberg FDR 보정을 사용합니다.')
    if st.button('🔬 전체 FDR 검정 실행',use_container_width=True):
        with st.spinner('검정 중...'): f=fdr_summary(df)
        c=st.columns(4); c[0].metric('Pair 검사',f"{f.get('pair_tests',0):,}"); c[1].metric('Pair 유의',f"{f.get('pair_fdr_significant',0):,}"); c[2].metric('Triple 검사',f"{f.get('triple_tests',0):,}"); c[3].metric('Triple 유의',f"{f.get('triple_fdr_significant',0):,}")
    ps=pair_stats(df,with_tests=True).head(50).copy(); ps['번호쌍']=ps.apply(lambda r:f"{int(r.a):02d}-{int(r.b):02d}",axis=1); st.dataframe(ps[['번호쌍','count','expected','lift','fdr_q_value']].rename(columns={'count':'출현','expected':'기대','lift':'배율','fdr_q_value':'FDR q'}),use_container_width=True,hide_index=True)
    ts=triple_stats(df,min_count=2,with_tests=True).head(50).copy(); ts['번호 3개']=ts.apply(lambda r:f"{int(r.a):02d}-{int(r.b):02d}-{int(r.c):02d}",axis=1); st.dataframe(ts[['번호 3개','count','expected','fdr_q_value']].rename(columns={'count':'출현','expected':'기대','fdr_q_value':'FDR q'}),use_container_width=True,hide_index=True)
with tabs[3]:
    btabs=st.tabs(['일반 백테스트','고급 검증','ROI'])
    with btabs[0]:
        tests=st.slider('최근 테스트 회차',10,150,30,10,key='bt_tests')
        if st.button('📈 백테스트 실행',use_container_width=True):
            with st.spinner('검증 중...'): st.session_state['last_bt']=cached_mobile_backtest(int(latest.draw_no),tests)
        bt=st.session_state.get('last_bt');
        if bt is not None and len(bt): render_backtest_summary(summarize_backtest(bt)); st.caption('우위 근거가 없으면 랜덤보다 낫다고 해석하지 않습니다.')
    with btabs[1]:
        mode=st.radio('검증 방식',['Nested Walk-forward','Strategy Tournament'],horizontal=True)
        if mode=='Nested Walk-forward':
            nt=st.slider('Outer 테스트 회차',5,40,12,key='nested_tests')
            if st.button('🧪 Nested 검증 실행',use_container_width=True):
                with st.spinner('검증 중...'): bt=nested_walk_forward(df,start_train=360,max_tests=nt,inner_draws=16,sample_combos=1000,random_reps=60)
                render_backtest_summary(summarize_backtest(bt)); st.dataframe(bt,use_container_width=True,hide_index=True)
        elif st.button('🏁 전략 토너먼트 실행',use_container_width=True):
            with st.spinner('전략 비교 중...'): tour=strategy_tournament(df,start_train=300,max_tests=30,sample_combos=1400)
            st.dataframe(tour,use_container_width=True,hide_index=True)
    with btabs[2]:
        if status.get('has_prize_data'):
            st.info('실제 과거 등위별 당첨금을 이용한 연구용 백테스트입니다. 미래 수익을 보장하지 않습니다.')
            if st.button('💰 ROI 백테스트 실행',use_container_width=True):
                with st.spinner('계산 중...'): bt=walk_forward(df,start_train=300,max_tests=50,sample_combos=1800,random_reps=80)
                render_backtest_summary(summarize_backtest(bt))
        else: st.warning('현재 데이터에 등위별 당첨금 필드가 없습니다.')
        probs=theoretical_single_game(); labels={'1st':'1등','2nd':'2등','3rd':'3등','4th':'4등','5th':'5등'}; st.dataframe(pd.DataFrame([{'등위':labels[k],'확률':pct(v,6),'약 1 / N':f"1 / {round(1/v):,}"} for k,v in probs.items()]),use_container_width=True,hide_index=True)
with tabs[4]:
    st.subheader('AI 진단 · 시간순 검증'); c1,c2=st.columns(2)
    if c1.button('시간순 Holdout',use_container_width=True):
        r=cached_mobile_ml_holdout(int(latest.draw_no))
        if r.get('available'): c=st.columns(3); c[0].metric('AUC',f"{r['roc_auc_out_of_sample']:.3f}"); c[1].metric('Model Log-loss',f"{r['log_loss_out_of_sample']:.4f}"); c[2].metric('기본보다 우수','예' if r['beats_constant_logloss'] else '아니오')
    if c2.button('완전 Walk-forward',use_container_width=True):
        ml_mode=st.radio('AI 검증 속도',['빠른 진단 (10회)','정밀 진단 (30회)'],horizontal=True,key='ml_speed_mobile')
        ml_tests=10 if ml_mode.startswith('빠른') else 30
        with st.spinner(f'회차별 재학습 중... ({ml_tests}회)'): r=cached_mobile_ml_walk_forward(int(latest.draw_no),ml_tests)
        if r.get('available'): rows=r.pop('rows',[]); c=st.columns(3); c[0].metric('테스트',r['tests']); c[1].metric('평균 AUC',f"{r['mean_auc']:.3f}"); c[2].metric('평균 Top6 적중',f"{r['mean_top6_hits']:.2f}개"); st.caption(f"평균 Log-loss {r['mean_log_loss']:.4f} · 기본 {r['mean_baseline_log_loss']:.4f}")
    st.markdown('---'); st.markdown('**사용 원칙**\n- AI가 기본 확률보다 실제로 좋아지는지 검증하는 연구 기능입니다.\n- 결과가 좋지 않으면 AI 예측 신호로 사용하지 않습니다.\n- MD Score는 당첨확률이 아닙니다.')

with tabs[5]:
    st.subheader('추천번호 ↔ 실제 당첨번호 · 상관/회귀 오차 진단')
    st.info('과거 각 회차 직전 데이터만으로 추천을 다시 생성한 뒤 실제 당첨번호와 비교합니다. 상관계수와 회귀계수는 원인 진단용이며 당첨확률 자체를 의미하지 않습니다.')

    dc1,dc2=st.columns(2)
    diag_tests=dc1.select_slider('진단 회차',['빠른 10회','표준 20회','정밀 30회'],value='표준 20회')
    diag_games=dc2.select_slider('회차당 추천 게임',[5,7,10],value=5)
    _dt=10 if diag_tests.startswith('빠른') else 20 if diag_tests.startswith('표준') else 30
    _samples=500 if _dt==10 else 800 if _dt==20 else 1000

    if st.button('🔎 상관·회귀 오차 진단 실행',use_container_width=True,type='primary'):
        with st.spinner(f'{_dt}개 과거 회차를 시간순으로 재생성·비교하는 중...'):
            st.session_state['corr_reg_diag']=cached_recommendation_diagnostics(int(latest.draw_no),_dt,diag_games,_samples)

    dr=st.session_state.get('corr_reg_diag')
    if dr and dr.get('available'):
        c=st.columns(4)
        _nc=dr.get('number_exposure_vs_win_corr')
        c[0].metric('진단 회차',f"{dr.get('tests',0)}회")
        c[1].metric('추천노출↔당첨 상관','-' if pd.isna(_nc) else f"{_nc:+.3f}")
        c[2].metric('평균 최고 적중',f"{dr.get('mean_best_hits',0):.2f}개")
        c[3].metric('평균 총 적중',f"{dr.get('mean_total_hits',0):.2f}개")

        if pd.notna(_nc):
            if abs(_nc)<.10:
                st.warning('추천 노출과 실제 당첨의 상관이 매우 약합니다. 현재 자료만으로 예측 우위를 주장할 근거가 부족합니다.')
            elif _nc>0:
                st.success('양(+)의 상관이 관찰됐지만, 표본 밖 Walk-forward와 랜덤 기준을 함께 통과해야 신호로 취급할 수 있습니다.')
            else:
                st.warning('음(-)의 상관이 관찰됐습니다. 현재 추천 가중치를 강화하면 안 됩니다.')

        st.markdown('#### 원인 분석 · 실제 구조와 추천 구조의 차이')
        mc=dr.get('mismatch_correlations',{})
        _names={'abs_gap_sum':'번호합 차이','abs_gap_odd':'홀짝 차이','abs_gap_low':'저·고번호 차이','abs_gap_range':'번호범위 차이','abs_gap_buckets':'구간분산 차이'}
        mdf=pd.DataFrame([{'요인':_names.get(k,k),'적중과 상관':v} for k,v in mc.items() if pd.notna(v)])
        if len(mdf):
            mdf['적중과 상관']=mdf['적중과 상관'].map(lambda x:f"{x:+.3f}")
            st.dataframe(mdf,use_container_width=True,hide_index=True)

        mr=dr.get('mismatch_regression',{})
        pr=dr.get('pre_regression',{})
        rc=st.columns(2)
        rc[0].metric('구조차이 회귀 R²','-' if not mr.get('available') else f"{mr.get('r2',0):.3f}")
        rc[1].metric('사전점수 회귀 R²','-' if not pr.get('available') else f"{pr.get('r2',0):.3f}")
        st.caption('R²가 낮으면 현재 변수들이 적중 차이를 충분히 설명하지 못한다는 뜻입니다. 높은 R²도 미래 예측력을 자동으로 의미하지 않습니다.')

        st.markdown('#### 프로그램이 제시하는 원인과 대책')
        for x in dr.get('causes',[]):
            st.markdown(f"**• {x['factor']}** · 상관 {x['correlation']:+.3f}\n\n→ {x['action']}")
        weak=dr.get('weak_signals',[])
        if weak:
            st.markdown('**가중치 점검 필요 항목**')
            for x in weak[:4]:
                st.caption(f"• {x['factor']} ({x['correlation']:+.3f}) → {x['action']}")

        st.markdown('#### 회차별 진단 원자료')
        raw=dr.get('rows')
        if raw is not None and len(raw):
            show=raw[['draw_no','best_hits','total_hits','avg_md_score','abs_gap_sum','abs_gap_odd','abs_gap_low','abs_gap_range']].copy()
            show.columns=['회차','최고 적중','총 적중','평균 MD Score','번호합 차이','홀짝 차이','저·고 차이','범위 차이']
            st.dataframe(show.sort_values('회차',ascending=False),use_container_width=True,hide_index=True)

    rec=st.session_state.get('md_recommendation_record')
    if rec:
        td=int(rec.get('target_draw',0))
        if td<=int(latest.draw_no) and td in set(df.draw_no.astype(int)):
            rr=df[df.draw_no.astype(int)==td].iloc[-1]
            win={int(rr[f'n{i}']) for i in range(1,7)}
            hs=[len(set(g)&win) for g in rec.get('games',[])]
            st.markdown('#### 이번 세션에서 저장된 추천 ↔ 실제 결과')
            st.write(f"대상 {td}회 · 최고 적중 {max(hs) if hs else 0}개 · 전체 게임 적중 합 {sum(hs)}개")
        else:
            st.caption(f"현재 세션 추천 기록: {td}회 대상 · 실제 추첨 후 이 탭에서 바로 비교할 수 있습니다.")

    st.markdown('---')
    st.caption('해석 원칙: 상관관계는 인과관계가 아닙니다. 회귀분석은 과거 오차를 설명하는 도구이며, 가중치 변경은 반드시 Nested Walk-forward와 랜덤 기준 비교를 통과한 경우에만 적용합니다.')


st.caption('MD LOTTO 6/45 · v5.4 Final Verified · 모든 특정 6개 조합의 1등 확률은 동일합니다.')
