# MD LOTTO v5.6 FINAL BUGFIX VERIFIED
# Upload only this file and requirements.txt to GitHub/Streamlit Community Cloud.
import base64 as _b64, zlib as _zlib, json as _json, tempfile as _tempfile, sys as _sys
from pathlib import Path as _Path
_EMBEDDED = 'eNrNvWuX48aRIPpX4J4jg6gCUXy2utmNvitL7bHu1cPbknc0l83DgyLBKqhIkALIenRN7ZFmen20Y81anrV25NmWj2ZXs57x8Z6jsWTLPqP94p+yH7uq/8ONRz4BkFUtyfesH10EkBmZGRkZGREZEXl6bTYeTufL5XxnOEzSZDkcBouTaz3n2nB4GGd5Mk+HQyd03HbQCBru/fSa7+gqu9HoYBnnS1Flks1nznA4WS1XWQzVktlini2dKE3ny2gJoPL7qXiXRel4PlOP6Wq2OHGi3EkXvrOAb/AT/rcY308JaD5KFidBDlByCXU3SeczbFwUsb8CwN04G9I7WWC+WCaz5EGcyULyxXAvmsWqWJ7MVlPqriw3mkZ5nkxOZInlKk3SPfkVnuLhUZzs7S9z3/mzuy/+6fdeH7704nfuPXfvz++n+N9xPHFm0XK0PxzNV+myNprPduf+UZIiGK+XxYCv1JnGaS2PxVfv2/hTFvEklGEOPYuHs3iZJaO8Rk/+Msr24qW/O09XefjKPI39bH5EP7ze/dSB/+wnyzzsW10QtTxnMs+ckZOkDgEbcIX5ahmeuruAXbc3i45rCMDz3fZiusrdXr6a1fbvhG2qu491xfeO9b1T+r4EOpiK7/jmjFtLJg513kmAAOZLB7sueo7/AVo5gO7LWVB95xGXRnALe993F5maWXcQYpPZt0I3BdAu1ciwBoH2dFPQE8Cd2Q+g3rETTae1iYB4mpy5VHV+FCQwKccELRHQ9uJa07/ueUb38T8zwGYTkdn03VY6dnstQGYGf9uAtOW+2+v4bhf/ds9uAf2fIP5hvdlA7F4XWpC9x+8z6vRiHMAg0qiGPQV06RHM+tngzIVOiqa2w8l0Hi2xYL9QaODZzTBqqRZglX8IhI/mOb5rNhqNLaJlnA1PfMzmCXyrcYW6Ud7bMR64LbEe4L0ie2YXTP21LN3zaV59IM3hHNjUNFpY9D7an+dxGvaBFqLlMp4tgPwFMo/2k2lMa40LebcJFE+zKHu7BWNoGAgehcvVYhrXcljv8Rg7EOTRDN/IKe9c93DaPd3gdti06IoolNvsjebpMklXsVXAGEyZANOTmuIPzBuOPe+OWQWp41i34VU0wl+CaLGI0zHAsdDNHyXGj6LpwRBAHkXZuDae+MBIs+VwmUVJGrYbDcY/zDV8iBdhk2YCmTG+g5dxPA6vd7o+Y2lILC0Pu4BVX0xlFi+4rDmHbV/wUWs2gSxzmktYbskImp0m+VJg3uiXjwgaTzzqkuf166pPPUFYtFDHhCQByphjHtt4EiTT+ajfg3LQIjJS+YrfMOsJT5NUrpcUOcLAK7OBZz1YzMyVRemAOdYtJ81Dc4eqUePGUpuNQ3tz4hJ+mgvMM/3b6LWeeA7wn23ouIVl47fCt/hrs0JE6GwsVkgFPc1mYWFDmo0Daj5YzmmSPItV474Eg4flEzIVBPfoTw27uYWMo9HA3mKZXZrxbHcMf3WLiOOhxrFBS0WOm+1KOi90cR0vIYord9crgh0/JVwD25vBz+IoDafRbHccOQfxiR9lWY/5croI8GOtf0x8HD/CqzRKPb3qofTAhLaIs1EMEzaNwyKQPm/sg9vhbCZ/a0AwQgtQFo9g8xpn0dEwnbs9ScniBWzqIA0KQUFBo5ckLIgNmL6x9MAfO8WPHfGxsKthWZIahiS9yNIsSDAoc6OHj4Qia/f3G14JrJgs7O4Q0QI1ETncfz/bhXGJIuPkcH2x8VrIWI0xYNZjFHBFs2SnVLJjlNzQhMCNUZFRU27CwIhV3sJUZXNigoeapIaH+VCDdnv6i2oS16TbMx7OLNZCAgHJKrPiwo1HwWoxxkV0StPLwgZNuxQ8aN5JZKDXLDzQSwRL70jg8MsyUhUSGayNFW6pjEaAaxXEdqjUmblmYMeSbALGY2+0IJe9EC2j72aAclxKuZLuQUidRTQdUrGq7S4lYxP8GF6EYUPqDKcubXBuryHQCxoD7zZQMBATdwd+VhGzF6BUjDLLdJ7ncane7UvrLRPcjblXdWy6zpC4L+N4lOTJYRzil23+AtJtqDQ31G9yXxbzg64XLA6j6SrGwcrXTjzNY6cZNG7Bq+kyykPuocUV6nZX9aow1RmBKtFfxbjEdDKX1KNnbumtZQSqfNVnVdkgQM0ThRqE6Ob2DFYpcOuX+Uh8vIhHIH5WN615jYRQaLpT3XRnc9OdKzTd2dw0vDcna0iziByElhOBkXB5gjXmqa7NdsqV9JSt5VCV07EfR0hFQ/qLlOj2iB5dplQgFPoLWmuCT/iv7+bJXkpC5XAxJFKVvVjYwOPDZByno3g4nwzj8R4U253Pp7XF7aDRJYkem7rDLdg1Qe6H0u7d48V0nkXLeXYSOM85KCaCQJWMQBU9cbAXyQQe0iWo1jkUwg/AYPLVdCmVh0U2n08c+B/bY+A5Bpl3iUtqMT+Ks8DV6rfBaJEpA0pH8+lqlpoCMny0GDPPKXNhcybwjSIlVU6ycbMkv6sgmsLuk8XRFLii4O4MoQJEvdT+TrlHa1oxyFkSe7nL1VvGV4CsN5Eq2PKrpNozb51enAIhAriNytp1Q1nTWlqr4ydpCvoHynHw7UZBl2i2CqraDUOrs1Q2uT/dv4b/fXW1jDNnlS7nK+DLY4dau+XE0WgfOw7fsEEnj6eAidwRaoezytGgNk+BtuMomyZoo8PukR5aF0OjqnnADX0l1fDptUJeXSdFvRBtfuPQtPzVREkLrcbvK+tt60WWtf+5kqpniCeg6YQL1NTSERBfX/ZcjpE03cHAByYzz+IhGbnC17NVbIDYXYYW1aHV0SQ7RLiA61lDNwwFXxENJlUav59S4aUZ7Lvi0bJzaUmrLJqi8EFIagxAxx0iQ62huhqP+i4TNa5HAgoS93wCW5E7kI2lgAF3IEozbbBMokpYL299ZTkS5mAZ750A64WC8Bl2+002HD0n7UaRD1xvrFv4FntoN2w+8BrApsXPi9Z3cnqRjA7ipUMmaB83pDpIedMINibZZ9hkA+eVuRoC0nbuLPdjYXghcBYL0BXDUz1d7ssvOLvRNIItGKQW2ygPWqr8MvAd97VlthrhDlkHSeDwpFw6lwUshcJ9hQw4ddyLo+nauvSV2nke5mhcj/BUJS4XHOHXofhqtfP9KIFWltFuMk2WJ+saWkApNCbtIsGJjT3a2wtPD3paSfBJcR3ChkUPBcW6oQz8DWXKb5wRfzwg87rCtIbfd59Hgoj24jpyb6Dkr9eaAfiFhA6gJglQh5D41kIPKuAHRguB0UYgW/lj7RmVlkTTbmhaFC81IF5mKsRab/o1XOb+kYfVYygf41TVjEWVLONZXisdTJC16pu1NW61m9tvXm5wLBjWBNPlQ4NvhetMjnyYUnUMVm14RIN8iOSE+MHjgL4goMF22KRHRUXwRhmwuKBFUPxZGJ7ou7Bn0Xvxm953jPfitx7AnzjWgumBqG6K8PkIfoAopM4TJ6vp1Ol060wDILnPp7eAgTIIZ777Zswi/TiDf3MhWCXzNDDM/vPDK80wwh7mUCgsWe43TXenfelknyoeisonrEVJ0cwd8Y3iX8Tl6BWxRGQK5b0ZhuSFgkguIQ4oeglpFFnY/wFUUm0iJ3TfvNlEgWOWX9kwjoW/vtHatAkLvFVx6MuQVzBG2wboGY1glg/oIK0Ct+XaAtWV1RXqy9XEp8pqnfXVOtXVLGVE7xDEkyOyzu/tSQ5sbhS4WGoaXz7NrCHz0bohOcjtETC5+xl12EjCFngL1ztLv2R8iUVdG69Y0rLWR4axvlP4IFBwdpkwGuBhKdtI8lrf6GVlrwZ+lI9gyMD7wu9G0zz2gizO4yVrH7VxNl9IFcTyQBlDo0/vffJmPk99BzgZdB9E07eA5cRt38GDW5TY4Vcyi4W3xyJa7k+TXQnu+/Co4NieKtK1JX5rhXMj6svHIBpHC1CAlYvK915//fvP8TtRdJVNoaV2sFomUxj+MjuRZe/hA4r333nutbvD51996Qcvv/KaEzp9dTDj8y80z8DvtIn/tPCfNv7TwX+6+M91+IeOn5DdfP/ei/+vBa7SmUGfDVlOELA3uUeksOT07AHAu2+8fu85q388zXk0jfNhNEPBHzoQrUB3EnXhMY9nybDwbhalK6goXwBsDdVEwv301e9+98XnX3zupeH//dqrrwx/cO8lLFJj6nT3l8tF3tvZOTo6Csb7SDNxdgL7QXCQ7UyXoNPs8I75/Xz5Ej6+mE7mwXj+f+XZaP+l5d1FPg5PBYphxF8D6Cvx0Sa4QNcvv3jv3qv3hs+99BIOAn2uZDv5bH5wsxvsJcv91W6QzHeY9tncl+9E02mAFO0qGC899/rd115/SjC4BeRLCUlh9d7d137wUgnWbM3AGZir/Z6GeZyjF1nNc+p39GJ4jd8KZgiKfOFDTbOX7CQk8q8RKYHeCQINEMVoiT+zOBrjXzwwmU8mw0k0AlEqDJ6tMCCg/AysDKh5FKMkENY6rZt+FxTcbqMF/2/D/zuej94+8yNQ42GT3J+P8xDW5oM4RZ+Lvvund193FcPPAyLomsIKrAljVddwF8UBoG5KA8ENxqp0pTqyMTRUw1rQRtgf5KB/PrcH6r3bc1+eP0im02inGzSc2ssv1F/CyXUO22gVjiMgu1t4JgyTC1LmCviru9bE4j43GsULhAnb0BTEUmSeO8Qzl/HxcmcxReFxa2fLLWwCuZ524PsJ9XI86Vmbg080kGQoTIJwv7ear/Keg8ZxwfeRTMwKgkRmSY42wrA/0v5eFjMkFxu0e8MHULCE/XqgTNwCAEhDUZLHzr/Djeluls0zYGov8zdHGr2dU1EauBoDOIjjRWi2t212xOKj2zYTlK4/pT7hodR40kfIA/i0OJE0r8Ca3P1KHN221vdHAzTzAVslhTAZ1filH+Ow89AlTLheEOXLk0VcA9W02IMNA+uVvZvQEq9QeJUOjOZ4YCNxTI5geheTdfEB9+Na8fsaMNCbYskgydOoBgNNAckVFOC+mBLBOqqOM46XfORVBRVmZBCMV7w44vEmyC/IUo6oWYIsbAl+JlEIwkiGIpQlKwIGQbgk74vNJgOQwPM0FJ5qWKusPSEry1MP1OzrDoqpsGjQw7F5Ozy+Dbqf3u+hUNEEWl48EnfCWVW43oJUxMY6h12llMPIGawu7JZaWgoHflqwXqQgEBMhBdESjSW+HHiYGpZo7WAl3Kus8eLgYGD0hQYHLQlnUxxfb9OIuNy6cRhkG9IZlCHvKjJZL8ZKh80SN6TjQZwmAGqiX54emfYq7BK2LZoLZgkdc5Zeg5rhedtNz8aNWUQqx98KZTtFxZo5ojjZEPSFlCTLe3V8MmCWfKfWM15CsCAczX25rX6v3RgobNuHYLzZoBKASOYNvrTl0JaClnoxonFo7E4eWlMk6mluLHeL8VVmYFyF/3EF9q22xiXchwr31ljZ+yrnU3vuFEgpLrRFCOL3xT7oAbADBfmF2/PhoqxRCYE6XAnBcfUIxJm2flE8A4WyaDZaxkNUb6ippqgkACOpV/U+DJv0bQNsFleZwfdATZYw8AWPIKApvhoq9qNceEghMYGiC/yQt225o63ZFNGHXcm642SvNt990z+IT3LDbycBYgbaTEcxfUVSNMmKDOz+IbH/3Tcr7AQCDBnhEbT0/jks+IeH1IFDbr5UfWK51wsQEy4G8nCpm0iTxW7KTva+sZbFE34xELmIshx9JybJKAEtEGVP9B2fzqNxD9HnS00CxHScdSTgv0AY7Dhcv2Mud/jO/RMQ/FN3SioYKc1Hr0jlmX5kIJzjB9KNqJAUcpGaynDuTaZ/PlOQXmD1G6GJnwRH/I4BnCgvgfLuVYC6C++oM/SVfk2X37FeKgAsF5jHErY4YMzUYaGdCfZ5+cqclPkJ91Q/Lf8sSdXTkfxdsMUeWjNLnZG2K1zWh55ncVMSR0DqMDqVx2+VkIodAWWSOgADpsZfSsh0JIQMPnvLJX5fmeNPsX8U+2iQNTTmA6vweoY4dWzYN7I4mMBOjYs/c+/fH2+7PlQhBgIyBJdGIWLQ7103jK/F1YPN8OpZ0w4UMECgsxvuf4BKRiNRrE3glSVRliFh1XhWgTTyxRq8lyXVH6T5arGgfd2RK89BmwpqkIs5KMBOvh8tlJxNQyvLmdampVyG8cEzbVTMsvGwp99rNgb+1tapkO56abU4iG2AQHgmVwA7sZHEZ/DgSYw+ZopzYIM10ROs4KMmAcID/g6bLZtTCH0C/UlgTSrDxS2te/fde/EkzuIMZNArmIGUNUQuTrQwTmnGUqdst7LOEE+KkneYk2uzBBEAvFm0lIMLlUO2GGEo/qJJOaDZRsuHlJGKohlPWiXfzcgkVPN82YIpEKGhwLlLfzBgLsodoF/Go2QEE/dU9hll/1iLckSC91Yp9lQQ4auS8IjOaTKdSZRMQRx13G3X+QvHDd6cg4zAbXBknNg0Zgm+G4LqVDumXcKeXZNekXSE9zxR2XFfcY+BtuYX/d6PDfWvTMz4lbRNQdEGhr8icaOnPj5xg+LUepwcJkiXecjRAK564Xq43tfuBdc9W2VPbpOXjqpeUvXMaDDSulTRflJvDgxHe5fPLfq2Qbi6grTo6p2hykZMk9IjoFWfB3LwFd8E4KORLCP7hKeASUrWLEbV6Zma6r5tkx6ERyOujK/l8CoM1bqg+qZKF03Yqih/KGg0UIVpWWk1SU7nvHo5sshbK7EwKfxYHjjfgaL1eDLB4wOuyGtKgj1x6MwBXWsUtxcOpItoL7Z8bGxulBm8kQZUYSt+ai50hQ25BjvyadPvwv5+P9968vfvuX4WoEXSM09OGZuoANCmRDYA+KFFf8HrC6yrVwIhRVK9qwgGUzUNXZvXlFBUMsxfEUG3FGs2uJvkyF5x2xNlEF1m79oN6F2FTXVdL8URxJW7KES3UPbLomula1tHhH2LWxszLmABfy1bRqTpRIeFzo/YhwCP/GoZjJLiNHtWB9ALBht/HUYBfZ4tpBGHpA+pJPreNsd4XsHE5m3XTHuTb3Qpi9GrEvarWnyM/trpXs+yfmfxbL6MrXfQa2PxCpMVcmYJwZNGOnzJAGTQuKBlbdBQdQJtddLGKJhAXVRAWlMQmOVsnoYxxzjDv3h0ya4lMHB6KVUYmPl+cUPl6jiawiTFAXo+pQMQR4vTJ79osRhAVxroEHdOPl9loxjtUnSI7MxT05GGTCYgbgCIfq9lGJBw56PJ44GxreM2voqtV1XG3HuEMtkyCNnzKUiFwEOj1IHOQ7PC5xWX7YSdmsfzo3QvA+kxcA06AQacTE6GSxBtYINYaokVrVcWxZCzJC/jgl5bNGPtx6ODeBw2bpHEBChlUVZJtYZjAls2lP0JitfQ8MKOmcLE5Cm71Ea5FDoeVgndTBGeiKHtq9bCkL8MpB9tyVxQpIv5UZlYAEWvxXhIVoNWcbLkkE31My1aIAWKrNDsq8qwaUF4lWqOGrUA7vbED19/kjSKLhSyo0ULlCpMpJEgIDavMTQyhyETkPU9Az531u3x336vPTCtUtFyPktGw6MsWQI3zQ9LJIYuDj10bLBZEb4OQCOI02UwOxgnwEXpgfmwT6xmOD8wDdqTsb+cLULpSAHVcvxdW8BySI5Dgohvtt0hqNarCb50A6ji+gA/JE6tW0XqmefBaDrP49pk7FUJI+YawNMiHB/A89lrnY4Uffw+ZHUpdJ/58/ozs/ozY5eBZzFoJqCzYx1sWg4EBMXp9MSWmKE49Y5GnmMVPJ7Ig1U6TdIDetZoz6PDDdiGkf6FifGqSfKxAOFDJwDBvZE+F6FY23vF1osH5aqiV+wnu8BcrauCOELdO5AArkwnwJximIZoPB4C60wO4/EQXyBF4xSKKQYaWgTEF5lIakQkwXjX4OL4QswETAM+iXmQCgBUl749gXAZoDnCFY7Ppm0TuoDUA8VrwtruYxE/mQy5jdAVlOKapOWZXpZpCv2JRytApPv8vbsg6jk/eOXFf/uDu86Lr7xw9w085BvKQ8BXX+EdSqrvnjpNKpBkaaZO0pEUvfgPG0T/KFO1Zh5cPU0BEyxK4TUU/oLxaraQPfPjNEdfrCgfJYlYi4g82MtaPowoAmUD17wHBUdz8v1yV8tJ/UbV2jQQQYvARERx8MYuaQ7ekrBM4pHM/ExzGPGKxoTtQSO8hmiopf56a7QKA7KaRuy4kBPsnvtCUbOt2b4UFvROY4kEJLb2rXWL4x9Y2uC9eAIrbJ/diUXjQFCTeHoS3Bdi5GE3uE4CLGmH0/leMhIw6s7roCYuVrvTZOTsrqYHDkvvzggFn2jP2Y33YWJJmUzjI9Q1SRyanjhyN5PBWwLeK/EhxoJJ2ciJqF4mpCgUSJw3VwBmNx5FK5DCEDK36eaO4amEQhgQAWw1EvK9eHeVTLkvhjy4Ox8bGq8xBjxKwBZog0aBTXdBLm48jIcdIcuXPp9KwchsxRlkhMUcJoRD2FDE2ovTVZICeuXBqYUAU7m2lydFIIAUZyosQQpK0vJB6D6XJ9HOa6CLKeOBlPdDvTGQyqupmxVfS/kSJ1qWP0vl5lqW9sSp2yxeRmGVUuwVD42NjyT4GQBMa9p6eay3CaLU0Q1h1DSVhGttKEaDNN9mFyVO15yHarWsYFJg6xw3CDMonCnZcdLqtl/ojW92gdo5Ns9VBiWHBt1KpXuGbVJ9HshlbFUz7UGslJS7P4RBk3uyfmXgTESz2MUJQQxZnj8QhlCz0FPv+XYtq33WScOSNcMrFeE/ff4jZ+p2yB2z/amMWgXld6ONQUds3CMGEU2R/58oqWosOAWta2BUJ3PBAU0GuRsDDcQmMJEfijxl4uXRPDsgfpIHwGMTOrmJ8xyD2AH00X6cGqwPWW1uBnasMty8aapIp7WQUSBboe7zlDRKPkGaqonDacjObTHbRU5ANItsMpR1+6Wlc8cA5H279FnOl1eeMKNruiWvIumZCqomzhkaDW43y6WNXuufa1x3yrU1mQyptglDYt1wplMK9IZeCzjaocQej0/Giopmqlx6TH+8Yk9Du8VetfOnWCZGcLBYKLoHm+OCK4Bdfc1VAbkSjdvL9bsxm4Ng7+W1CTQHG7bch6MJhqGLFbXNFFEniUPKPoHt2nj5WrAiP0x/CSnuK/OhRZ4isgYmsWI6zDiQDYeaXnnNYM0qgOvmthy7cfkcfw1+alg4JU9CE2vF3JIr0LfC5rrvNPffCiunZG8OSE7ScC3cSr5ob+YKzlPz1zKckjGxPEETaV+U8nmSSgeqntMMglMe6JliHr7jVkGBLjunYvxnUE0M4axQuLDxFu3WwlTtlYWrcL3xUpABKShhpdpS8EAU3/qVtrLB5c6n6ryY9Qz2VVc24Z5zqlq4f62iifvX2DBs+KNIs41cHEaHWds0w8zZcnfg9kh9dlG1Aw4bLflEWMjyJdc1th+7PVdIOKSUbRt7EzyYnSVfyN0swTwyJTc4qsRiBqas0YLkGoc5HpfbE6noii6Bppzq9myxdZ3FUrriKbnO7RUlXLvq1lbBZVPQmr+1JSvqCmelkzkxNVy3WvEmK+5xb72YU4yDrpxaNb1su1g7vy4ZXvllfFyVCsalw4DhKMKsKMLHkGimhArVQxvIWaXDRvncx8KKWjTS9rDG7FY8j6o4KyTVGT3Tl/P5VMWwGUfqufaGts8lsB37+GH4Dfq670ULKLtbj+h75O9iiQfJgj0q8J9+szcwT4h3V5iEAiph3p4pyKDp7XA/0ecifGyMj9O5v08t9qG1ZsPza82m38K/rabfxr/tpt/Bvx342/UGpk8YxTJCK+kzzYYNHN2LALGUk7hpdtvEZk0A8Fu0w0RhuGsG4I7Id+M02s1rUX3XWwuFsNDyzrx617Z2mjGmmEIBO0Mj9935eMy8Wrx9plVADtD7YZwWyoRho1hsbYDRdH5k1b4dtspt7Cd7+1apO2GrXSpFxMBJqulNHXf3S5ofoTPbaIVx80OMOxcpq4GI0O94Ix2R4zWGrwLdcS0kQG+nu7419LKm0thHKg2MBOZ/yDOsekDxvdFIphWLRmtBkjsRk/HwNNlunrm9Q+FWdGi7FQla987K4bpSCMRVWB2jYAuGRDQgGUbAacKmV7BngqgCXBkkW2D5ShooGDcREWl8xIZLjrGVHgrdq9oxTa8Wo02HY+IqXFqkZU5ZOZ/H87RcbLYshmON1JHJJnKRI5pjQKDDQosgFitUg+fSE6m976zS6BD2bMy8Uk/j42Wd3GwA2jjhJPJoyUnrExjV9BLznzjYnZjWPHHITht8KLKHrHHUn9jaPTD7WKfPpS0q1IJpIWOAmByLDR8vqxvcbpaabG50XZwfVR4RQwMlH5PC4XJq6Bi2AwkAHVQoPxT6ksYqSZNUk74VQmsVWtFuFkcH9mvAv7E+xhMfbXCXakRQy9z37I80FZLjQkcu9aG0q/PckXRRAGx0P5lwM70KYRYGsbA5ALwx0yVpGdYWKPmvfEuqs3DovZwKzSRG1LOhiGOhB981eYYQoOgPVzsrRPrPpk8f529cKyEvkjiYxlGWBotkEU+TNJa1Z9EB7AXiZbFsFi+y+Shm84Go8NoSY/+z8WuAFxXAL2sgkCgbzubjeCorvDTfowSO9+K9jJ2uCpVETg5ZfjrfG2J+SB+Wz2gYrUZDzA0TX+G2i/vpd+8+9/oP7t19Ley7D7ia67vS9IB7ka83MfiAe+yw1VA/u/pns9HA2HvhSSBFxiH6HU8kryhmKMKTeMuixl+lQe2NMM37soe24e+Nvu7XIHwjkA/BJJlO06j2bNC1qfgNEVwKIChZhzonpzMg2FrTeFpMfdbsNnxYhsNkfMzna2JULJxbmedlMUnXQOLiVdnCLT6otFFysOiCc0L/0npJxoVwDc4iVU4/JeAVnHatvpauCRDArELFUB08fbcKUBoqM5ghr6xTmHwjuVVFwM+6XlYw4HJfqHuls4anzZylAbyhzWiRyXlPTsJ0ETyIs3le63T9Mdpt8Q00dMMq1oeXuOpQWakJvZlLo5W33hyY/kQnsrWTEwOInPsABAT8SCPY6nTtM+k3yl6o0DQeF5zUag0iLblwPBBF4VuUZdFJrT+wH6w1Ah8OgbBGB7U3qBRvbHGKG9UJ18u5puykvm6GOJjSzZRvrcErazYjrHl+mdGRcIHIwxsg/OfDoOvn8+khPLvT3cle7mr/FqL9YYycgzfS0tKlXGz4pINRESpZICZZRB6KYdDqyk6v8ljlYqvXyrW3jQa83mCNLGzsbnc2w2COAC1uCvzNlyHyDHO94y7a5TnG9Aw7O23JQ5gvSeeEN/wTX3ESk81BLUBWgZvRv4UgLHSUSd5a4ex7t1sqRki9VmQAX41M40rKFeYQ0R+uFFZUv+WAjhXy2z4Or+nLCFZ+6W3VmnVr4oCqYTnJo2hKoyeg3Q5HeNMMn+qKd3dGK8EniE5DSa6wXSxrb/QJwMA/ET88KW/jGpiCZkelA5EWGbN17kZYC1rAEA6/OfCbcf1Zv1nHP8rZNaexgkgAeK5d3wHGgQNayMmaTkXaKLl/104YJAhggJHd9d8RtFf0LjSQzuIZLxA0mbAcRs8q3TJb+PTHeF3iY1cKFZjFeD4ZcoI3mY/YkjjMAZStjzyIIpjp1HdxPMghhrIQSJPwvgyBAKis4LIaAqnvEiDUPPFIAcPrlkNRQwYST29DIY4AK15cM5xNq/KeWulO1UI+gpUKekqn2/iK9858teTC4tgSl0fDh5L1QofqJnuyqyq2puHgfrzdHGzkPcYxKC4mmakXFl7xu+haBaPCi3s0jJ2dlqmJ2fxK8awiv8JGfaMhJZRpwBuYWSVDGyuuVXFZTQWL8M0t+rgg42D/hJSjezTwqgUTXdgoe2UJ5WS5QRIB8XH5VBLIZg4Hyuc65raOwSkxpXguWYiPq0SCvilmjTnL1fyhyBmXFTxH16tgMGUAzFXXwgAut4bpbW57OV9cH+IddjxyniGYF9R7YDPo16/3BgPBes9sIY+OZ9fuqr6R4JYZeV+m84WtQwt5WV/jbWBcDQdVBrTP2GXLuCpVunTn0ddn0CGx0CFLyJ9W3bagboJYO2m7m+tV7A/iIgDaJrx1lXnzUK0amTR46/DW7I/UqEEdKgtk1ieiKaGvGoJBJ2U4+uPl0JgW8N+iYURda/lVb+FEyywmNbzKEU9l4kNhkRCpa8v1eEn5rDiIYuQiAMpQpT1DJoNdGhnFRtAkWdeGmKe2ZlocfEpa22qsMUisS651md1D/m6jDaSY7kpkGsNMV2mOia4aMqgZRhzWUmhV21t28LnKmMFsGtPNZWHTk5soepxxzja66lFejUCJ0WF6ZiAaI1U7EezT8A1g4kwAdsm9RViDnPvXxrD/XQskTvp4VnIgc+4OwlodOiXMQwEeJHl4CcVBbTFasriwFbS7zraDQ5E4KZVodtcm6jdqtqtqNpw6YwtW4G6t6a3pQ2tTC9A+6hA11VK32FAdsUyQt1oF6RoqpVPcS0GqQwryLQR5AeNxjUOXUpE1XXJ25BqSp50+2c/0gTMnMcQFR1mJSRvCGnh9pA5twEK37azLykudemAd8omgdglG6phxnIaYkskr3nyJX7zbBej4MojG49q6qy5pXHjHpY1F6g5BNNaqSKhsJGHGRhQOsgQA5ty5W85bq2isHug0zOy2WrCio4acg0VlNsQqhIw8v0XXVHF7lxRte7IvlxTslLQ0Fj/lSR5NKf6ELVJ8ET3gb+JBf6VG+Rv9NPNZFBJ3y7s6VOruZsPI290qXt/QxisV193fUHXXJp9M/WkGNU44Obyj9xd5hIbBAOQOj8rJXuy8/ALlLY/5YlrNqcV9D7kzjvMRDBoPXJGNYf0cHY7w2gcAIHT46JjaQU6W7WH8lZHnfOK062Ti7MhM6MA0gEpyH+kaGGWC7FA43QuzCVYGjliH1mFJG7nSgevsy7DNWQz9lneoTqED5J9aPqarzsiNBIupK4ubU+6j1qQmBiVoRdt6c1OzSU5UrJKKJJhCtZFXqNwJu42iZ5lqMw+vzIREzSW6dpf3YpO6mIAFJ8HJHYf90pZeG/kASxKScROz7tvABEHHAnh/pbzn8rh33McbnviMYuBnMV2AYaqrf+L8P3EMG5yzm82jMbDGBdAlKNLwC28QOYQtlqFT9nadAJ/PgmEJwVbJuT2ZlsTc5vvQFcoCy13r93DGiDvSs0d6Ll4EzAttq9VteNKNxLhfGDlfWzIvfOiYDy35kMUzVutD1bAlljBzVqVUDkDrkmKD91Ga74SW7i1+APIOQZlr3hDPFKJh+yGyiwBdcG06CahWi05R8tpjymZBVOSibjFi/jwq2/3lNcWj3Pm2Q5cU63qX3Fa8xtm6dPnDglFqseYRs/lFu+oTsfVFp+pTp3h+nMZHLTKILFp1mj68qjc+avO7Nr1r87sOv+vQu04Bjr7kwQFOgS3izYeKTRKh0slt7uBBYR3vlgsKJ98wnZ2gsYVNgaDTDLr4s40yT4t+tvBno72lr+42FlJ5agDeHUknVcfgkoTg/7ckdSUmKdWwTR/7gP90bDMMV9AZrAqn6hQCjlclKVILFvNFjWtRWsRKSjO2+j/WrNMsy/1+0RLLtq3etOWqVm86ti2k7wI2xM4/8NULueEbr3iXH4QKpQU4SmhSGxUUpnR0NTk7fovi/M1bvDE6Xnve2WFevLQs4z+6WJSYCWdYXWJ6q6Mow+mBlifuq0imp7LWGW7Cp1T1zOE703O8k5CC+8g4i9ZB0LZc1R0JVI4MoJYkw75mEUWmMKBtkH/z5idtigZs3OgwVTD8WXdLHibczWAV0qkUauRXlaVMcam7QVx6wWzAiY/3o1VOgga0VUeZiDCkiVC7KWlRCRs2BCyOBIqk/rdjbGurlH74nLcXhNsV3u043xVXpzhAK8kML46scja6qrAiMwB8owLLU4odhoBzZZ3njyipsIcBbGn3r0lGe//awLv0wj5RjRLs3L+mL8K5f81veE9b3bo45ytBsC/aYRBVMCpEMSX2aM1MCBOMNIOlmAz9/jVa4IisSuGhWnAwaj2V6FAWGzKx9/Dl8wAYFxXADQ0By4wVKzDYituHuM6dyguIjK3vyhzZDLmdL8QBITI5SWjCxwr2YzT5zSpLUFQL7FaLKKXjJGQ+XBxN/Tc9Ozf8/WuT+WiV8xkRIqNmgRM1vR0Et9VsNLyAt6KmV2TBQFLIfK+ZTNj8Kg/zx0PLlCjxr9ZfBWA8v8CC96/ZPFyzWGTnzYZS0gzeb9lIBcd5CgvpUxhDDS8zv2AZVQYRut0vS/IDNoV46uILaVagt0CeUCRsBNKYCE/Odujw6aBwlW43tRN07tU73lYjaDVkcsDJpNodPvctR3gjEzzVoZTLPWpwG9p/tmt3AJseS+foMWUPolrQdLOhfKWqHN7R211CqV2vy0ZFaWA9AKLxrPZgnMKG9EzXcianK6xEx7q2JwrQfDNo+PjVMD9daZOx9vEcIw5Eib48tquMOOBDHeUEbZwD8ppESPIsAhbj2HydL8foKAlQm3KG8bwzzc0cXLaznOD39pGqwozsV8fK7fggRHsntwvwOa2WrzwB6ZqrvUiyGaOE6SGIvHq2FxpftWcefeHasz1ONzAOYO2kET2j7jrbuyP2/2eDrhVBxfsOnk7Fx4taPWh3tx5wh4biWk79rbtVQ4/5HYBab3pbWy2+ahUTiMipLw9C+y16O3hQvYVnmFvN4Dr7qBoF6FQeasoM39Rfs7sm9vvpIAwAkBrCNnbd6PY2rMIt7p2WnoD/zA9Wi/BUZIyLODl8Fux6njx3lEZ4zwyOYeOmDo85IzTjy5LXn7Y32lKyMk8C8Q2ZSFXYF73Lx24vH6vb+GiYbs98Evfy8SDcnvFgJjRRIo2UtZCZobzlVaRelZxOrBoo1Tc7OKBFo95CF025DG82U+TRIPpQgSt1EUu+k4+JVMR2Mh6H1VEstwRILHHa7jX9Vi+42fI79G+zF1zv+l36t9GDmfav479nfSgtOjQFpXZd9IqEjWWuDhtKC9gyRomCfGopEP/OTjGM6Ey1wqV5Sfii6o7UU/MF3ZFUESAjq4sSBbTSy3q75e3cNNApk7cT5QbtzpaaFiJ/hdHtoHl9S+FgG89pzL4aL7ghg3tbIm6ZouwuqONUohiLkAewYq2EhLvzgXY0ZDG4mlzFmiWQJv0P7BSN9FKe5Eu28SDsI/flj5yw2TxPOQZZGwRuQ4i1jBPUk5bcpCtHqhlnY0sd8T/gYxl9/lJSf+QYK9VYdSmruI4dc+NaV3YGnfKlnTDf5Ws7g2ZLXdwZtG6cqTuaBahwA7MAeiTQ4WYKYDt6WDmBt1jSCpv1ksRlHr/hrlATg+2bAx1s6YdtVcAeOJShH/p7AQmDLXyhPzM6Blv0t3h0xLaPnkUk3GF0sJAGvR4L39R7oA/fmhwhmMOY9FsqVJgwoxy9wTIFL4PidOoq+IWAMmKtbuF3eo2RhkXJO5mtpkSJTyt8w64sbB5K/H4et26Mtljvv4B2ClISVKVXMPHf9AV4aSyQaZTnyeSktkdXkolbBXzOni9XxSyU0iqW8r6Nv0RJ416DWRheV0zJbeYy3Tt/6tIOrS4cQkC6cCsd24X1p3Zmf+roT53lvvWprT911Sf5JoVVbtzGN0NhGPhjNp3X+KZXR08QGsDovNCRB4bKE3Ld4RfbzfpMvXvM1vbkQKVFhayXqHOHYv7wQAQ0fvRwxGylnMNbYHYozgylP8U8G8dZeEqIRZ8oxBnsp4SgHvAaxEav7dPQex2fB9zrykxuBKzQeGX8m4EGU5bexdQ8oXEKbojcoA7ckqRDRg0qjPc6kKKOF3vwG/OuCDoiDfuaAH1JfEx71ShU5hbR4YO8Z46tnw2snKaIcRIHqKhvmLGyHiEUKni39MT08ZcNAnqVk3iTfStkpBY64K2ZuO0Qq6oJ5sc7Uj/FtZfUFra6oldozQuS9HA4Gk9qwc1nu3jUEhozY9rt2YcifytbolN/bYF+IAvcXHdSnTW7xprzov5gK489nxVGf7FNj55BnmhADU8PeholBwODd/HtP3QBD+GvJGHrkiBS6wdxST35lRg2WrenGi37q8nyN7ujxO1BnwBhh555S5CqLO8KOitCQeRz5n6rVTEn5sAqvdYKUwrbU9VMbwJjEOcwoysSYCAmxQJ6zTW3hayWKF4IRwauDVVjuR/DvrNMyGkYujJlvwgVoTKO0/nM8K7pdJVbjZwrIyiReEpzhyqZwYrEY66X3xPPqWno1/2ut9W+4ZVLEleySna8Lf3YvolnV+Vq3VK1dqFau1CttN2Sw9s3uNM+hR1sZl6NbIVervcazEfJ4sR2/hvtJy3YiRMYJJ4w6MmX5DelxIY6/lDMbP9KGSNMHRv955WCPTB8unb3h5NxVlscRlO1G5BXtYyUoi9seyAexSEgWj0IQxU4U47L4i3N8he+5fAxUbjo01fQgt8KVehXqlpCh4dQGY8K4wM10af/eT17vwmT7eYtjGenPQFh+KK9fjLYSnfwN/o+cdvwboChzKK1w2haDCcjp8W3/IbfrFDbRAioz+ELeVhr4f26PkYMtBug+lgnZ/8uxut6gU+NpdeiIb/VDttB13n51e+8+NJd57vPvfa6Z11KAVQLG+kmW50Ig88yvGcViw90uKjpY9+8jncKL06snL6sKeDEAoCCax5ObylSzw5PP5WGvJ6ySYEswG7dePQmH0ybGz7r5BLQtzRKLz3dcdEEhZYcUV7Z+XqNoMHXKnHzp0dn8I4QRWc2YoLOzi5pocraKEl5MsVczhleC3EYqzSN1F6OyN3FFFZ42zEWxGNGwOfecj/sXFfRWGidkzl8xPWKhOOthdAdx8ZOL77wXi9AzGK6uGc/WeggCqEpgQSrgykwXGgoN4PMiHGglUhjo1raE1ND7meZj0PASAt9RyQb+4ZiuKdHPaMCmVmOfIbYM6zGDa88BVa80ZVsvHg4hZ3GsCSMDYG+gZCGg68Znej5wBNMZxA0+1KX6s06cksDTB9LynMB470wKlIt4yQMdwdkgtg6ngVYVWzPj3VLATvAuMNbH8x1wRYP9W1HzEuBUO21g9DgR7mUXlHCViy7Ls30ctDqgxhy9QJU660IDa374/F8go7cZZB3mhuBqkUrghrU2OvqelW0ayLcfCzyKwSNM1s7MGmq8jInzQgGIqGdQcD9o0G/QC5mrI92NKnidxQRojcDw2WAtgLlLUCnycbFjHlY2tXRG8hQFEFRWlonH4k/tv3XCE7xpspFybgmjCtjdAruOaP+AhUehg+/w6TI9hks7ILk3RNSKJS3VevudDrwtsisqNCt8hquSspk6pAts+OcN2/Ur0Etjy3hJd5HDREDpF9Ma/TNJDBTvWJisgjJoiPDzepQHOso6UtcCcLsVLQYLCixAzWsp5YMHUY/lJRSDhrD+1VBMwItSPADt8fNuLKPbk/lOHSnyUQW2JFvKROD/L1hXZXX14PCliu5IZIBmWsJ9yhE+e5C5mJaHJ6tc7IShC+kA40OvgDdBTFy+JYAMwilYIln3AK4lki80g3HVhYNEa/i+oA+RN7Aj/IRH6OGfQ4dozgt/Gew/tppHWiPDmp6jeJtwkx+jXXr1VqWaxdvxQJqh7ZKs2MpaG2vYtnwGTPd4TPa5I4/Jr99roeXz1Z4Cpmrre0VqZaIhysFCEBNg1JC6cZd8xbVESiv9i2otxX2KgJPKxbVoVxQ7W9kMR30GwNaTwf9JvwY4Y/WQK2tQ3NdCS7S/irULd1VqHf/P5I6DmkTuW+meavn65Ph943GfNUBhTiNL98eqXn5F9lG0zjPh9FqnFySI+eWM9/NQTqAPUSFL4H0U8xoY2w1sjyHLCq5+bgVqiMi/FKT5TTL39pqKd7JS8DmnsrjJBrjtQvQ1nFrq9bp7LRv4gIW8FEzD3IQ9UQhv1MOhREBliImHrAGQmE+T4fHrSHdNH7cglkV9eElJoMSwNzxxO11OiZhFq1KJE6BVsrmC7eHATR4r0+yPBmmc8xt+ibPFh2W30FHmi4P0AVVNomPhmP4w5WLsFPKiuq+LGNPJnQBbzo6cWguyWn7lgM/xvOYD+AX2fwQb3Idx7gUoSjdtyuirYXNLXDNu2mBbmCCZlF2giw3mi72oxC6qEwMlq9lheAE3DUPn4ZzF2N6sUW83Bz+iLM7I6qXMhPSS+pospdSRl1kIRQvu8gDg/JvE5R14bOikwb0JUIXr6vhL58CvvRT7rmvKTh8JZsRa7TDMwdTTrMjPWYxo9kItntx3GhNkTxBi42JUvvfpQaHW+zpIK0Nt9iviG7FNryGbpFTgrwre3pSE7b5vJc/0/LK/kVr1xY6SKAOI7UG0/eIv77VbFgf31oBujHLc9Ase45yjZvratzEGpQcFN3yeM7gKcAntNtzwj0oItMB03qvzBVXtFouV+nTeedtCkNenxiNC6h4NlnIDrFDSvizuy/+6fdeH7704nfuPXfvzykrsCu8fGAL/YaOxhH7ClJcAtu9UQbbrATbMMC2BFhRowCz1S3D7FTC7BowGwyTD34j8gouQW63KnrbrYDcuKEhd7oMWRWaVgBuXBFwu9TlM53GioINahTPKJLuy0WN4fdhXx70jrxvi8/aQ5xqDWQw2muz+Xy5r4MJ8fAVc83kwAcyTN2+h6GFIr24s7taitsH9oFIeQB4UeU8A0EGuIt1KZBY57j+97f2qQP72AHsorfd3qIPd8J28UuzJT91Cp+UsL9K46HwR1COkHQtscig1eroEAg7grTZXR9AijuPSMx1o2Ebdl9E4JSMpy6S8RiRefMJcOF8BsKOj9tlfRyPpoC8sfBDAXF8F5CpL6aiQJQx3fmJ87jE6CnKS8mpXld4n4O+4Bj2gFUOQhLFDWIsnR1oIYAL4yJ2gsM+c7z9mILu8WIqzF0G8wc9nWAsLPANlHmhj6sRvgYUTJLlmlDRQijEbYWm7Rtlq/GpmwLiYR9T/MV3xUy5PZsP9XUZEO5Jn4Uyp2eYSROnUiYOUU43MrGQ6oBv9qtuEID0BcvxDBSkJq392F044wxc6nS+OoOh1Yx9eygSi/hiZBC8Vcqlo75fIdPfrZJ0XcyWhLXe9GuIaf/Is61H9gDliWopPzwygbAQjM04VeFD7FBhLx87BJfWEf6zDcPaaj67/aa1oozfyk3rqPpOHOqPF4oIBJ67Po5vsB1a7I7U7LlKXCC5nzEnOJ/q6J89B4BmGCS5DvDPQFcrkC7WWU+05FqgyVXAtUmW/gihANf5DokF8pK8YJQfomAgZAhfXd7sp00/bflp2087ftr10+vsRHE/bbaaN/1Wo3W93ujUm02/6bd82DVaN/z2TR9tDk0sA7u0KnMDSrTgf1yo43fafvM6FWqqQvDxut+EDzeoUMNvX/dvUpmWKNOtN1p+x8cWn0VwsC12mgCOCrV1oZsAnMA0sEi7jd1qcXMdVQqK3KRC0INnQdfCjrduUKGuKgRQb2Cxm9h1TEOP4KjMdVUGetoRPYdeXcfOdxgBz4oy+D9AUrOD/cLRN7G9JgO6oQoBBOzfTRo7jKtLpajQTVUIxgSSDha9iaDaz2KfGJfthi71rM89R9zdwCKozkIRie5nAeOIyjb16ga1d8NvcqGWKoSoprltMqgOTgr1u93WhXB2cayIJOwQ/KCJa3dUGfjSFHDE0KD+s1RIYvtGvdEEPD5L89slUsI2qMx1XeYG9YjnjVEAb7jUs6oUttSgHrUllpCeqNQNVQpHJCgO6YTw1GpRoZu60E3qUFsQHFLTdf9GQcQeJ9FeOqeD1a+ZR/mPKHv7pcwhSoTDuyqBjWYZ2WcFd47MM/lIHPVJs8mu+XHX+igTTuQHdAKcT5IUr7+NvG+bj/LChSiM+lh2gDB3+ae100fe7Q7d0b6gQ6DIw/AV/bzrVZ4Xm4b6oqcvDnQ0jyc02D4sqIHOyapUBvbiLkYS4Q56bDgYU6G1LjB094NS92q5pRS6pnIp/Y8LRUADNAEcCzf7Yw7csYpO50dWUeU3X1VY3OsgokxwQ2LP9UIx4e2uko+Rv/yx6S/PwM9UtTMDkZy5Ft0PhqCv1yZ06YCQRXxpyZlnCsnjkIr0++KawW1dZKBuq+2TU8HEr/Pfgc8T7QVokkwjUJXNxA8yryyIiTDIG5xMVDe83faqZMZy1rhU2AXQQxcIB9Ps472+LB9mLekeIGTDk3Asx1DOoM15q8d9c3CVhWYrkaNbnmzTidUbvAj0mz68DBsqReEbD8LaG/XZCs+hRG/gzUn9RJoudmonHCpFkVKirecoqSHZaoeczRjxPE9BDMNxv/EAJviNBwPl07ck3jBFU95eMAXx4q3ac/7JAz/DtDPs/K7unseBhs/9m10Vk5/nmTB51monD+r4nWIghDEKBpUvzQInD2TfjVJizbXCZh3g7eR4LeYEa8rIqAoGYC7NUgI+Y4pxQkX0kOXEXZz7hUyuh9etJttNKUH7C1sINijurLBM8Gaw2SyGlULhBBGwHry/QW8nm1OstkT+lLB7qSeLvrXAlKBvNDZE5bf9oqsyK2Lf0xf/wkzTjRz1aD+OxoXh1A/zOo/I0SNSeufdaLQvuIFSLffilFA2Flf94rYGWuM0gT1NyquO8zzw75hdG1FxlHMsE2I7+5h1CO0F8TEwjTSi694MnPrSwDzHO9KKNuW1Kud44t0Ojbm4GuvI4igna3qS0i3fRD1S+HYFPXyNHLjW4R4MeI6XglPyHEFMuwkHlV8hZa5ICm2mny+kGTEyxFenamVXiKslZr1MsaxUC206r1QSNUHrtAsFhfOqamSh3hp9Uhcqh7NLXbKxNpLe9FCg/giP/6KsMSqazQra58C8pvMVQmx9Gh/G08KyVFTiHOaCSPC2n+kKF09Q8JfIK3LnmrvU5iRylq/VqOdIx5t60/aH5/c7HLPO2ezM67iwi1fsB7Uk7qwUNak5szU5fnldALeu8OiZS0eW4Te6jH0p6qurJXQ7doRcHZippC+zgPJ4zeVE7uBUUctzZHGUUQXGN5Rr+FsRYcM8NKTZkmUCaEJ8DvtGudGmnmGd6HAPzViFAMHj/oGRYUbDHpgO57JfZ4W7MUt3Plp5j4GjrMty7CpsCJ9//Fk6LFPolJ72VaVgWEMdECbwTotM54DQDm06dkwtxg2OMgTctLub4PV7qwGj+JWbKFjyzVasT1ZDdqUrt1U8ITAbs79ZrRWqXbk5Ky7ObMv4YDVkVrislTOTER2G6/JrWjQr3WaKpGsnq5Sulofk/GR/rMguU0poWV1fft4AQSS9rK7PHwu1zwqM1FqxRX/HeASbPK7y0wP0dhR8wfLc0eUEEC4qIa4pi+6fXJC7bhSv61a8ymZ286GurpM0rAGxzhEzHinefkWHndvdp5QEl/P5cIJpzMg+KzORAyjFGGWoNQi6oWGckRuXr/cn1dkFXQw9JVcbk5f5Re7jV/AKv2pNl1SK0kosZWAtJF0dmF2DoZyOesZo0K9pNPDRP0nzZWP7kSPilNB8palYqvKOYTViMfdocPHVE1pP9BMaSPQTW0D0szR1DEoNPHW/rc4VOq8RAvpKWDaSQCnf3LF8iQSv0K8rVrf6omjlT5zvrWZRWsfcAEiiziha5XG+w9fE5AGfCcITnqYy2UKxEyenWJIoz+cj9vORkg4QOrDW0FKwjSnpuee/fvfJh7978sE/Oxef/OTiR79yzn/77sVHX178/kPXr6hEdi/3yc/evvjFR87j3/zq4h8+vaQGmb/ci4/f/sMXjz/7mJtzzn//8OLRP11SU9jCXFnn1z+9ePSwdvGbR+fvvV2HPxc/fM+7BISyk7nQ18efPoTiDy/+cm2XLVHDffkF5zVeTYUypsTgCiRcfPz+xbtlcIWdX47l4kcfw59S6eLe7X4fXjgXH7x78fEHFw//pVTe2nxdROpHv3v8O+jMP3xKM1ruU3Efc1+nX87Fv35y/uuH5//jVxe/eLuqgti23H8LfysLi/UvCHUDwV389qcXv37knP/qtxcfvXfx0YeOosCLjx46Tz54JAjx8ad/e/F37zvnv/wUWnHOf/E+UI9DZATfiZag8D8//uyhw1N78ejL8394JCYYvpz/6N3zH30SbKDi7uNfv3fx84cA9OHFrz+Hxi4ePnKQtN/90Hn86SP88+S9f3ry8HPsWOsPX7T/8EUH3ov+PU17vAaa/77VcnacVvvfd7piBVx89DkO+eKX/0uC++WnjFeY9b8+//HD83+AZUbdPIeRykoPr9asXEAX/+2di4/eFgvo4mfw6+F/1i8EtTD2/+nxv8Kof/wr+PXkg88da7EBUh4+/jUVhCYv/stPnvzsp5f0QK+/ZuP8R/+ErYmFaNLQ40/fdp789e+ByOVcwsQ/+U+/A0Sfv/+hjYzzzz6/+NnDcrMymIjjCU2fahE9bG0c8rzbvt7APAU5LB6FM2QpjdQORAqmQ50YngsUMygeHPbg/320QQJ7n6H7RhrvRZQoM3QoEX9GdxmgNptjemd2tyAFVWaExE2galAinLHXLlzUcOjcduqYpKxo2yBI2ot6EqH10+3xNgHSF5rRlQ2PfKh5RePFzLSyoUzhYheGaYZz2I0U5GDZpHv+94/OP/4CFzyz0IuP33Eu/uv7wMKci7/7ITCHkq+q1TUM8yvqI6KrLtDr4y++dJ785NH5Z7+TC1sRGLHrT3HtIeFBs0Bn4sX5P37pwMbw+PO3gfBg3TkXDz85/+V/ePIBUeH5L//1yX959+KvfyNoDxbE28gMfo/84gNYDUCc8N6ibVpuP390/jefOMCZLz55Gxfx49+8Ty09+hhKGLRsC/1SJKCrm0UOZdB4FvMUzdyYx33pTECWRZrJ9+dHDsigCWd6F1gKZJ6b6KCKeqT4d5XVQI5Ah7dL1jKEvY6eSLc58A+8AlXJlbPJNG5MJvHI/3n+y3/G3UKhnBD4c9jxPiS++cO/hXLGTvFKjN7Vzp8ZrlhMCOe/gFn9ORPcBwbuNcavcChhfBK+HPKKP9Q7rKMJsnzKOD0M9Dc/CvFAqg940c8R+TVnmc5IBg/F08mhYV/RSTHVy4pbgeS9PNrkouvpt1UVJZXEKtODfGOBN9mrLmq9LkLVJwMME54rQZrlzJfWCRAxHbfHf80vSKFCAIPv+GQduEoVz5oWdoo3jjN2jFMMdnhUJy1rzjLovgd4M2cmuY97MfnkxW+hXddI6WClMZ5TVlgnX8QjdO92rsuLHziLhOQRJVdi2AnyhCX/p/ZzeOp7kL62Y4Rv3XW0xknCTtj8de9bKt3mTH4EdNx9mMxXhcSYV3AruHLS0bUpQr+ie0LB98BK8bfZ96CQs+8b9D0o5+ozfA/E5p3m8WhF2WstI9y6JKtW7RxY55ARWa7dXBtymvstsjpGgPkw3H2m4P7vimOiIRKBOSA8Esg59ZWkD4/tl/LRSkdZtl4asRV4MSnqgTnFEheSd1zpZG5gxi/KdS5PKs2MIMVwQguOPKs0rxLCTBe6f+oQEcOh8RrbrOqjaeRbTPTlkYQprGa+Axg+vS+cK9gnCRq2PlDAHeJwWF0M+qcKFoLBpWgzUUKNsEISODZBHlZWGZWqQOfX1OCb1NioxcYsNmJJ45VcI34F2fsVxDyotOPy5X/cg9EEzaSLiWWeLdtHrxioLmJVDGrKYmSnBjEZZ+utpzSjpnE8Hi6P5uLawTNlW6sitnprPa3psPynJTS6KLZ6scik7jhVuT4xMxDs/ZEmWZkZ+XqGfFQjOdmfT8d4uYi/Alk7dF1zhY5D+FCHAsYhImbuCd2L//ERyMIU8jeWrjXu40/fB0WdX96WL89//DPQadzSHE7cU2r/rOecQgu9vbNT7MGZ879/+LfOKbSr39ROqdUz5xTN92NPffG4LW7paQBypzxXogSvqQTmZYwc8aPNk64PU0OTMfBH8pfJy7m8Zb7hOjh1XId/AZIeueWaFx+/zY3V0E7jcV2ccK7Lv9bUtSyUXJOJhOuK3xVt/t2nFz/8G+wwGvq4YpmWGEjVe/fivb+p6g7h1jl/5yMbdAVJMi4r3pdATwBDD5/8/XugKDvSivnzX53/53+5+Pk/wnxTVpNJ//41c0vFWwzOEGUCzsCwc2sB2hiZFHZHJ6NpbEnTMhYxzemyZL5zF0Oe6RpovHVyWMLQncZA+QWY4SkiHlrulAR0L1rovVNeeCBa8+40rWwVqrgs0H9zUNe/gWtx6EVx91Xw1IVaIiWDBBnWjGupNUSZoka+ENH7sqgxCnTRkh56m/DiFZPAGGhRQdEEEc3MOmu6dCtQOPB0x/DR9vD7Kuq0lK/sOEq5U1T5G6jEFhU1mtU1VCNMbqzSHlbBVAVwf6mCIDcgADGpAqC/j+zvvP/Aa/5hfpMaJavQxBnNz1r3tKaW8w0qMrhCDTG3opJ4qhqEWUllHSoSr1ch+uag0U0jVvTiYQqKGGZmnGBg7XjiOykGz+zOszy8Xgik+y6sbVPJJknCOcKLRChXWkxhazMgoZyUahZoqJiPLyiecBZhjjV8TDJYkVPg4ag5iuDDaj/CZusb9B7kXq0RbG5tkoiMLskUSvpGoakp+HAbpuyDTmXZWHOzP3ESvlXJwCfh0HeS7SZ+OiJTIiEIk8wsA+fu8Wi6Giu87sZkV3EwXhBnUYccpgfp/EgaGtfpHHZuvsV6lYO6Va103HLS4ypUknuv4Zpo4oZHiXkGU/M1APLpk2e6ir0GeAFVDp1fRUknn6MfLRvp6zQm5xBoSpzMoiVFXXRneJaNUfYsuEOi2JRLsaU+VQLMTrsbNJzt6sIkr1Bh+uXttNaXJfmEytKvjWWFPEKlpWyy09xQQZ3BUxX1BJWC7ro6FfIK1a54j3DWtl0hnDD+yu839sdS9QVWrVeEskqHUbGg1NkP74U4zZ6fTnxLNd02thzPXpCV14A2Buo6lYM4FCX5Vk7FHWkZiU+eZ6fjx2pPq57Nh7C7TOd7SjWTUZc6aSdMyE6tEbS722PWhsb+0B+yC+dBPPBND09Re0fm0edAACM50TepRPmFWZO6JW0qVsK0yixGInWfGOVEOkcO/cm60XFGxCi1k82IoW5RkjvPbCCrLljDknUERMESpg2F+94/2HY5rcUgxD/VBfBiEA5uVgnSoEnPbwSdLpLEgbyhXeJcrG/eQjpBw7MQVliORtLkQfUwLArBBqtXtFRIZUy1jV+1MFQvmB45n4vLN2RhyVJnp7D/ixwbeKdkn7YhbmDo857EbfR7NwaDYiNqSdjZLNlawqVMO3GCuJ2CeIrT4edjuYc9CAUH4BRWdWEwxanFHF/H4itUMG8gs2LdaPbUtSMPth6Y11iYZhnsBN/zIG020mpN3ZVdsiwhVNworRQEeXRoLxOfkNavMcEErYbn13ipBs02/qYFGzRb+FssW/GkFm/QuIHPFUs4aHbxS8VCFnWs5UyAB5ayJTsNSzUkdOCi9cuLxi8uE/NuRLr6ggzNeCXe/0lj9WA0W9YoNfPSr20a4nOOia+/a+KJxtFCLOYEZL3lCeDskKTtNN8QUFSUvg9j+/5QX14yjikpkskkRtHfWURLKIPuavRiBBLTKE5BQprn5q3pOQf9yEQT8nZPEe5DN3niKVacnVTd6KnuCF4jsbcuyUmsHTG/5i2gdmYq+wJQlNOf5u5PMR/GtZ9yC7tEZ9IqE/b7Ok1jrdmVkvbOTldxV4MFbLStsuk33GQT1kZVUvfE3sDf2YN5k1IKu1ODDQVmDc2OTcPD174D1Tj+KNx0at1vkcfhmttS7UghgfpSlwsG++XERwYMM5oBbZQ4uMmOJaMy2sHhbwTYRW8Xg8Vb7N0/Nc5AyEV+Og2D7g1xRzaO1bokezvotLaWk4p7qrGo7X69zpveHqC6qGdSdbmOZETW5TminxXltcWEELC+YUIN3s6WLfNqd3lxqa2Vyldb4CPWd/G9X75UVdzYal3NXWI0eG/j2pvfb4eb7m81e7JIRgfillRMPeJz4COqwur+EsdMSaoP+zJ9PQkPVpxRcvVaxn47aqRynHYiT+TCWWXy5HUtbAIoL6kEvoQQKJcK/J/XP7wweWTpgl3BkUITI/oqYryYzKamgX9s0bZ2TcvMtOHiKlwMIAPBWOxRIAa6F//tP5Cn7G8eXfz9pxcPP3aLF41H3hU6VVgN1KliR5++a+zEht6pH33OjqjOpZ0cSUutxbfWCfmaMa9jczxZivELhS+ybYKkkIwWvioGe2HQbuj0wIXyJhVbSC35gz09ljfAgOKKtwyq1RaVfFD5zofGIc35e29ffPQTcZBW4NlPM5AqGi4O7usNJAwb5YGg93D1WK5KkwRoPfEZKdBlOklY+LVjy/hH+xnfyl1m5pT7wNzOWOpGlIRUgutpWbzrWXd+7MXFolKINwuS3AztxmEt6FzfMi8KL8bBYSxWpZfidtDq2DXNSJ61tZrdLT0kfFKdLm8uNdXPSkqv4kpl7D8t18HTwj98IZy0H3/x8ZMPP9jAbvDshz4ZsNG9jfSO6XyehVofrhqDkaqE9havfsO0wdE5eYKpF7FSiZbwP5jzjjbqlGC9pXdY7Yr0VtUObiJauvwYu3cdAXv++q7rT6Wl661jC9ZY9BayvpE7oYVN7wqsx+QSa2jmysQgo2WAV3zw7gYy0BICi+Y8mb5l6rzC5u2DWoxpNsOirFO8gL7bM++b13do2zJJgVLWDnPiclCBGKdzarS13Ty7ZNwJX6qkk4qUW8/IzH6At09sG9HuyMPDzOTlJgtAY60+w5HTZnW8Qnwp+RERGNlzl0NdZFgLhQehg3qFqIFRHuhr/fN/FFzAufj5u+gRf/7phxcfvuNa2ktVz9ZLL5f08fFnXz7+l0/JOf4vf+Vc/NU7T/7qkXP+t584Fz/65OLjRxR78tF7whNBRV+9g67cP35IXuHczKU9LO6Fm/s1MSpc/PbRkw8fXvz3Lx//7lNskXFCATPcR12UHCNwhvv3r5U2avKPuHjvb0TEzaVdrtrBL5tx3WmKOcOQBwxW+EDG1Vx8wHFFVE7gk8b02UPAp4hRuLRnVdvGJT2zY9tg1oVbCYzrD1+I0CTdHaADHPDH74hAKQ64uBxjFge7DFd/9Y6Oh8IOPf717y9+T/FWF58gHZ//8+cUSiLI2SI6haevYj5A9oVx0UgnxZMqZb823wujJ+iYzV5Z0igN7BfvaOcdjKr67DdAERT9QqtMLLInP/6PMHWPf/ue623oHh9hql6pbNzYGestGmGv0Dkj/u9zuz/WSueoO+Fital/fGqqsYaZu58GWVZwawlHVp+AumDlIgcFXnfx8U/MfiHT5xM32EidP3zhuMGbc7yblJvDmK318ezKRiC+BtFymeGVyzwqAKnOKwolYjyUwERNQ9NmJs5UtC2sDJqym0NXKXk8VEez8VCZc93izRXq/ju0T9KBJ99oMEM3iJIzKby4gn0Rx/QN2j+lZSNebFp+a09MhRaCsSCWZxh2ZhNAUMGxyIajNSPREgI3dhiiNAqJE5ugsftJRk7RkrRfnL//iFg3rIyPkJf/L+d0tNhqNhq9oDE5e+biw7eNWLXzn356/tGXyL66KjxYxL0iM4VdS+8JFGoLxP8vn+OaPP/Fz8//+qcyTPTv3scIKrnjqfApb/2gTObDi53Cfq3FLT0JBQ9S4yFM2k6FtJph5+wFzQk6F9rDFOHFMqb1Q83uaDdDFgMyzydvk3xDAXlyQ/nsSyiBuOfIU4qH/emXVxuiJaugwPNfHzrFyPrimCTjpKHAfPmF2OPqWpKdrUUA41VOMu1dOOj//uX5Z2/TJstC7sWPHp3/5YcYo/jhJ5VxzKVLNIp5+fRCdnuwxnzFnHr4QwaO5m6PkIUBS2f/H0qKRGU='
_RUNTIME = _Path(_tempfile.gettempdir()) / "md_lotto_runtime_v56_final_bugfix"
_marker = _RUNTIME / ".ready"
_RUNTIME_VERSION = "v5.6-final-bugfix"
if (not _marker.exists()) or (_marker.read_text(encoding="utf-8", errors="ignore").strip() != _RUNTIME_VERSION):
    _RUNTIME.mkdir(parents=True, exist_ok=True)
    _files = _json.loads(_zlib.decompress(_b64.b64decode(_EMBEDDED)).decode("utf-8"))
    for _rel, _txt in _files.items():
        _p = _RUNTIME / _rel
        _p.parent.mkdir(parents=True, exist_ok=True)
        _p.write_text(_txt, encoding="utf-8")
    _marker.write_text(_RUNTIME_VERSION, encoding="utf-8")
_sys.path.insert(0, str(_RUNTIME))
import os as _os
_os.environ.setdefault("MD_LOTTO_DATA_DIR", str(_RUNTIME / "data"))

from pathlib import Path
import os, threading, time
from io import BytesIO
from zipfile import ZipFile, ZIP_DEFLATED
from xml.sax.saxutils import escape as _xml_escape
import pandas as pd
import streamlit as st
import plotly.express as px
from md_lotto.data import load_csv,sync_history,save_sqlite,dataset_status,save_sync_status,load_sync_status
from md_lotto.data import sync_incremental_official
from md_lotto.stats import number_stats,pair_stats,triple_stats,structure_summary,randomness_audit,fdr_summary
from md_lotto.optimizer import optimize_games, deterministic_top_games
from md_lotto.backtest import walk_forward,summarize_backtest,nested_walk_forward,strategy_tournament
from md_lotto.simulation import monte_carlo,theoretical_single_game
from md_lotto.ml import train_evaluate,walk_forward_ml
from md_lotto.diagnostics import recommendation_actual_diagnostics
from md_lotto.transitions import latest_transition_report, next_draw_adjustment_report, adaptive_priority_five

st.set_page_config(page_title='MD LOTTO 6/45', page_icon='🎯', layout='wide', initial_sidebar_state='collapsed')
ROOT=Path(__file__).parent
DATA_DIR=Path(os.getenv('MD_LOTTO_DATA_DIR', str(ROOT/'data')))
DATA_DIR.mkdir(parents=True,exist_ok=True)
path=DATA_DIR/'lotto_history.csv'; db=DATA_DIR/'lotto.db'; sp=DATA_DIR/'sync_status.json'
bundled=ROOT/'data'/'lotto_history.csv'
embedded_bundled=_RUNTIME/'data'/'lotto_history.csv'
if not path.exists():
    _seed_source=None
    if bundled.exists() and bundled.resolve()!=path.resolve():
        _seed_source=bundled
    elif embedded_bundled.exists() and embedded_bundled.resolve()!=path.resolve():
        _seed_source=embedded_bundled
    if _seed_source is not None:
        path.write_bytes(_seed_source.read_bytes())
_SYNC_LOCK=threading.Lock()

st.markdown(r"""
<style>
:root{--bg:#050814;--panel:#0a1020;--line:#1d2b46;--muted:#98a4b8;--blue:#1687ff;--green:#28d06f;--red:#ff4f6d;--violet:#9c5cff;--gold:#ffcc33}
html,body,[class*="css"]{font-family:Inter,Pretendard,"Noto Sans KR",system-ui,-apple-system,sans-serif}
.stApp{background:radial-gradient(circle at 15% 0%,rgba(22,135,255,.12),transparent 28%),radial-gradient(circle at 88% 15%,rgba(156,92,255,.10),transparent 26%),linear-gradient(180deg,#050814 0%,#070b15 100%);color:#f5f7fb}
.block-container{max-width:1120px;padding-top:.45rem;padding-bottom:6.2rem}[data-testid="stHeader"]{background:transparent}#MainMenu,footer{visibility:hidden}
.hero-shell{position:relative;overflow:hidden;padding:1.2rem 1.25rem 1.05rem;border-radius:24px;background:linear-gradient(135deg,rgba(29,12,28,.96),rgba(7,14,31,.96));border:1px solid #263556;box-shadow:0 18px 42px rgba(0,0,0,.35),inset 0 1px 0 rgba(255,255,255,.05);margin:.2rem 0 1rem}
.hero-shell:before{content:"";position:absolute;inset:-40% 35% 35% -20%;background:radial-gradient(circle,rgba(255,60,110,.22),transparent 60%);pointer-events:none}.brand-row{display:flex;align-items:center;gap:.75rem;position:relative;z-index:1}
.brand-target{width:56px;height:56px;border-radius:50%;display:grid;place-items:center;font-size:2rem;background:radial-gradient(circle,#fff 0 12%,#e53b49 13% 27%,#fff 28% 40%,#c80f21 41% 59%,#650713 60% 100%);box-shadow:0 7px 20px rgba(255,50,80,.32),inset 0 0 0 2px rgba(255,255,255,.55)}
.brand-title{font-size:clamp(1.8rem,5vw,2.55rem);font-weight:1000;letter-spacing:-.045em;line-height:1;background:linear-gradient(180deg,#fff,#eef1f7 56%,#b8beca);-webkit-background-clip:text;color:transparent;text-shadow:0 8px 20px rgba(0,0,0,.24)}.brand-sub{position:relative;z-index:1;color:#aeb8c9;margin:.65rem 0 0;font-size:.93rem}
.sync-ok,.sync-warn{display:flex;align-items:center;gap:1rem;padding:1rem 1.15rem;border-radius:18px;margin:.55rem 0 1.15rem;font-weight:800}.sync-ok{background:linear-gradient(90deg,rgba(18,82,50,.44),rgba(6,27,25,.72));border:1px solid rgba(45,214,112,.38)}.sync-warn{background:linear-gradient(90deg,rgba(104,62,11,.38),rgba(40,26,8,.70));border:1px solid rgba(255,180,55,.38)}.sync-icon{font-size:1.6rem}.sync-main{font-size:1.28rem}.sync-detail{color:#d7deea;font-weight:650;font-size:1.12rem}
.section-head{display:flex;align-items:center;justify-content:space-between;gap:.75rem;margin:1.15rem 0 .65rem}.section-title{font-size:1.52rem;font-weight:950}.date-chip{font-size:1rem;color:#b8dcff;padding:.48rem .78rem;border-radius:12px;background:#0b2242;border:1px solid #174d87}
.lotto-row{display:flex;gap:.56rem;flex-wrap:wrap;align-items:center;margin:.55rem 0 1rem;padding:.28rem 0 .9rem;perspective:1000px}.ball{--c1:#FFF06A;--c2:#FFC400;--c3:#9A4E00;position:relative;width:70px;height:70px;flex:0 0 70px;border-radius:50%;display:inline-flex;align-items:center;justify-content:center;
background:
radial-gradient(ellipse at 25% 14%,#ffffff 0 4%,rgba(255,255,255,.98) 5% 10%,rgba(255,255,255,.40) 13%,transparent 27%),
radial-gradient(circle at 35% 30%,var(--c1) 0 16%,var(--c2) 46%,var(--c3) 100%);
border:2px solid rgba(255,255,255,.95);
box-shadow:
inset 12px 13px 18px rgba(255,255,255,.52),
inset -15px -18px 24px rgba(0,0,0,.62),
inset 0 0 0 2px rgba(255,255,255,.20),
0 11px 18px rgba(0,0,0,.60);
filter:saturate(1.65) contrast(1.14)}
.ball:before{content:"";position:absolute;left:8%;top:5%;width:52%;height:24%;border-radius:50%;
background:linear-gradient(168deg,#fff 0%,rgba(255,255,255,.98) 30%,rgba(255,255,255,.30) 68%,transparent 100%);
transform:rotate(-23deg);opacity:1;z-index:4;pointer-events:none}.ball:after{content:"";position:absolute;left:13%;right:13%;bottom:-10px;height:12px;border-radius:50%;background:radial-gradient(ellipse,rgba(0,0,0,.72) 0%,rgba(0,0,0,.36) 48%,transparent 78%);filter:blur(4px);z-index:-1;pointer-events:none}
.ball-num{position:relative;z-index:5;display:flex;align-items:center;justify-content:center;width:72%;height:72%;border-radius:50%;
font-size:2.08rem;font-weight:1000;line-height:1;letter-spacing:-.06em;color:#fff;
-webkit-text-stroke:1.6px #06080c;text-shadow:0 3px 2px rgba(0,0,0,.95),0 0 5px rgba(0,0,0,.78);
background:radial-gradient(circle at 40% 28%,rgba(255,255,255,.10),rgba(255,255,255,.01) 48%,rgba(0,0,0,.16) 100%);
box-shadow:inset 0 1px 2px rgba(255,255,255,.25),inset 0 -2px 4px rgba(0,0,0,.30)}
.b1{--c1:#FFF06A;--c2:#FFC400;--c3:#9A4E00}.b2{--c1:#61C8FF;--c2:#0066FF;--c3:#00165E}.b3{--c1:#FF7770;--c2:#F00000;--c3:#650000}.b4{--c1:#FFFFFF;--c2:#AEB4BC;--c3:#30363D}.b5{--c1:#70FF86;--c2:#00B935;--c3:#003D12}.bonus{width:76px;height:76px;flex-basis:76px;box-shadow:inset 10px 12px 18px rgba(255,255,255,.35),inset -14px -18px 23px rgba(0,0,0,.47),0 0 0 3px #ffbd28,0 0 0 6px rgba(255,220,88,.22),0 14px 22px rgba(0,0,0,.48)}.bonus .ball-num{font-size:2.12rem}.bonus-label{font-size:2rem;font-weight:1000;color:#eef2f8;margin:0 .08rem;text-shadow:0 3px 5px #000}
.legend{display:flex;gap:.9rem;flex-wrap:wrap;padding:.55rem .7rem;border-radius:14px;border:1px solid #1b2a43;background:#090f1b;margin:-.15rem 0 1rem;color:#d5dbe5;font-size:.78rem}.legend span{display:flex;align-items:center;gap:.32rem}.dot{width:11px;height:11px;border-radius:50%}
.kpi-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:.65rem;margin:.65rem 0 1.1rem}.kpi{position:relative;overflow:hidden;border-radius:17px;padding:1rem 1rem 1.08rem;border:1px solid #24334e;background:linear-gradient(145deg,#0c1423,#08101c);min-height:122px;box-shadow:0 12px 26px rgba(0,0,0,.22)}.kpi:before{content:"";position:absolute;inset:0;background:radial-gradient(circle at 10% 0%,rgba(25,132,255,.18),transparent 45%)}.kpi.purple:before{background:radial-gradient(circle at 10% 0%,rgba(158,77,255,.20),transparent 48%)}.kpi.red:before{background:radial-gradient(circle at 10% 0%,rgba(255,65,106,.20),transparent 48%)}.kpi-label{position:relative;color:#c9d2e1;font-size:1rem;font-weight:800}.kpi-value{position:relative;font-size:2.12rem;font-weight:950;margin-top:.58rem}.kpi-value.redv{color:#ff5c7a}.kpi-sub{position:relative;font-size:.88rem;color:#8f9bb0;margin-top:.18rem}
.menu-title{font-size:1.38rem;font-weight:950;margin:.7rem 0 .7rem}.menu-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:.65rem;margin-bottom:1.15rem}.menu-card{border:1px solid #243450;border-radius:17px;padding:1rem .7rem;text-align:center;background:linear-gradient(160deg,#0d1728,#08111f);box-shadow:0 10px 24px rgba(0,0,0,.22);min-height:132px}.menu-card.blue{border-color:#155aa4;background:linear-gradient(160deg,#0c315f,#07182d)}.menu-card.green{border-color:#2e6f31;background:linear-gradient(160deg,#153b18,#08190d)}.menu-card.orange{border-color:#8b5117;background:linear-gradient(160deg,#4b270d,#1b1006)}.menu-card.violet{border-color:#67318b;background:linear-gradient(160deg,#351449,#16091f)}.menu-icon{font-size:2.05rem}.menu-name{font-size:1.18rem;font-weight:950;margin-top:.38rem}.menu-desc{font-size:.86rem;color:#c1cad8;margin-top:.24rem}
[data-testid="stMetric"]{border:1px solid #24334e!important;border-radius:15px!important;background:linear-gradient(145deg,#0c1423,#08101c)!important;padding:.75rem!important;box-shadow:0 10px 22px rgba(0,0,0,.18)}[data-testid="stMetricLabel"]{color:#aeb8c8}[data-testid="stMetricValue"]{color:#f7f9fc}.stButton>button{border-radius:12px!important;font-weight:800!important;border:1px solid #2b4772!important;background:linear-gradient(180deg,#123f73,#0b284b)!important;color:#fff!important;min-height:2.7rem}.stButton>button:hover{border-color:#41a1ff!important;box-shadow:0 8px 20px rgba(15,115,220,.22)!important}
[data-baseweb="tab-list"]{gap:.32rem;background:#070d17;border:1px solid #1c2940;padding:.42rem;border-radius:14px;overflow-x:auto}button[data-baseweb="tab"]{height:3.25rem;border-radius:11px;padding:0 1rem;color:#a6b0c0;font-weight:850;font-size:1.02rem;white-space:nowrap}button[data-baseweb="tab"][aria-selected="true"]{color:#38a9ff;background:linear-gradient(180deg,#102f57,#0a1b34);box-shadow:inset 0 0 0 1px #235e99}
.game-card{padding:.72rem;border:1px solid #22314c;border-radius:16px;margin:.55rem 0;background:linear-gradient(145deg,#0c1423,#080f1a);box-shadow:0 10px 24px rgba(0,0,0,.19)}.game-title{font-weight:900;margin-bottom:.2rem;color:#dfe7f3}.md-score{color:#ff617f}.small-note{font-size:.78rem;color:#8490a3}.game-card .lotto-row{margin:.4rem 0 .55rem;padding-bottom:.55rem}
@media(max-width:768px){.sync-ok,.sync-warn{padding:.95rem .9rem;gap:.72rem}.sync-icon{font-size:1.45rem}.sync-main{font-size:1.13rem}.sync-detail{font-size:.98rem}.section-title{font-size:1.30rem}.date-chip{font-size:.88rem;padding:.45rem .62rem}.kpi{padding:.85rem .75rem;min-height:112px}.kpi-label{font-size:.9rem}.kpi-value{font-size:1.82rem}.kpi-sub{font-size:.78rem}.menu-title{font-size:1.28rem}.menu-card{padding:.85rem .45rem;min-height:116px}.menu-icon{font-size:1.82rem}.menu-name{font-size:1.02rem}.menu-desc{font-size:.76rem}button[data-baseweb="tab"]{height:3rem;font-size:.94rem;padding:0 .78rem}.block-container{padding-left:.66rem;padding-right:.66rem;padding-top:.3rem;padding-bottom:6.5rem}.hero-shell{padding:1rem .9rem;border-radius:21px}.brand-target{width:48px;height:48px;font-size:1.65rem}.brand-title{font-size:1.72rem}.brand-sub{font-size:.82rem}.section-title{font-size:1.12rem}.date-chip{font-size:.72rem}.lotto-row{gap:.38rem;flex-wrap:nowrap}.ball{width:53px;height:53px;flex-basis:53px}.ball-num{width:74%;height:74%;font-size:1.60rem;-webkit-text-stroke:1.15px rgba(3,6,12,.94)}.bonus{width:59px;height:59px;flex-basis:59px}.bonus .ball-num{font-size:1.72rem}.bonus-label{font-size:1.55rem}.legend{gap:.55rem;font-size:.67rem;padding:.48rem .52rem}.dot{width:9px;height:9px}.kpi-grid{gap:.45rem}.kpi{min-height:101px;padding:.72rem .62rem}.kpi-label{font-size:.72rem}.kpi-value{font-size:1.48rem}.kpi-sub{font-size:.65rem}.menu-grid{gap:.4rem}.menu-card{padding:.64rem .35rem}.menu-icon{font-size:1.35rem}.menu-name{font-size:.82rem}.menu-desc{font-size:.60rem}.game-card .ball{width:43px;height:43px;flex-basis:43px}.game-card .ball-num{font-size:1.31rem}.game-card .lotto-row{gap:.25rem;flex-wrap:nowrap}.game-title{font-size:.9rem}[data-testid="stMetric"]{padding:.6rem!important}h2{font-size:1.25rem!important}h3{font-size:1.06rem!important}div[data-testid="stDataFrame"]{font-size:.76rem}}
@media(max-width:390px){.ball{width:50px;height:50px;flex-basis:50px}.ball-num{font-size:1.52rem}.lotto-row{gap:.29rem}.bonus{width:56px;height:56px;flex-basis:56px}.bonus .ball-num{font-size:1.64rem}.kpi-value{font-size:1.36rem}.game-card .ball{width:40px;height:40px;flex-basis:40px}.game-card .ball-num{font-size:1.21rem}}
.v36-badge{display:inline-block;margin-left:.42rem;padding:.14rem .40rem;border-radius:999px;background:#FFD000;color:#111;font-size:.68rem;font-weight:1000;vertical-align:middle}

/* ===== v3.8 MOBILE ONE-ROW FIT + VIVID GLOSSBALL OVERRIDE ===== */
@media (max-width: 640px){
  .lotto-row{
    display:flex!important;
    flex-wrap:nowrap!important;
    width:100%!important;
    max-width:100%!important;
    gap:4px!important;
    justify-content:space-between!important;
    align-items:center!important;
    overflow:visible!important;
    padding:.28rem 0 .72rem!important;
    margin:.45rem 0 .75rem!important;
  }
  .lotto-row>.ball{
    width:calc((100% - 20px)/6)!important;
    height:auto!important;
    aspect-ratio:1/1!important;
    max-width:50px!important;
    min-width:0!important;
    flex:0 1 calc((100% - 20px)/6)!important;
    box-sizing:border-box!important;
    border-width:2px!important;
  }
  .lotto-row>.ball .ball-num{
    width:76%!important;
    height:76%!important;
    font-size:clamp(1.35rem,6.1vw,1.72rem)!important;
    -webkit-text-stroke:1.25px #06080c!important;
  }
  .lotto-row>.bonus{
    width:calc((100% - 24px)/7)!important;
    max-width:46px!important;
    flex-basis:calc((100% - 24px)/7)!important;
  }
  .bonus-label{
    font-size:1.2rem!important;
    margin:0!important;
  }
}
@media (max-width: 390px){
  .lotto-row{gap:3px!important}
  .lotto-row>.ball{
    width:calc((100% - 15px)/6)!important;
    max-width:47px!important;
    flex-basis:calc((100% - 15px)/6)!important;
  }
  .lotto-row>.ball .ball-num{
    font-size:clamp(1.28rem,5.8vw,1.58rem)!important;
  }
}
/* Remove muted filter effects from the balls only */
.ball.b1,.ball.b2,.ball.b3,.ball.b4,.ball.b5{
  filter:saturate(1.75) contrast(1.15)!important;
}

.compact-audit-row{display:grid;grid-template-columns:repeat(3,1fr);gap:.55rem;margin:.45rem 0 .7rem}
.compact-audit{display:flex;align-items:center;justify-content:space-between;gap:.6rem;padding:.58rem .72rem;border:1px solid #24334e;border-radius:12px;background:#0a111e;min-height:54px}
.compact-audit span{font-size:.76rem;color:#9ea9ba;font-weight:700}.compact-audit b{font-size:.94rem;color:#f4f7fb;white-space:nowrap}
@media(max-width:768px){.compact-audit-row{gap:.35rem}.compact-audit{padding:.5rem .48rem;min-height:50px;display:block}.compact-audit span{display:block;font-size:.68rem}.compact-audit b{display:block;font-size:.86rem;margin-top:.16rem}}
</style>
""",unsafe_allow_html=True)

def ball_class(n): return 'b1' if n<=10 else 'b2' if n<=20 else 'b3' if n<=30 else 'b4' if n<=40 else 'b5'
def balls_html(nums,bonus=None):
    parts=[f'<span class="ball {ball_class(int(n))}"><span class="ball-num">{int(n)}</span></span>' for n in nums]
    if bonus is not None: parts += ['<span class="bonus-label">+</span>',f'<span class="ball {ball_class(int(bonus))} bonus"><span class="ball-num">{int(bonus)}</span></span>']
    return '<div class="lotto-row">'+''.join(parts)+'</div>'
def pct(v,d=2):
    try:return f'{float(v)*100:.{d}f}%'
    except:return '-'

def _xlsx_col_letter(n):
    s=''
    while n:
        n,rem=divmod(n-1,26)
        s=chr(65+rem)+s
    return s

def _xlsx_inline_cell(ref, value, style=0):
    if value is None or (isinstance(value,float) and pd.isna(value)):
        return f'<c r="{ref}" s="{style}"/>'
    if isinstance(value,(int,float)) and not isinstance(value,bool):
        return f'<c r="{ref}" s="{style}"><v>{value}</v></c>'
    txt=_xml_escape(str(value))
    return f'<c r="{ref}" t="inlineStr" s="{style}"><is><t>{txt}</t></is></c>'

def _history_xlsx_bytes(history_df, status_dict):
    d=history_df[['draw_no','draw_date','n1','n2','n3','n4','n5','n6','bonus']].copy()
    d=d.sort_values('draw_no').reset_index(drop=True)
    d['draw_date']=pd.to_datetime(d['draw_date']).dt.strftime('%Y-%m-%d')
    headers=['회차','추첨일','번호1','번호2','번호3','번호4','번호5','번호6','보너스']

    def sheet_xml(rows, widths, freeze=True, autofilter=None):
        max_cols=max(len(r) for r in rows)
        max_rows=len(rows)
        cols=''.join(
            f'<col min="{i}" max="{i}" width="{w}" customWidth="1"/>'
            for i,w in enumerate(widths,1)
        )
        xml_rows=[]
        for ri,row in enumerate(rows,1):
            cells=[]
            for ci,val in enumerate(row,1):
                style=1 if ri==1 else 0
                cells.append(_xlsx_inline_cell(f'{_xlsx_col_letter(ci)}{ri}',val,style))
            xml_rows.append(f'<row r="{ri}">'+''.join(cells)+'</row>')
        pane='<pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/>' if freeze else ''
        filt=f'<autoFilter ref="{autofilter}"/>' if autofilter else ''
        return ('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
                '<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">'
                f'<dimension ref="A1:{_xlsx_col_letter(max_cols)}{max_rows}"/>'
                f'<sheetViews><sheetView workbookViewId="0">{pane}</sheetView></sheetViews>'
                '<sheetFormatPr defaultRowHeight="18"/>'
                f'<cols>{cols}</cols><sheetData>{"".join(xml_rows)}</sheetData>{filt}</worksheet>')

    history_rows=[headers]
    for _,r in d.iterrows():
        history_rows.append([
            int(r.draw_no), str(r.draw_date),
            int(r.n1),int(r.n2),int(r.n3),int(r.n4),int(r.n5),int(r.n6),int(r.bonus)
        ])

    expected=list(range(1,int(d.draw_no.max())+1)) if len(d) else []
    actual=d.draw_no.astype(int).tolist()
    missing=sorted(set(expected)-set(actual))
    duplicate_count=int(d.draw_no.duplicated().sum())
    invalid_number_rows=0
    for _,r in d.iterrows():
        nums=[int(r[f'n{i}']) for i in range(1,7)]
        if len(set(nums))!=6 or not all(1<=x<=45 for x in nums) or int(r.bonus) in nums or not 1<=int(r.bonus)<=45:
            invalid_number_rows+=1

    audit_rows=[
        ['검증항목','결과'],
        ['파일 목적','MD LOTTO 앱이 실제 사용하는 전체 당첨이력 확인용'],
        ['최소 회차',int(d.draw_no.min()) if len(d) else '-'],
        ['최신 회차',int(d.draw_no.max()) if len(d) else '-'],
        ['총 데이터 행',int(len(d))],
        ['1회부터 연속 데이터','정상' if bool(status_dict.get('complete_from_draw1')) else '미완료'],
        ['누락 회차 수',len(missing)],
        ['누락 회차','없음' if not missing else ', '.join(map(str,missing[:100]))],
        ['중복 회차 수',duplicate_count],
        ['번호/보너스 유효성 오류 행',invalid_number_rows],
        ['최신 추첨일',str(status_dict.get('latest_date') or '-')],
        ['주의','이 파일은 앱 내부 분석에 사용되는 현재 데이터의 복사본입니다. 추천 확률을 의미하지 않습니다.'],
    ]

    content_types='''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/worksheets/sheet2.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/><Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/><Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/></Types>'''
    root_rels='''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/></Relationships>'''
    workbook='''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="전체 당첨이력" sheetId="1" r:id="rId1"/><sheet name="데이터 검증" sheetId="2" r:id="rId2"/></sheets></workbook>'''
    wb_rels='''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet2.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>'''
    styles='''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="10"/><name val="Arial"/></font><font><b/><color rgb="FFFFFFFF"/><sz val="10"/><name val="Arial"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF17365D"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border><left/><right/><top/><bottom/><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="2"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1"><alignment horizontal="center"/></xf></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>'''
    core='''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:title>MD LOTTO 전체 당첨이력 검증</dc:title><dc:creator>MD LOTTO</dc:creator></cp:coreProperties>'''
    app_xml='''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties"><Application>MD LOTTO</Application></Properties>'''

    s1=sheet_xml(history_rows,[10,14,9,9,9,9,9,9,9],True,f'A1:I{len(history_rows)}')
    s2=sheet_xml(audit_rows,[25,65],True,None)

    out=BytesIO()
    with ZipFile(out,'w',ZIP_DEFLATED) as z:
        z.writestr('[Content_Types].xml',content_types)
        z.writestr('_rels/.rels',root_rels)
        z.writestr('docProps/core.xml',core)
        z.writestr('docProps/app.xml',app_xml)
        z.writestr('xl/workbook.xml',workbook)
        z.writestr('xl/_rels/workbook.xml.rels',wb_rels)
        z.writestr('xl/styles.xml',styles)
        z.writestr('xl/worksheets/sheet1.xml',s1)
        z.writestr('xl/worksheets/sheet2.xml',s2)
    return out.getvalue()

def render_backtest_summary(s):
    c=st.columns(4); c[0].metric('테스트 회차',f"{int(s.get('tests',0)):,}"); c[1].metric('MD 평균 최고 적중',f"{s.get('md_best_mean',0):.2f}개"); c[2].metric('랜덤 평균 최고 적중',f"{s.get('random_div_best_mean',0):.2f}개"); c[3].metric('우위 근거','있음' if s.get('evidence_of_edge') else '없음')
    st.caption(f"승 {s.get('head_to_head_wins',0)} · 패 {s.get('losses',0)} · 무 {s.get('ties',0)} · Sign test p={s.get('sign_test_p_value',1):.4f}")
    if 'md_realized_roi' in s:
        a,b,c=st.columns(3); a.metric('총 구매비',f"₩{s.get('md_total_cost',0):,.0f}"); b.metric('과거 지급액',f"₩{s.get('md_total_payout',0):,.0f}"); c.metric('과거 ROI',pct(s.get('md_realized_roi',0),1))

@st.cache_data(ttl=1800,show_spinner=False)
def cloud_sync_tick(_bucket):
    with _SYNC_LOCK:
        try:
            d,ss=sync_history(path,verify_official_count=3); save_sqlite(d,db); save_sync_status(ss,sp); return ss
        except Exception as e:return {'ok':False,'error':str(e),'using_cached_data':path.exists()}

@st.cache_data(show_spinner=False, max_entries=10)
def cached_mobile_backtest(latest_draw, tests):
    _df=load_csv(path)
    return walk_forward(_df,start_train=300,max_tests=tests,sample_combos=1500,random_reps=50)

@st.cache_data(show_spinner=False, max_entries=6)
def cached_recommendation_diagnostics(latest_draw, tests, games, sample_combos):
    _df=load_csv(path)
    return recommendation_actual_diagnostics(
        _df,start_train=300,max_tests=tests,games=games,
        sample_combos=sample_combos,pool_size=20,max_overlap=3
    )

@st.cache_data(show_spinner=False, max_entries=8)
def cached_mobile_ml_holdout(latest_draw):
    return train_evaluate(load_csv(path))

@st.cache_data(show_spinner=False, max_entries=8)
def cached_mobile_ml_walk_forward(latest_draw, tests):
    return walk_forward_ml(load_csv(path),start_train=300,max_tests=tests)

# SAFE BOOT: render immediately from embedded/validated local history.
# External sync is manual so a slow/blocked network can never leave the app blank.
if not path.exists():
    st.error('내장 데이터 파일을 준비하지 못했습니다. 앱을 다시 배포해 주세요.')
    st.stop()
df=load_csv(path)

# v4.0 DATA RECOVERY:
# 1) On a fresh runtime, restore full 1..latest history when possible.
# 2) Then check official local_max+1 for newly published draws.
if not st.session_state.get('_full_history_checked_v56'):
    st.session_state['_full_history_checked_v56']=True
    if len(df) and int(df.draw_no.min())>1:
        try:
            with st.spinner('전체 회차 데이터를 복구·동기화하는 중입니다...'):
                df,_full_status=sync_history(path,verify_official_count=2)
                st.session_state['startup_sync_status']=_full_status
                save_sync_status(_full_status,sp)
        except Exception as _e:
            st.session_state['startup_sync_status']={'ok':False,'error':str(_e),'using_cached_data':True}

if not st.session_state.get('_official_incremental_checked_v56'):
    st.session_state['_official_incremental_checked_v56']=True
    try:
        df,_inc_status=sync_incremental_official(path,max_new=6,timeout=5)
        st.session_state['incremental_sync_status']=_inc_status
    except Exception as _e:
        st.session_state['incremental_sync_status']={'ok':False,'error':str(_e)}

df=load_csv(path)
status=dataset_status(df)
ns=number_stats(df)
latest=df.iloc[-1]

# Invalidate results that were created for a previous draw.
_current_draw=int(latest.draw_no)
_previous_basis=st.session_state.get('_analysis_basis_draw_v56')
if _previous_basis is not None and int(_previous_basis)!=_current_draw:
    for _k in ('md_games','md_recommendation_record','last_bt','corr_reg_diag'):
        st.session_state.pop(_k,None)
st.session_state['_analysis_basis_draw_v56']=_current_draw

ss=st.session_state.get('startup_sync_status') or load_sync_status(sp) or {'ok':True,'using_cached_data':True}
nums=[int(latest[f'n{i}']) for i in range(1,7)]; bonus=int(latest.bonus)

st.markdown('<div class="hero-shell"><div class="brand-row"><div class="brand-target">🎯</div><div class="brand-title">MD LOTTO 6/45 <span class="v36-badge">v5.6 FINAL BUGFIX</span></div></div><div class="brand-sub">과거 데이터·확률·조합 최적화를 연구하는 개인용 분석 도구</div></div>',unsafe_allow_html=True)
if ss.get('ok') and status.get('complete_from_draw1'):
    st.markdown(f'<div class="sync-ok"><span class="sync-icon">✅</span><span class="sync-main">전체 데이터 정상</span><span class="sync-detail">· 1회 ~ {status.get("max_draw")}회 · 연속성 확인</span></div>',unsafe_allow_html=True)
elif not status.get('complete_from_draw1'):
    st.markdown(f'<div class="sync-warn"><span class="sync-icon">⚠️</span><span class="sync-main">전체이력 복구 필요</span><span class="sync-detail">· 현재 {status.get("min_draw")}회 ~ {status.get("max_draw")}회만 보유 · 추천 잠금</span></div>',unsafe_allow_html=True)
else:
    st.markdown('<div class="sync-warn"><span class="sync-icon">⚠️</span><span class="sync-main">온라인 최신 확인 실패</span><span class="sync-detail">· 저장된 전체 검증 데이터를 사용 중입니다.</span></div>',unsafe_allow_html=True)
st.markdown(f'<div class="section-head"><div class="section-title">🏆 제 {int(latest.draw_no)}회 최신 당첨번호</div><div class="date-chip">추첨일 {latest.draw_date.strftime("%Y-%m-%d")}</div></div>',unsafe_allow_html=True)
st.markdown(balls_html(nums,bonus),unsafe_allow_html=True)
st.markdown('<div class="legend"><span><i class="dot" style="background:#f2b400"></i>1-10</span><span><i class="dot" style="background:#1687ff"></i>11-20</span><span><i class="dot" style="background:#ed3547"></i>21-30</span><span><i class="dot" style="background:#9da2aa"></i>31-40</span><span><i class="dot" style="background:#38b44b"></i>41-45</span><span><i class="dot" style="background:#ed3547"></i>보너스</span></div>',unsafe_allow_html=True)
st.markdown(f'<div class="kpi-grid"><div class="kpi"><div class="kpi-label">📊 분석 회차</div><div class="kpi-value">{len(df):,}</div><div class="kpi-sub">총 분석 데이터</div></div><div class="kpi purple"><div class="kpi-label">🗓️ 최신 회차</div><div class="kpi-value">{int(latest.draw_no)}회</div><div class="kpi-sub">가장 최근 회차</div></div><div class="kpi red"><div class="kpi-label">📅 최신 추첨일</div><div class="kpi-value redv" style="font-size:1.28rem">{latest.draw_date.strftime("%Y-%m-%d")}</div><div class="kpi-sub">자동 동기화 기준</div></div></div>',unsafe_allow_html=True)
st.markdown('<div class="menu-title">✨ 주요 분석 메뉴</div><div class="menu-grid"><div class="menu-card blue"><div class="menu-icon">🎲</div><div class="menu-name">번호 추천</div><div class="menu-desc">최적 번호 조합</div></div><div class="menu-card green"><div class="menu-icon">📊</div><div class="menu-name">FDR 분석</div><div class="menu-desc">패턴·확률 검증</div></div><div class="menu-card orange"><div class="menu-icon">🎯</div><div class="menu-name">백테스트</div><div class="menu-desc">과거 성과 검증</div></div><div class="menu-card violet"><div class="menu-icon">🧠</div><div class="menu-name">AI 진단</div><div class="menu-desc">종합 인사이트</div></div></div>',unsafe_allow_html=True)


st.markdown('### 📥 전체 당첨이력 직접 검증')
if status.get('complete_from_draw1'):
    _audit_xlsx=_history_xlsx_bytes(df,status)
    _xlsx_name=f'MD_LOTTO_1_to_{int(status["max_draw"])}_history_audit.xlsx'
    st.download_button(
        '📊 1회~최신회차 전체 데이터 Excel 다운로드',
        data=_audit_xlsx,
        file_name=_xlsx_name,
        mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        use_container_width=True
    )
    st.caption(f'Excel에 1회~{int(status["max_draw"])}회 전체 당첨번호와 별도 「데이터 검증」 시트가 포함됩니다. 총 {int(status["draws"]):,}회 · 누락 없음.')
else:
    st.warning('현재는 전체 1회~최신회차 이력이 복구되지 않아 Excel 다운로드를 잠갔습니다. 불완전 데이터를 전체 데이터처럼 보여주지 않기 위한 안전장치입니다.')
    st.caption('사이드바 → 「🔄 지금 최신 데이터 확인」 실행 후 전체이력 정상 표시가 나오면 다운로드 버튼이 활성화됩니다.')

with st.sidebar:
    st.header('데이터 관리')
    if status.get('complete_from_draw1') and ss.get('ok'):
        st.success(f"1회~{status.get('max_draw')}회 전체이력 확인")
    elif status.get('complete_from_draw1'):
        st.warning(f"저장된 1회~{status.get('max_draw')}회 사용 중 · 온라인 확인 실패")
    else:
        st.error(f"전체이력 미완료 · {status.get('min_draw')}~{status.get('max_draw')}회")
    st.caption('연속 전체이력 정상' if status.get('complete_from_draw1') else '추천 전 전체이력 복구가 필요합니다.')
    if st.button('🔄 지금 최신 데이터 확인',use_container_width=True):
        with st.spinner('전체 회차와 최신 회차를 확인하는 중입니다...'):
            try:
                _df,_st=sync_history(path,verify_official_count=2)
                st.session_state['startup_sync_status']=_st
                save_sync_status(_st,sp)
                _df,_inc=sync_incremental_official(path,max_new=6,timeout=6)
                st.session_state['incremental_sync_status']=_inc
                for _k in ('md_games','md_recommendation_record','last_bt','corr_reg_diag'):
                    st.session_state.pop(_k,None)
            except Exception as _e:
                st.session_state['startup_sync_status']={'ok':False,'error':str(_e),'using_cached_data':True}
        st.rerun()
    st.caption('동기화 실패 시 기존 검증 데이터는 보존됩니다.')
if not status['complete_from_draw1']: st.error(f"현재 데이터는 {status['min_draw']}~{status['max_draw']}회({status['draws']}회분)만 있습니다. 전체 1회~최신회차 복구 전에는 추천·시뮬레이션을 잠급니다.")

tabs=st.tabs(['🏠 대시보드','🎲 번호 추천','📊 FDR 분석','🏆 백테스트','🧠 AI 진단','🔎 오차 진단'])
with tabs[0]:
    st.subheader('데이터·무작위성 진단'); audit=randomness_audit(df); struct=structure_summary(df)
    st.markdown(
        f'''<div class="compact-audit-row">
        <div class="compact-audit"><span>전체 회차</span><b>{status['draws']:,}</b></div>
        <div class="compact-audit"><span>연속 데이터</span><b>{'정상' if status['contiguous'] else '점검 필요'}</b></div>
        <div class="compact-audit"><span>균등성 검정</span><b>{'특이점 없음' if audit.get('p_value',0)>=.05 else '검토 필요'}</b></div>
        </div>''',
        unsafe_allow_html=True
    )
    st.caption(f"번호합 평균 {struct.get('sum_mean',0):.1f} · 10~90% 범위 {struct.get('sum_q10',0):.0f}~{struct.get('sum_q90',0):.0f} · 흔한 홀수 개수 {struct.get('odd_mode','-')}개")
    _lr=latest_transition_report(df)
    if _lr.get('available'):
        st.info(f"최근 {_lr['previous_draw']}회→{_lr['current_draw']}회 변화: 직전번호 재등장 {int(_lr['current_features']['overlap_prev'])}개 · 연속수 {int(_lr['current_features']['consecutive_pairs'])}쌍 · 번호합 {int(_lr['previous_features']['sum'])}→{int(_lr['current_features']['sum'])}")

    _today=pd.Timestamp.now(tz='Asia/Seoul').tz_localize(None).normalize()
    _one_year_ago=_today-pd.Timedelta(days=365)
    _recent=df[(df['draw_date']>=_one_year_ago)&(df['draw_date']<=_today)].copy()
    _counts={n:0 for n in range(1,46)}
    for _,_r in _recent.iterrows():
        for _i in range(1,7):
            _counts[int(_r[f'n{_i}'])]+=1
    _chart=pd.DataFrame({'번호':list(range(1,46)),'최근 1년 출현':[_counts[n] for n in range(1,46)]})
    _chart['번호대']=_chart['번호'].map(lambda n:'1-10' if n<=10 else '11-20' if n<=20 else '21-30' if n<=30 else '31-40' if n<=40 else '41-45')
    st.markdown('#### 최근 1년 번호별 출현 빈도')
    st.caption(f"{_one_year_ago.strftime('%Y-%m-%d')} ~ {_today.strftime('%Y-%m-%d')} · 본번호 6개 기준 · 번호대별 색상 적용")
    _color_map={'1-10':'#F2B400','11-20':'#4F7FEA','21-30':'#D84C5A','31-40':'#AEB4BC','41-45':'#63B35D'}
    fig=px.bar(_chart,x='번호',y='최근 1년 출현',color='번호대',color_discrete_map=_color_map,category_orders={'번호대':['1-10','11-20','21-30','31-40','41-45']},hover_data={'번호':True,'최근 1년 출현':True,'번호대':True})
    fig.update_layout(margin=dict(l=0,r=0,t=15,b=0),height=350,paper_bgcolor='rgba(0,0,0,0)',plot_bgcolor='rgba(0,0,0,0)',font_color='#aeb8c8',legend_title_text='번호대',xaxis=dict(dtick=1),yaxis_title='출현 횟수')
    st.plotly_chart(fig,use_container_width=True)
with tabs[1]:
    _adj=next_draw_adjustment_report(df)
    if _adj.get('available'):
        _tr=_adj['transition']; _pf=_adj.get('profile',{})
        st.markdown('### 🔁 전회차 대비 변화와 다음회차 보완')
        st.caption(f"{_tr['previous_draw']}회 → {_tr['current_draw']}회 실제 당첨번호 변화 분석")
        _cols=st.columns(4)
        _cols[0].metric('직전번호 재등장',f"{int(_tr['current_features']['overlap_prev'])}개")
        _cols[1].metric('연속수 Pair',f"{int(_tr['current_features']['consecutive_pairs'])}쌍")
        _cols[2].metric('번호합',f"{int(_tr['current_features']['sum'])}")
        _cols[3].metric('홀수',f"{int(_tr['current_features']['odd'])}개")
        with st.expander('무엇이 달라졌고 다음 회차에 어떻게 반영하는지 보기'):
            for _line in _tr.get('explanations',[]): st.write('• '+_line)
            st.markdown('**다음회차 보완책**')
            for _line in _adj.get('actions',[]): st.write('→ '+_line)
            _cg=_tr.get('current_consecutive_gap',0); _ag=_tr.get('historical_consecutive_avg_gap')
            if pd.notna(_ag): st.caption(f"연속수 과거 평균 출현간격 약 {_ag:.1f}회 · 현재 연속수 미출현 간격 {_cg}회")
    subt=st.tabs(['추천 조합','번호 분석','시뮬레이션'])
    with subt[0]:
        st.info('패턴 인텔리전스 모드: 전체 과거패턴 + 최근 회차 변화 + 연속수 주기 + 유사상태 다음회차 흐름을 종합해 우선순위 5조합만 제시합니다.')
        if st.button('🎯 이번 회차 우선순위 5조합 만들기',type='primary',use_container_width=True):
            if not status.get('complete_from_draw1'):
                st.error('전체 과거회차 데이터가 아직 복구되지 않았습니다. 21개 내장 Seed만으로는 패턴이 왜곡될 수 있어 추천을 중단합니다. 사이드바의 「지금 최신 데이터 확인」으로 전체 회차를 먼저 복구해 주세요.')
            else:
                with st.spinner('과거 전체패턴과 최근 회차 변화까지 종합 분석하는 중...'):
                    st.session_state['md_games']=adaptive_priority_five(df,ns,pool_size=20,max_overlap=3)
                    st.session_state['md_recommendation_record']={
                        'target_draw':int(latest.draw_no)+1,
                        'created_from_draw':int(latest.draw_no),
                        'games':[list(map(int,c)) for c in st.session_state['md_games'].combo.tolist()],
                        'mode':'V5_6_FINAL_BUGFIX_PRIORITY5'
                    }
        games=st.session_state.get('md_games')
        _rec_basis=st.session_state.get('md_recommendation_record') or {}
        if games is not None and len(games) and int(_rec_basis.get('created_from_draw',-1))!=int(latest.draw_no):
            st.session_state.pop('md_games',None)
            st.session_state.pop('md_recommendation_record',None)
            games=None
            st.info('새 당첨회차가 반영되어 이전 추천은 자동 폐기했습니다. 이번 회차 기준으로 다시 생성해 주세요.')
        if games is not None and len(games):
            for i,row in games.iterrows():
                _scenario=str(row.get('scenario',f'{i+1}순위'))
                _reason=str(row.get('reason','전체 패턴 종합'))
                st.markdown(
                    f'<div class="game-card"><div class="game-title">{int(row.get("rank",i+1))}순위 · {_scenario} '
                    f'<span class="md-score">· 종합평가 {float(row.get("priority_score",0)):.1f}</span></div>'
                    f'{balls_html(row.combo)}'
                    f'<div class="small-note">{_reason}</div></div>',
                    unsafe_allow_html=True
                )
            st.caption(f"분석 후보 조합 수: {int(games.attrs.get('evaluated_combinations',0)):,}개 · 최종 제안은 5조합")
            st.caption('※ 순위는 과거 패턴을 참고한 프로그램 내부 우선순위이며 실제 당첨확률 순위가 아닙니다.')
        else: st.info('「이번 회차 우선순위 5조합 만들기」를 누르세요.')
    with subt[1]:
        view=ns[['number','count_all','count_20','count_50','count_100','count_300','current_gap','mean_gap','z_score']].copy(); view.columns=['번호','전체','최근20','최근50','최근100','최근300','현재 미출현','평균 간격','Z-score']; st.dataframe(view,use_container_width=True,hide_index=True); st.caption('Hot/Cold와 Gap은 과거 상태를 설명할 뿐 “나올 차례”를 의미하지 않습니다.')
    with subt[2]:
        sims=st.select_slider('가상 추첨 횟수',[10000,50000,100000,500000],value=100000)
        if st.button('🎲 시뮬레이션 실행',use_container_width=True):
            if not status.get('complete_from_draw1'):
                st.error('전체 과거회차 복구 후 실행해 주세요.')
            else:
                games=st.session_state.get('md_games'); games=games if games is not None and len(games) else adaptive_priority_five(df,ns,pool_size=20,max_overlap=3)
                with st.spinner(f'{sims:,}회 가상 추첨 중...'): r=monte_carlo(games.combo.tolist(),sims)
                c=st.columns(3); c[0].metric('가상 추첨',f"{r['simulations']:,}회"); c[1].metric('1회 이상 당첨',pct(r['any_prize_probability'],3)); c[2].metric('평균 당첨 티켓',f"{r['mean_winning_tickets']:.4f}")
                labels={'1st':'1등','2nd':'2등','3rd':'3등','4th':'4등','5th':'5등','none':'미당첨'}; st.dataframe(pd.DataFrame([{'최고 결과':labels[k],'확률':pct(v,4)} for k,v in r['best_rank_probability'].items()]),use_container_width=True,hide_index=True)
with tabs[2]:
    st.info('다중 비교 착시를 줄이기 위해 Benjamini–Hochberg FDR 보정을 사용합니다.')
    if st.button('🔬 전체 FDR 검정 실행',use_container_width=True):
        with st.spinner('검정 중...'): f=fdr_summary(df)
        c=st.columns(4); c[0].metric('Pair 검사',f"{f.get('pair_tests',0):,}"); c[1].metric('Pair 유의',f"{f.get('pair_fdr_significant',0):,}"); c[2].metric('Triple 검사',f"{f.get('triple_tests',0):,}"); c[3].metric('Triple 유의',f"{f.get('triple_fdr_significant',0):,}")
    ps=pair_stats(df,with_tests=True).head(50).copy(); ps['번호쌍']=ps.apply(lambda r:f"{int(r.a):02d}-{int(r.b):02d}",axis=1); st.dataframe(ps[['번호쌍','count','expected','lift','fdr_q_value']].rename(columns={'count':'출현','expected':'기대','lift':'배율','fdr_q_value':'FDR q'}),use_container_width=True,hide_index=True)
    ts=triple_stats(df,min_count=2,with_tests=True).head(50).copy(); ts['번호 3개']=ts.apply(lambda r:f"{int(r.a):02d}-{int(r.b):02d}-{int(r.c):02d}",axis=1); st.dataframe(ts[['번호 3개','count','expected','fdr_q_value']].rename(columns={'count':'출현','expected':'기대','fdr_q_value':'FDR q'}),use_container_width=True,hide_index=True)
with tabs[3]:
    btabs=st.tabs(['일반 백테스트','고급 검증','ROI'])
    with btabs[0]:
        tests=st.slider('최근 테스트 회차',10,150,30,10,key='bt_tests')
        if st.button('📈 백테스트 실행',use_container_width=True):
            with st.spinner('검증 중...'): st.session_state['last_bt']=cached_mobile_backtest(int(latest.draw_no),tests)
        bt=st.session_state.get('last_bt');
        if bt is not None and len(bt): render_backtest_summary(summarize_backtest(bt)); st.caption('우위 근거가 없으면 랜덤보다 낫다고 해석하지 않습니다.')
    with btabs[1]:
        mode=st.radio('검증 방식',['Nested Walk-forward','Strategy Tournament'],horizontal=True)
        if mode=='Nested Walk-forward':
            nt=st.slider('Outer 테스트 회차',5,40,12,key='nested_tests')
            if st.button('🧪 Nested 검증 실행',use_container_width=True):
                with st.spinner('검증 중...'): bt=nested_walk_forward(df,start_train=360,max_tests=nt,inner_draws=16,sample_combos=1000,random_reps=60)
                render_backtest_summary(summarize_backtest(bt)); st.dataframe(bt,use_container_width=True,hide_index=True)
        elif st.button('🏁 전략 토너먼트 실행',use_container_width=True):
            with st.spinner('전략 비교 중...'): tour=strategy_tournament(df,start_train=300,max_tests=30,sample_combos=1400)
            st.dataframe(tour,use_container_width=True,hide_index=True)
    with btabs[2]:
        if status.get('has_prize_data'):
            st.info('실제 과거 등위별 당첨금을 이용한 연구용 백테스트입니다. 미래 수익을 보장하지 않습니다.')
            if st.button('💰 ROI 백테스트 실행',use_container_width=True):
                with st.spinner('계산 중...'): bt=walk_forward(df,start_train=300,max_tests=50,sample_combos=1800,random_reps=80)
                render_backtest_summary(summarize_backtest(bt))
        else: st.warning('현재 데이터에 등위별 당첨금 필드가 없습니다.')
        probs=theoretical_single_game(); labels={'1st':'1등','2nd':'2등','3rd':'3등','4th':'4등','5th':'5등'}; st.dataframe(pd.DataFrame([{'등위':labels[k],'확률':pct(v,6),'약 1 / N':f"1 / {round(1/v):,}"} for k,v in probs.items()]),use_container_width=True,hide_index=True)
with tabs[4]:
    st.subheader('AI 진단 · 시간순 검증'); c1,c2=st.columns(2)
    if c1.button('시간순 Holdout',use_container_width=True):
        r=cached_mobile_ml_holdout(int(latest.draw_no))
        if r.get('available'): c=st.columns(3); c[0].metric('AUC',f"{r['roc_auc_out_of_sample']:.3f}"); c[1].metric('Model Log-loss',f"{r['log_loss_out_of_sample']:.4f}"); c[2].metric('기본보다 우수','예' if r['beats_constant_logloss'] else '아니오')
    if c2.button('완전 Walk-forward',use_container_width=True):
        ml_mode=st.radio('AI 검증 속도',['빠른 진단 (10회)','정밀 진단 (30회)'],horizontal=True,key='ml_speed_mobile')
        ml_tests=10 if ml_mode.startswith('빠른') else 30
        with st.spinner(f'회차별 재학습 중... ({ml_tests}회)'): r=cached_mobile_ml_walk_forward(int(latest.draw_no),ml_tests)
        if r.get('available'): rows=r.pop('rows',[]); c=st.columns(3); c[0].metric('테스트',r['tests']); c[1].metric('평균 AUC',f"{r['mean_auc']:.3f}"); c[2].metric('평균 Top6 적중',f"{r['mean_top6_hits']:.2f}개"); st.caption(f"평균 Log-loss {r['mean_log_loss']:.4f} · 기본 {r['mean_baseline_log_loss']:.4f}")
    st.markdown('---'); st.markdown('**사용 원칙**\n- AI가 기본 확률보다 실제로 좋아지는지 검증하는 연구 기능입니다.\n- 결과가 좋지 않으면 AI 예측 신호로 사용하지 않습니다.\n- MD Score는 당첨확률이 아닙니다.')

with tabs[5]:
    st.subheader('추천번호 ↔ 실제 당첨번호 · 상관/회귀 오차 진단')
    st.info('과거 각 회차 직전 데이터만으로 추천을 다시 생성한 뒤 실제 당첨번호와 비교합니다. 상관계수와 회귀계수는 원인 진단용이며 당첨확률 자체를 의미하지 않습니다.')

    dc1,dc2=st.columns(2)
    diag_tests=dc1.select_slider('진단 회차',['빠른 10회','표준 20회','정밀 30회'],value='표준 20회')
    diag_games=dc2.select_slider('회차당 추천 게임',[5,7,10],value=5)
    _dt=10 if diag_tests.startswith('빠른') else 20 if diag_tests.startswith('표준') else 30
    _samples=500 if _dt==10 else 800 if _dt==20 else 1000

    if st.button('🔎 상관·회귀 오차 진단 실행',use_container_width=True,type='primary'):
        with st.spinner(f'{_dt}개 과거 회차를 시간순으로 재생성·비교하는 중...'):
            st.session_state['corr_reg_diag']=cached_recommendation_diagnostics(int(latest.draw_no),_dt,diag_games,_samples)

    dr=st.session_state.get('corr_reg_diag')
    if dr and dr.get('available'):
        c=st.columns(4)
        _nc=dr.get('number_exposure_vs_win_corr')
        c[0].metric('진단 회차',f"{dr.get('tests',0)}회")
        c[1].metric('추천노출↔당첨 상관','-' if pd.isna(_nc) else f"{_nc:+.3f}")
        c[2].metric('평균 최고 적중',f"{dr.get('mean_best_hits',0):.2f}개")
        c[3].metric('평균 총 적중',f"{dr.get('mean_total_hits',0):.2f}개")

        if pd.notna(_nc):
            if abs(_nc)<.10:
                st.warning('추천 노출과 실제 당첨의 상관이 매우 약합니다. 현재 자료만으로 예측 우위를 주장할 근거가 부족합니다.')
            elif _nc>0:
                st.success('양(+)의 상관이 관찰됐지만, 표본 밖 Walk-forward와 랜덤 기준을 함께 통과해야 신호로 취급할 수 있습니다.')
            else:
                st.warning('음(-)의 상관이 관찰됐습니다. 현재 추천 가중치를 강화하면 안 됩니다.')

        st.markdown('#### 원인 분석 · 실제 구조와 추천 구조의 차이')
        mc=dr.get('mismatch_correlations',{})
        _names={'abs_gap_sum':'번호합 차이','abs_gap_odd':'홀짝 차이','abs_gap_low':'저·고번호 차이','abs_gap_range':'번호범위 차이','abs_gap_buckets':'구간분산 차이'}
        mdf=pd.DataFrame([{'요인':_names.get(k,k),'적중과 상관':v} for k,v in mc.items() if pd.notna(v)])
        if len(mdf):
            mdf['적중과 상관']=mdf['적중과 상관'].map(lambda x:f"{x:+.3f}")
            st.dataframe(mdf,use_container_width=True,hide_index=True)

        mr=dr.get('mismatch_regression',{})
        pr=dr.get('pre_regression',{})
        rc=st.columns(2)
        rc[0].metric('구조차이 회귀 R²','-' if not mr.get('available') else f"{mr.get('r2',0):.3f}")
        rc[1].metric('사전점수 회귀 R²','-' if not pr.get('available') else f"{pr.get('r2',0):.3f}")
        st.caption('R²가 낮으면 현재 변수들이 적중 차이를 충분히 설명하지 못한다는 뜻입니다. 높은 R²도 미래 예측력을 자동으로 의미하지 않습니다.')

        st.markdown('#### 프로그램이 제시하는 원인과 대책')
        for x in dr.get('causes',[]):
            st.markdown(f"**• {x['factor']}** · 상관 {x['correlation']:+.3f}\n\n→ {x['action']}")
        weak=dr.get('weak_signals',[])
        if weak:
            st.markdown('**가중치 점검 필요 항목**')
            for x in weak[:4]:
                st.caption(f"• {x['factor']} ({x['correlation']:+.3f}) → {x['action']}")

        st.markdown('#### 회차별 진단 원자료')
        raw=dr.get('rows')
        if raw is not None and len(raw):
            show=raw[['draw_no','best_hits','total_hits','avg_md_score','abs_gap_sum','abs_gap_odd','abs_gap_low','abs_gap_range']].copy()
            show.columns=['회차','최고 적중','총 적중','평균 MD Score','번호합 차이','홀짝 차이','저·고 차이','범위 차이']
            st.dataframe(show.sort_values('회차',ascending=False),use_container_width=True,hide_index=True)

    rec=st.session_state.get('md_recommendation_record')
    if rec:
        td=int(rec.get('target_draw',0))
        if td<=int(latest.draw_no) and td in set(df.draw_no.astype(int)):
            rr=df[df.draw_no.astype(int)==td].iloc[-1]
            win={int(rr[f'n{i}']) for i in range(1,7)}
            hs=[len(set(g)&win) for g in rec.get('games',[])]
            st.markdown('#### 이번 세션에서 저장된 추천 ↔ 실제 결과')
            st.write(f"대상 {td}회 · 최고 적중 {max(hs) if hs else 0}개 · 전체 게임 적중 합 {sum(hs)}개")
        else:
            st.caption(f"현재 세션 추천 기록: {td}회 대상 · 실제 추첨 후 이 탭에서 바로 비교할 수 있습니다.")

    st.markdown('---')
    st.caption('해석 원칙: 상관관계는 인과관계가 아닙니다. 회귀분석은 과거 오차를 설명하는 도구이며, 가중치 변경은 반드시 Nested Walk-forward와 랜덤 기준 비교를 통과한 경우에만 적용합니다.')


st.caption('MD LOTTO 6/45 · v5.6 Final Bugfix · 모든 특정 6개 조합의 1등 확률은 동일합니다.')
