# MD LOTTO v5.8 INTEGRATED CONVERGENCE - VERIFIED
# Upload only this file and requirements.txt to GitHub/Streamlit Community Cloud.
import base64 as _b64, zlib as _zlib, json as _json, tempfile as _tempfile, sys as _sys
from pathlib import Path as _Path
_EMBEDDED = 'eNrNvWuT49aVIPhXYDlsEJkgks9UFatQO7JUbmtXD0+VPFYvi8FAkmAmlCRIAWQ+Kjsn5HaNw9NWr+Uea1rulhzqGfXY7fDGqi3ZsqM1X/xT9mNl1n/Y87hPAGRmyfLG+FFJAPee+zr33HPOPY+zZ2bj4XS+XM53hsMkTZbDYbA4fabnPDMcHsVZnszT4dAJHbcdNIKG+yB9xnd0lb1odLiM86WoMsnmM2c4nKyWqyyGaslsMc+WTpSm82W0BFD5g1S8y6J0PJ+px3Q1W5w6Ue6kC99ZwDf4Cf9bjB+kBDQfJYvTIAcouYS6l6TzGTYuithfAeBenA3pnSwwXyyTWfIwzmQh+WK4H81iVSxPZqspdVeWG02jPE8mp7LEcpUm6b78Ck/x8DhO9g+Wue989+6Lf/Gt14YvvfiNe8/d+8sHKf53HE+cWbQcHQxH81W6rI3ms725f5ykCMbrZTHMV+pM47SWx+Kr93X8KYt4Esowh57Fw1m8zJJRXqMnfxll+/HS35unqzx8ZZ7GfjY/ph9e70HqwH8OkmUe9q0uiFqeM5lnzshJUoeADbjCfLUMz9w9mF23N4tOagjA8932YrrK3V6+mtUO7oRtqnuAdcX3jvW9U/q+BDyYiu/45pxbSyYOdd5JAAHmSwe7LnqO/wFcOYTuy1VQfecRl0ZwC3vfdxeZWll3EGKT2VdCNwXQLtXIsAaB9nRT0BOYO7MfgL1jJ5pOaxMB8Sw5d6nq/DhIYFFOCFoioO3Htaa/63lG9/E/M5jNJk5m03db6djttWAyM/jbhklbHri9ju928W/3/Bbg/ynOP+w3G4jd60ILsvf4fUadXowDGEQa1bCnMF16BLN+Njh3oZOiqe1wMp1HSyzYLxQaeHYzPLVUC2aVf4gJH81zfNdsNBpbhMu4Gp74mM0T+FbjCnWjvLdjPHBbYj/Ae4X2TC4Y+2tZuu/TuvqAmsM5kKlptLDwfXQwz+M07AMuRMtlPFsA+ovJPD5IpjHtNS7k3SZQvMyi7O0WjKFhTPAoXK4W07iWw36Px9iBII9m+EYueWfXw2X3dIPbYdPCK8JQbrM3mqfLJF3FVgFjMGUETE9rij4wbTjxvDtmFcSOE92GV9EIfwmixSJOxwDHmm7+KGf8OJoeDgHkcZSNa+OJD4Q0Ww6XWZSkYbvR4PmHtYYP8SJs0kogMcZ38DKOx+Fup+vzLA2JpOVhF2bVF0uZxQsua65h2xd01FpNQMuc1hK2WzKCZqdJvhQzb/TLxwkaTzzqkuf166pPPYFYtFHHNEkClLHGPLbxJEim81G/B+WgRSSk8hW/YdITniWp3C8pUoSBVyYDz3qwmZkqi9IBU6xbTpqH5glVo8aNrTYbh/bhxCX8NBczz/hvT6/1xGuA/2xDx61ZNn6r+RZ/bVKIEzobix1SgU+zWVg4kGbjgJoPlnNaJM8i1XguweBh+4SMBcE9+lPDbm4h4Wg0sLdYZo9WPNsbw1/dIs7xUM+xgUtFipvtSTwvdHEdLSGMK3fXK4IdPyVcY7Y3g5/FURpOo9neOHIO41M/yrIe0+V0EeDHWv+E6Dh+hFdplHp610PpgQltEWejGBZsGodFIH0+2Ae3w9lM/taAYIQWoCweweE1zqLjYTp3exKTxQs41IEbFIyCgkYviVkQBzB9Y+6BP3aKHzviY+FUw7LENQyJe5GlmZFgUOZBDx9piqzT3294JbBisbC7Q5wWqImTw/33sz0YlygyTo7WFxuvhYzVeAbMejwFXNEs2SmV7BglNzQh5saoyFNTbsKYEau8NVOVzYkFHmqUGh7lQw3a7ekvqknck27PeDi3SAsxBMSrzIobNx4Fq8UYN9EZLS8zG7TskvGgdSeWgV4z80AvESy9I4bDL/NIVZPIYO1Z4ZbK0whwrYLYDpU6N/cMnFiSTMB47IMW+LIXomX0zQymHLdSrrh7YFJnES2HFKxqe0tJ2AQ9hhdh2JAyw5lLB5zba4jpBYmBTxsoGIiFuwM/q5DZC5ArRp5lOs/zuFTv9pX1lgmextyrOjZdZ0jcl3E8SvLkKA7xyzZ/Ae42VJIbyje5L4v5QdcLFkfRdBXjYOVrJ57msdMMGrfg1XQZ5SH30KIKdbureleY4oyYKtFfRbjEcjKV1KNnaumtJQSqfNVnVdlAQE0ThRiE083tGaRSzK1fpiPxySIeAftZ3bSmNRJCoelOddOdzU13rtF0Z3PT8N5crCGtIlIQ2k4ERsLlBdYzT3VtslOupJdsLYWqXI6DOEIsGtJfxES3R/joMqYCotBfkFoTfMJ/fTdP9lNiKoeLIaGq7MXCBh4fJeM4HcXD+WQYj/eh2N58Pq0tbgeNLnH02NQdbsGuCXw/lHbvniym8yxazrPTwHnOQTYRGKpkBKLoqYO9SCbwkC5BtM6hEH4AApOvpkspPCyy+XziwP9YHwPPMfC8S9xSi/lxnAWuFr8NQotEGaZ0NJ+uZqnJIMNHizDzmjIVNlcC3yhUUuUkGTdL8rsKpCmcPlkcTYEqCurOECpA1Evt75R7tKYVA50lspe7XH1kfAHI+hCpgi2/Sqw999bJxSkgIoDbKKztGsKaltJaHT9JU5A/kI+DbzcKskSzVRDVbhhSnSWyyfPpwTP431dXyzhzVulyvgK6PHaotVtOHI0OsOPwDRt08ngKM5E7QuxwVjkq1OYp4HYcZdMEdXTYPZJD62JoVDUPuKEvJBo+vVTIu+u0KBeizm8cmpq/mihpTavx+9py23qWZe1/riXqGewJSDrhAiW1dATI15c9l2MkSXcw8IHIzLN4SEqu8LVsFRsg9pahhXWodTTRDidcwPWsoRuKgi84DSZWGr+fUuClFey74tHSc2lOq8yaIvNBk9QYgIw7RIJaQ3E1HvVdRmrcjwQUOO75BI4idyAbS2EG3IEozbjBPIkqYb289YX5SFiDZbx/CqQXCsJnOO036XD0mrQbRTqw21i38S3y0G7YdOA+wKbNz5vWd3J6kYwO46VDKmgfD6Q6cHnTCA4m2Wc4ZAPnlbkaAuJ27iwPYqF4IXAWCdAVwzO9XO7LLzh70TSCIxi4FlspD1Kq/DLwHff+MluN8ISsAydwdFouncsClkDhvkIKnDqexdF0bV36Su08D2s0rkd4qxKXC47w61B8tdr5dpRAK8toL5kmy9N1DS2gFCqT9hDhxMEe7e+HZ4c9LST4JLgO4cCih4Jg3VAK/oZS5TfOiT4eknpdzbSG33efR4SI9uM6Um/A5D+tNQPwCwldQE0SwA7B8a2FHlTAD4wWAqONQLby5zozKjWJpt7Q1CheqUC8SlWItd7wa7jN/WMPq8dQPsalqhmbKlnGs7xWupggbdWXq2vcaje337ha4VhQrAmiy5cGXwnXqRz5MqXqGqxa8YgK+RDRCecHrwP6AoEG22GTHhUWwRulwOKCFkLxZ6F4ou9Cn0XvxW963zHei996AF91rA3TA1bdZOHzEfwAVkjdJ05W06nT6dYZB4Bzn09vAQFlEM58742YWfpxBv/mgrFK5mlgqP3nR9daYYQ9zKFQWNLcb1ruTvvKxT5TNBSFT9iLEqOZOuIbRb+IytErIolIFMpnMwzJCwWSXIEcUPQK1CiSsP8FsKRaRU7TffNmExmOWX5txTgW/tOV1qZOWMxbFYW+avIKymhbAT2jEczyAV2kVcxtubaY6srqaurL1cSnymqd9dU61dUsYUSfEESTI9LO7+9LCmweFLhZanq+fFpZg+ejfUN8kNsjYPL0M+qwkoQ18NZc7yz9kvIlFnXtecWSlrY+MpT1ncIHMQXnVzGjAV6Wso4kr/WNXlb2auBH+QiGDLQv/GY0zWMvyOI8XrL0URtn84UUQSwLlDE0+vTWJ2/k89R3gJJB94E1fRNITtz2Hby4RY4dfiWzWFh7LKLlwTTZk+C+DY8Kjm2pIk1b4jdXuDaivnwMonG0AAFYmah867XXvv0cvxNFV9kUWmoHq2UyheEvs1NZ9h4+IHv/jefu3x0+/+pL33n5lftO6PTVxYzPv1A9A7/TJv7Twn/a+E8H/+niP7vwD10/Ibn59r0X/08LXKUxg74bsowg4Gxyj0lgyenZA4B3X3/t3nNW/3iZ82ga58Nohow/dCBagewk6sJjHs+SYeHdLEpXUFG+ANgaqjkJD9JXv/nNF59/8bmXhv/7/VdfGX7n3ktYpMbY6R4sl4u8t7NzfHwcjA8QZ+LsFM6D4DDbmS5BptnhE/Pb+fIlfHwxncyD8fx/y7PRwUvLu4t8HJ6JKYYR/wlAX4mPN8EFvH75xXv3Xr03fO6ll3AQaHMl28ln88Ob3WA/WR6s9oJkvsO4z+q+fCeaTgPEaFfBeOm51+7ef+0pweARkC8lJDWr9+7e/85LJVizNQNnYK62exrmcY5WZDXPqd/Rm+E+vxXEEAT5woeaJi/ZaUjoXyNUArkTGBpAitESf2ZxNMa/eGEyn0yGk2gErFQYPFuhQED+GUgZYPMoRk4grHVaN/0uCLjdRgv+34b/dzwfrX3mxyDGwyF5MB/nIezNh3GKNhd99y/uvuYqgp8HhNA1NSuwJ4xdXcNTFAeAsikNBA8Yq9K16sjGUFENe0ErYb+Tg/z53D6I927PfXn+MJlOo51u0HBqL79QfwkX1zlqo1Y4jgDtbuGdMCwucJkroK/uWhWL+9xoFC8QJhxDU2BLkXjuEM1cxifLncUUmcetnS23cAjketmB7ifUy/GkZx0OPuFAkiEzCcz9/mq+ynsOKscF3Uc0MSsIFJklOeoIw/5I23tZxJBMbFDvDR9AwBL664FScQsAwA1FSR47/wEPprtZNs+AqL3M3xyp9HbORGmgagzgMI4XodnettkRi45u20RQmv6U+oSXUuNJHyEP4NPiVOK8AmtS92tRdFtb3x8NUM0HZJUEwmRU45d+jMPOQ5dmwvWCKF+eLuIaiKbFHmwYWK9s3YSaeDWF1+nAaI4XNnKOyRBMn2KyLj7geVwrfl8DBnpTLBkkeRrVYKApTHIFBrgvpoSwjqrjjOMlX3lVQYUVGQTjFW+OeLwJ8guylCNqliALXYKfySkEZiRDFsriFWEGgbkk64vNKgPgwPM0FJZqWKssPSEpy1MPxOxdB9lU2DRo4di8HZ7cBtlPn/dQqKgCLW8eOXfCWFWY3gJXxMo6h02llMHIOewu7JbaWmoO/LSgvUiBISZECqIlKkt8OfAwNTTR2sBKmFdZ48XBwcDoCw0OWhLGpji+3qYRcbl14zDQNqQ7KIPfVWiyno2VBpslakjXg7hMANScfnl7ZOqrsEvYtmgumCV0zVl6DWKG5203PXtuzCJSOP5KKNspCtZMEcXNhsAvxCRZ3qvjkwGzZDu1nvDSBAvE0dSX2+r32o2Bmm37EowPGxQCcJL5gC8dOXSkoKZejGgcGqeTh9oUOfW0Npa5xfg6KzCumv9xxexbbY1Lcx+qubfGytZXOd/ac6eAS3GhLZogfl/sgx4AG1CQXbi9Hi7yGpUQqMOVEBxXj0DcaesXxTtQKItqo2U8RPGGmmqKSgIwonpV78OwSd82wGZ2lQl8D8RkCQNf8AgCWuLrTcVBlAsLKUQmEHSBHvKxLU+0NYci2rArXnec7Nfme2/4h/FpbtjtJIDMgJvpKKaviIomWpGC3T8i8r/3RoWeQIAhJTyCltY/RwX78JA6cMTNl6pPLPN6AWLCxYAfLnUTcbLYTdnJ3pfWsnjCL8ZELqIsR9uJSTJKQApE3hNtx6fzaNzD6fOlJAFsOq46IvBfIQw2HK7fMbc7fOf+CQj+mTslEYyE5uNXpPBMPzJgzvEDyUZUSDK5iE1lOPcm07+cKUgvsPiN0MRPgiN+xwBOlJdA+fQqQN2Dd9QZ+kq/pstvWC8VAOYLzGsJmx0wVuqo0M4E+7x8ZU7C/IR7qp+W301S9XQsfxd0sUfWylJnpO4Kt/WR51nUlNgR4DqMTuXxm6VJxY6AMEkdgAFT4y8lpDoSTAbfveVyfl+Z409xfhT7aKA1NOYDqfB6Bjt1Yug3sjiYwEmNmz9zHzwYb7s+VCECAjwEl0YmYtDv7RrK1+LuwWZ496xpBwoYINDYDc8/mEqeRsJYG8ErSyIvQ8yq8awcaeSLNfNe5lS/k+arxYLOdUfuPAd1KihBLuYgADv5QbRQfDYNrcxnWoeWMhnGB8/UUTHJxsuefq/ZGPhbW2eCu+ul1ewgtgEM4bncAWzERhyfQYMnMdqYKcqBDdZET7CCj5IEMA/4O2y2bEoh5Am0J4E9qRQXt7Ts3XfvxZM4izPgQa+hBlLaELk5UcM4pRVLnbLeyrpDPC1y3mFOps0SRADwZtFSDi5UBtlihKH4iyrlgFYbNR+SRyqyZrxolXQ3I5VQzfNlCyZDhIoC5y79QYe5KHcAf3keJSGYuGeyz8j7x5qVIxS8t0qxpwIJX5WIR3hOi+lMomQK7KjjbrvOXzlu8MYceARugz3jxKExS/DdEESn2gmdEvbqmviKqCOs5wnLTvqKegy0Nr9o935iiH9lZMavJG0KjDZm+AsiN1rq4xM3KG6tx8lRgniZh+wN4KoXrof7fe1ZsOvZIntym6x0VPWSqGd6g5HUpYr2k3pzYBjau3xv0bcVwtUVpEZXnwxVOmJalB4Brfo8kIOv+CYAH49kGdknvAVMUtJm8VSdnaul7ts66UF4POLK+FoOr0JRrQuqb6p0UYWtivKHgkQDVRiXlVST5HTPq7cjs7y1EgmTzI9lgfMNKFqPJxO8PuCKvKck2FOH7hzQtEZRe2FAuoj2Y8vGxqZGmUEbaUAVuuKnpkLXOJBrcCKfNf0unO8P8q0n//C262cBaiQ98+aUZxMFADqUSAcAPzTrL2h9gXT1SiAkS6pPFUFgqpaha9Oa0hSVFPPXnKBbijQb1E1SZK947IkyOF1m79oN6F2FTnVdL8UVxLW7KFi3UPbLwmsla1tXhH2LWhsrLmABfS1rRqTqRLuFzo/ZhgCv/GoZjJL8NHtWB9AKBht/DUYBfZ4tpBKHuA8pJPreNvt4XkPF5m3XTH2Tb3Qpi9GqEs6rWnyC9trpfs/SfmfxbL6MrXfQa2PzCpUVUmYJwZNKOnzJAKTTuMBlrdBQdQKtddLKKFhAXVRAWlMQiOVsnoYx+zjDv3h1yaYlMHB6KUUYWPl+8UDl6jiawiLFAVo+pQNgR4vLJ79othhAVyrocO6cfL7KRjHqpegS2ZmnpiENqUyA3QAQ/V7LUCDhyUeLxwNjXcdtfBVbr6qUufdoymTLwGTPp8AVAg2NUgc6D80Km1fcthM2ah7Pj9P9DLjHwDXwBAhwMjkdLoG1gQNiqTlW1F5ZGEPGkryNC3JtUY11EI8O43HYuEUcE0wps7KKqzUME1izofRPULyGihc2zBQqJk/ppTbypdDxsIrpZozwhA9tX7UWhvxlIO1oS+qCIl7Mj8vIAlN0P8ZLshq0ioslh2yKn2lRAymmyHLNvi4PmxaYVynmqFEL4G5P/PD1J4mjaEIhO1rUQKnChBoJAmL1GkMjdRgSAVnfM+BzZ90e/+332gNTKxUt57NkNDzOkiVQ0/yohGJo4tBDwwabFOHrACSCOF0Gs8NxAlSUHpgO+0RqhvNDU6E9GfvL2SKUhhRQLcfftQVsh+QkJIj4Ztsdgmi9muBLN4Aqrg/wQ6LUulXEnnkejKbzPK5Nxl4VM2LuAbwtwvEBPJ+t1ulK0cfvQxaXQvdrf1n/2qz+tbHLwLMYJBOQ2bEONi0HAozidHpqc8xQnHpHI8+xCl5P5MEqnSbpIT3rac+jow2zDSP9K3PGqxbJxwI0HzoACJ6N9LkIxTreK45evChXFb1iP9kE5npdFcgR6t4BB3BtPAHiFMMyROPxEEhnchSPh/gCMRqXUCwx4NAiILrISFIjJAnGewYVxxdiJWAZ8EmsgxQAoLq07QmEyQCtEe5wfDZ1m9AFxB4oXhPadh+L+MlkyG2ErsAU10Qtz7SyTFPoTzxawUS6z9+7C6ye851XXvz337nrvPjKC3dfx0u+obwEfPUVPqGk+O6p26QCSpZW6jQdSdaL/7BC9M+yVGvWwdXLFDDCIhdeQ+YvGK9mC9kzP05ztMWK8lGSiL2IkwdnWcuHEUUgbOCe96DgaE62X+5qOanfqNqbxkTQJjAnojh445Q0B29xWCbySGJ+rimMeEVjwvagEd5DNNRSf701UoUBWS0jdlzwCXbPfSGo2dpsXzIL+qSxWAJiW/vWvsXxDyxp8F48gR12wObEonFAqEk8PQ0eCDbyqBvsEgNL0uF0vp+MBIy68xqIiYvV3jQZOXur6aHD3LszQsYn2nf24gNYWBIm0/gYZU1ih6anjjzNpPOWgPdKfIS+YJI3ciKqlwkuChkS540VgNmLR9EKuDCEzG26uWNYKiETBkgAR42EfC/eWyVT7ovBD+7Nx4bEa4wBrxKwBTqgkWHTXZCbGy/j4UTI8qXPt1IwMltwBh5hMYcFYRc2ZLH243SVpDC98uLUmgBTuLa3J3kgABdnCixBCkLS8mHoPpcn0c59kMWU8kDy+6E+GEjk1djNgq8lfIkbLcuepfJwLXN74tZtFi+jsEoo9oqXxsZHYvwMAKY2bT0/1tsEUcroBjNqqkrCtToUo0Fab7OLck7X3IdqsaygUmDtHDcIKyiMKdlw0uq2X+iNb3aB2jkx71UGJYMG3UqleYatUn0e0GVsVTP1QSyUlLs/hEGTebJ+ZcyZ8Gaxi9MEMWR5/0AzhJKFXnrPt2tZ7bNMGpa0GV6pCP/p8x+5UrdD7phtT2XUKgi/G3UM2mPjHhGIaIr0/1RxVWNBKWhfA6E6nQsKaBLIvRhwIDaBifhQZCkTL4/n2SHRkzwAGpvQzU2c5+jEDqCPD+LUIH1IanPTsWOV4eFNS0UyrTUZBbQV4j4vSaNkE6SxmiichuzcFqtdpASEs0gmQ1m3X9o6dwxA3tdLn+V6eeUFM7qmW/Iqgp4pp2qinKHR4HazXNrotf65xnSnXFujyZBqmzDkrBvGdEqA3tBrAUcblNjj8UlZUdFMlUmPaY9X7Glot9irNv4U28RwDhYbRfdgs19wBbDr77kqINfCcXu7fjNmdRCcvbw3AefgwJbncDRBN3Sxo7YZI+rEcUjeJ7BNG6/eC5bnh2kvIdl9pT600FN41sAiViyH6Qey4VLTK+8ZrFkFcN3aln03rl7jP4GeGhpOSZNQxVqxtmQK9JWwue47rf1Xwsol2Z/DJCdpuBZuJV20D3MF56npaxlOSZlYXqCJ1C9K/jxJpQFVz2kGwRkP9FwRD99xq6BAl50zMf5zqCaGcF4oXDh4i3proar2ysxVuF55KdCABJSwUmwpWCCKb/1KXdngauNTdV/McgbbqiudcM85Uy08eKaiiQfPsGLYsEeRahu5OYwOs7Rpupmz5u7Q7ZH47KJoBxQ2WvKNsODlS6ZrrD92e67gcEgo2zbOJngwO0u2kHtZgnFkSmZwVInZDAxZoxnJNQZzPC63J0LRFU0CTT7V7dls6zqNpTTFU3yd2ytyuHbVra2CyabANX9rS1bUFc5LN3NiabhuteBNWtyT3no2p+gHXbm0anlZd7F2fV1SvPLL+KQqFIxLlwHDUYRRUYSNIeFMaSpUD20g55UGG+V7H2tW1KaRuoc1arfifVTFXSGJzmiZvpzPp8qHzbhSz7U1tH0vge3Y1w/DL9HWfT9aQNm9ekTfI38PSzxMFmxRgf/0m72BeUO8t8IgFFAJ4/ZMgQdNb4cHib4X4WtjfJzO/QNqsQ+tNRueX2s2/Rb+bTX9Nv5tN/0O/u3A3643MG3CyJcRWkm/1mzYwNG8CCaWYhI3zW6bs1kTAPwWnTBRGO6ZDrgjst04i/byWlTf89ZCoVloeedevWtrO00fUwyhgJ2hkfvufDxmWi3efq1VmBzA96M4LZQJw0ax2FoHo+n82Kp9O2yV2zhI9g+sUnfCVrtUipCBg1TTmzqe7lc0P0JjttEK/eaH6HcuQlYDEqHd8UY8IsNrdF8FvONaiIDeTnd9a2hlTaWxj1QaCAms/5BXWPWA/HujkQwrFo3WgiRzIkbj4Vmy3Tx3e0fCrOjINisSuO6dl911JROIu7DaR8FmDAlpgDOMgNKETa+gzwRWBagycLZA8hU3UFBu4kSk8TErLtnHVloodK+rxzStWow2HfaJqzBpkZo5peV8Hu/TcnHYMhuONVJHBpvIRYxo9gGBDgspgkisEA2eS0+l9L6zSqMjOLMx8ko9jU+WdTKzAWjjhIPIoyYnrU9gVNMr1H/iYndiavPEJTsd8KGIHrLGUH9iS/dA7GMdPpeOqFAzpoWIAWJxLDJ8sqxucLtZarK50XRxflx5RQwNlGxMCpfLqSFj2AYkAHRQIfyQ60saqyBNUkz6SgitVUhFe1kcHdqvYf6N/TGe+KiDu1IiglrmuWd/pKWQFBc6cqUNpV2d1464iwJgo/vJhJvpVTCzMIiFTQHgjRkuSfOwNkPJf+VbEp2FQe/VWGgGMaKeDYUfCz34rkkzBANFf7jaecHTfzZ9ej9/I62ETCRxOI2jLA0WySKeJmksa8+iQzgLxMti2SxeZPNRzOoDUeH+En3/s/F9mBflwC9rIJAoG87m43gqK7w036cAjvfi/YyNrgqVREwOWX463x9ifEgfts9oGK1GQ4wNE18j28WD9Jt3n3vtO/fu3g/77kOu5vquVD3gWeTrQww+4Bk7bDXUz67+2Ww00PdeWBJIlnGIdscTSSuKEYrwJt7SqPFXqVB7PUzzvuyhrfh7va/7NQhfD+RDMEmm0zSqPRt0bSx+XTiXAggK1qHuyekOCI7WNJ4WQ581uw0ftuEwGZ/w/ZoYFTPnVuR5WUziNaC4eFXWcIsPKmyUHCya4JzSv7RfknHBXYOjSJXDTwl4BaNdq6+lNAECmFWo6KqDt+9WAQpDZToz5JV1CotvBLeqcPhZ18sKAlzuC3WvdNfwtJGzNIDXtRotMinv6WmYLoKHcTbPa52uP0a9Lb6Bhm5YxfrwEncdCis1ITdzadTy1psD057oVLZ2emoAkWsfAIOAH2kEW52ufSf9etkKFZrG64LTWq1BqCU3jgesKHyLsiw6rfUH9oO1R+DDESDW6LD2OpXigy1O8aA65Xo515Sd1OlmiIIp2UzZ1hq0smYTwprnlwkdMRc4eZgBwn8+DLp+Pp8ewbM73Zvs5662byHcH8ZIOfggLW1disWGT9oZFaGSBmKSRWShGAatruz0Ko9VLLZ6rVx722jA6w3W8MLG6XZnMwymCNDiJsfffBkizTD3O56iXV5jDM+ws9OWNITpkjROeN0/9RUlMckc1ILJKlAz+rfghIWGMsmbK1x973ZL+Qip1woN4KsRaVxxuUIdIvrDlcKK6rcckLFCftvH4TV96cHKL72tWrNuLRxgNWwneRVNYfQEtNvhCDPN8K2ueHdntBJ0gvA0lOgKx8Wy9nqfAAz8U/HDk/w27oEpSHZUOhBhkTFa516EtaAFdOHwmwO/Gdef9Zt1/KOMXXMaK7AEMM+13R0gHDighVys6VSEjZLnd+2UQQIDBjOyt/47gvaK1oXGpDN7xhsEVSbMh9GzCrfMGj79MV4X+NiVTAVGMZ5PhhzgTcYjtjgOcwBl7SMPoghmOvVdHA9SiKEsBNwkvC9DIAAqKrishkDqewQIJU+8UkD3uuVQ1JCOxNPbUIg9wIqJa4azaVXcUyvcqdrIx7BTQU7pdBtfMO/MFwsuLK4tcXs0fChZL3SobpInu6oiaxoOnsfbzcFG2mNcg+JmkpF6YeMVv4uuVRAqTNyjYezstExJzKZXimYV6RU26hsNKaZMA95AzCoJ2lhRrYpkNRUkwjeP6JMCj4P9E1yO7tHAq2ZMdGGj7LU5lNPlBk4E2MflU3EgmykcCJ/riNs6AqfYlOK9ZME/rnISdKaYNeosV9OHImVcVtAcXa+CwJQBMFVdCwOo3Bqit7nt5XyxO8QcdjxyXiFYF5R74DDo13d7g4Egvec2k0fXs2tPVd8IcMuEvC/D+cLRoZm8rK/nbWCkhoMqAzpn7LLluSpVuvLk0ekz6JJYyJClyZ9WZVtQmSDWLtre5noV54NIBEDHhLeuMh8eqlUjkgYfHd6a85EaNbBDRYHM+oQ0pemrhmDgSRmO/ng1NMYF/LeoGFFpLb9oFk7UzGJQw+tc8VQGPhQaCRG6tlyPt5TPgoMoRiYCIAxV6jNkMNilEVFsBE2Sdm2IcWprpsbBp6C1rcYahcS64FpX6T3k7zbqQIrhrkSkMYx0leYY6KohnZphxGEthVa1vmUHn6uUGUymMdxcFjY9eYiixRnHbKNUjzI1AgVGh+WZAWuMWO1EcE7DN4CJKwGzS+YtQhvkPHhmDOffM4Gckz7elRzKmLuDsFaHTgn1UIAXSR4moTisLUZLZhe2gnbX2XZwKHJOSiWa3bWB+o2a7aqaDafOswU7cK/W9Nb0obWpBWgfZYiaaqlbbKiOs0yQt1oF7hoqpVM8S4GrQwzyrQnyAp7HNQZdSkTWeMnRkWuInnb4ZD/TF84cxBA3HEUlJmkIa2D6SO3agIVu21GXlZU69cC65BNO7RKMlDHjOA0xJJNXzHyJX7zbBej4MojG49q6VJc0Lsxxac8idYcgGntVBFQ2gjBjI2oOsgQA5ty5W86bq2isHug2zOy22rCiowafg0VlNMSqCRl5fovSVHF7VxRte7IvVxTslKQ0Zj/lTR4tKf6EI1J8ET3gb+JBf6VG+Rv9NONZFAJ3y1wdKnR3s2HE7W4V0ze0MaXiuvwNVbk2+WbqLzKoccrB4R19vsgrNHQGIHN4FE72Y+flFyhuecyJaTWlFvkecmcc5yMYNF64IhnD+jkaHGHaBwAgZPjohNpBSpbto/+VEed84rTrpOLsyEjoQDQAS3If8RoIZYLkUBjdC7UJVgaKWIfWYUsbsdKB6hxIt81ZDP2WOVSn0AGyTy1f01VH5EaExdCVxcMp91FqUguDHLTCbX24qdUkIyoWSUUQTCHayBQqd8Juo2hZptrMw2sTIVFziabd5bPYxC5GYEFJcHHHYb90pNdGPsCSiGRkYtZ9G5gg6FoA81fKPJcnvZM+ZnjiO4qBn8WUAMMUV7/q/B9xDAecs5fNozGQxgXgJQjS8AsziBzBEcvQKXq7DoDPd8GwheCo5NiejEtibfMD6ApFgeWu9Xu4YkQd6dkjORcTAfNG22p1G540IzHyCyPla0vihQ8d86ElH7J4xmJ9qBq22BImzqqUigFoJSk2aB+F+U5o697iB0DvEIS55g3xTC4ath0imwhQgmvTSEC1WjSKkmmPKZoFYZGLssWI6fOorPeXaYpHufN1h5IU63pXZCteY2xdSv6w4Cm1SPOIyfyiXfWJyPqiU/WpU7w/TuPjFilEFq06LR+m6o2P2/yuTe/a/K7D7zr0rlOAo5M8OEApsEXMfKjIJCEq3dzmDl4U1jG3XFC4+Ybl7ASNLWwKGJ1m0MWfbeR5WvSzhT8b7S2dutvYSOWlAXh3JJ5UXYNLFIL/35LYlZioVMM2fewD/tOx1TBcQUewKtyqkws4pkpSqBYs5osa16KwiJWYZhz1f65Vp1WW5/2iJbZtW71py12t3nRsXUjfhdkQJ//AVy/kgW+84lN+EKopLcBRTJM6qKAwhaOrydXxW+Tnb2bxRu94bXlnu3nx1rKU/2hiUSImHGF1ieGtjqMMlwdanrivIpqeyVrneAifUdVzh3Om55iTkJz7SDmL2kGQtlzVHQlUjgygljjDviYRRaIwoGOQf/PhJ3WKBmw86DBUMPxZlyUPA+5msAvpVgol8uvyUia71N3ALr1gNuDEJwfRKidGA9qqI09EM6SRUJspaVYJGzYYLPYEiqT8t2Mca6uUfvgctxeY2xXmdpzvidQpDuBKMsPEkVXGRtdlVmQEgC+VYXlKtsNgcK4t8/wZORW2MIAj7cEzktA+eGbgXZmwT1SjADsPntGJcB484ze8p61uJc75QhDsRDsMogpGBSum2B4tmQlmgifNICkmQX/wDG1wnKxK5qGacTBqPRXrUGYbMnH2cPJ5AIybCuCGBoNl+ooVCGxF9iGuc6cyAZFx9F2bIpsut/OFuCBEIicRTdhYwXmMKr9ZZQnyaoHTahGldJ2ExIeLo6r/pmfHhn/wzGQ+WuV8R4STUbPAiZreDoLbajYaXsBHUdMrkmBAKSS+z5hE2PwqL/PHQ0uVKOdf7b8KwHh/gQUfPGPTcE1ikZw3G0pIM2i/pSMVFOcpNKRPoQw1rMz8gmZUKUQou1+W5IesCvFU4gupVqC3gJ5QJGwEUpkIT8526PDtoDCVbje1EXTu1TveViNoNWRwwMmk2hw+9y1DeCMSPNWhkMs9anAb2n+2a3cAmx5L4+gxRQ+iWtB0s6FspaoM3tHaXUKp7dZlo6I0kB4A0XhWWzBO4UD6WtcyJqcUVqJjXdsSBXC+GTR8/Gqon651yFjneI4eB6JEX17bVXoc8KWOMoI27gF5TyIkeRcBm3Fsvs6XYzSUBKhNucJ435nmZgwu21hO0Hv7SlXNjOxXx4rt+DBEfSe3C/A5rJavLAEpzdV+JMmMUcK0EERaPdsPja/aMo++cO3ZPocbGAewd9KInlF2ne3fEef/s0HX8qDicwdvp+KTRa0etLtbD7lDQ5GWU3/rbtXQYn4HoNab3tZWi1OtYgARufTlQWi7RW8HL6q38A5zqxnsso2qUYBu5aGmjPBN/TW7a85+Px2EAQBSQ9jGrhvd3oZduMW909wT0J/54WoRnomIcREHh8+CPc+T945SCe+ZzjGs3NTuMec0zfiyZPWn9Y02l6zUk4B8Q0ZS5fZF7/Kx28vHKhsfDdPtmU8iLx8Pwu0ZD2ZAE8XSSF4LiRnyW15F6FVJ6cSugVJ9s4MD2jTqLXTR5Msws5lCjwbhh3JcqQtf8p18TKgijpPxOKz2YrklQGKJs3av6bd6wc2W36F/m71gt+t36d9GD1ba38V/z/tQWnRoCkLtOu8VCRvLXB82lBawpY8SOfnUUkD+nZ2iG9G5aoVL85bwRdUdKafmC8qRVOEgI6uLEoVppZf1dsvbuWlMpwzeTpgbtDtbalkI/dWMbgfN3S01B9t4T2P21XjBDRnU22Jxyxhld0FdpxLGWIg8gB1rBSTcmw+0oSGzwdXoKvYsgTTxf2CHaKSX8iZfko2HYR+pL3/kgM3mfcoJ8NrAcBtMrKWcoJ605CFdOVJNOBtb6or/IV/L6PuXkvgjx1gpxqqkrCIdO8bGtVJ2Bp1y0k5Y73LazqDZUok7g9aNc5WjWYAKNxALwEcCHW7GANajh5ULeIs5rbBZL3Fc5vUbngo1Mdi+OdDBln7YVgXsgUMZ+qG/FyZhsIUv9GeejsEW/S1eHbHuo2chCXcYDSykQq/HzDf1HvDDtxZHMOYwJv2WChUWzChHb7BMwcqguJy6Cn4hoDyxVrfwO71GT8Mi553MVlPCxKdlvuFUFjoPxX4/j0c3elust19APQUJCarSKxj4b/oCvDQ2yDTK82RyWtunlGQiq4DP0fPlrpiFklvFUt7X8ZcoaeQ1mIXhriJKbjOX4d75U5dOaJVwCAHpwq10bBfWn9qZ/amjP3WWB9antv7UVZ/kmxR2uZGNb4bMMNDHbDqvcaZXRy8QKsDovtCRF4bKEnLd5RfrzfqMvftM1vblQKVGhbSXKHOHYv3wQgQkfrRwxGilHMNbzOxQ3BlKe4p5No6z8IwmFm2icM7gPKUJ6gGtwdnotX0aeq/j84B7XRnJjYAVGq/0fzOmweSl9zA0T2jcghssN4gDtyTqkFKDCmNeBxLUMbEHvzFzRdAVadjXCOhL5GPcq55CpW4RHT7Me+bY+tnAimmKM07sABX1DTVW1qMJhQreLb0wffxlg4Be5cTeZF8JeVILHfDWLNx2iFXVAvPjHSmf4t5LagtbXNE7tOYFSXo0HI0nteDms128agmNlTH19mxDkb+ZLdGov7ZAO5AFHq47qY6aXWPJeVF/uJXHns8Co7/YpkfPQE9UoIZnhz09JYcDg3Zx9h9KwEPzV+KwdUlgqfWDSFJPdiWGjtbtqUbL9mqy/M3uKHF70CeYsCPPzBKkKstcQedFKDj5HLnfalWsiTmwSqu1wpLC8VS10pvAGMg5zChFAgzExFiYXnPPbSGpJYwXzJEx14aosTyI4dxZJmQ0DF2Zsl2E8lAZx+l8ZljXdLrKrEauleGUSDSluUOVTGdFojG75fdEc2oa+q7f9bbaN7xySaJKVsmOt6Uf2zfx7qpcrVuq1i5UaxeqmXF+meHAyFF8749KerTLF2E00dOSUnzLRGu+zjJ/aF9ofFdAchiSIyA5BiSHo1vfnWRRMkvGSV6/v0iy6BCEU0wCZaUPwBd2/Gn/2HCvp75IzbxBGI5JaGHu99grKjFX9BUpM59MNSrRbBlFqCNCjVtbOVtbDqoMnB0HoDkiQLSnu8g6/wq9t0CdfioE9FQm4ur3DgcDI2kVZoBJh4LtEiOq6QOF5+T5eQotLFXoRmmvZ3Iu6XJOd2pxdhTRTdJinif0Q0C15verzl0REchRqgwEjt2UjBgbWAaWXeSatOVCA5Hm1V6c1TE7HoZSm0EpLpTbaYP0XQ3TPaDVsMtqO8yKwsCSVJUm+8xyca3WkqVNp9dyeanTsitp39hyDWmOMsbwpLgR0LppmuyRKQXan8wwOGg+57B95AA8nsessdmLYRvbwQAx4uL+Kslx6QAp8Ab1FLnTZGbYA5DJSFiDidtpNYIGX4u2GnfCRimaH2xFKAizs4PWmqIo/Kwqi7orYa5KNqpy2Nu006iqfCWVeUpvyazMcYj7adtBLfAWbsd6K2jQbSL+BaGUvoGgWqMh1KF3/KrRKRdX3akDUG+NxwGd56gyYf3fs10fE0up6z/mWNA63d65J1udbtDYyY3MImhmjUPM5dj60Cy6ZKr9LI4rIHy4bE8lKkgxoVpKALre9K4rJdS6fsurlhLgU9urlhJqHb/jVUsJtbZf8KKuzfyGVzI4nFB4FFi2yXyazPVFzVAIDukVwgMH/FDmhjYRvM/mzXRJ4XTrPNWOak2cLuyEgueQbkdfkh/PeYPlTpTFjrpmUkSp6WGwfAzjQ5m5euiqiFHgRTyPGt2cGxyFLMhQFQK2PEdQ9npGyb/SkdjZPbbkiWxSzRSajLYnRgRig0GSBJ+kcJjFFW7/iK77pd13PorTKIOJMG0Vi1f9BYNMtJjUMwgHsTCdsO7OKCjz3qmzzyaeJVNL6dTJeS3iiqGbXLE0W8vx+KEhm5aUVdGOKyX30n1/39KHzKIFqs99ELsN+aiAkAN5Ft5fotcKjLouMzSj8qFoE33Lam6/AmwuFX21fc7ZFyNDqu2k973CZZpxlXm7uzHV3nMY/jCCAxr3mPCgNWxB2LoGkVrEUxwHOkgdcDxDROsqgVyXEMtWUWi7aV0tWV6NJNZ6tk5wA1sju/RV59tZXN+PUzoEZe4XEXtz7lC0bGEJjIPCoIbwd4wZW+KTaLQEjERUwwhIhZ1OLAnqpNjRW3Ipskv224JEjwyeKdVbYn0op1HK9ZIPNX3hdMuKiyQxn0R8fw/kevOYWoTX5cDllPoF5tdq3Bqj1f6C21+I9rVkLQ4saVrFBxbV9yyv02U7hH86+E8X/9kNlbwYmrwExkikGxfjJUuV7CiBHJ6+rJZLYOkz6KqYUvEUwnhz/EWfNDOVJ62tFqmoTZcOoQzkaH3HIfK9OX28E7ZL3zvW907pe9f63i1937W+7xbC/cjp3NQJjNQKo68wxizOMUI5a/b4gG34rV6X/rZ7ZJ7cgUe/22ue97GGoTBKOW4JrX8prkQxiOWivZhi3kGcup3Udxcd9dyh56567tLzLv3ehd9VGgSV7kYtFVZaLYUiojhCC8q5xGkic/0iVvt6W1adBrlBIyoqW9tqXX1F1tRpqj0RpHFmD45XvPbF/PBMzPE+VjAyWYxXULnT3hbBxTrbvgSK8+hEApyYJxH8G9Mp6MQBaGIBpzAc1uJU3RknKJvyyS83vTrx1SCFo3nF1ge8bONe7+A/Xfxn19zbbJlateuvva9J89goB0JOqj3g1YZW/LNeh34yKDLShe0zI4vmnlB3ljsyNOgEPpc2KREJ/FLanDhJ+mOn9LGrP3ZLH3f1x90vuB2xc7zh8BfuHeyRetMRb7rqTVe82aWnddtSzwruTXuOdtKKLVgw+dNuDAbXUOB9tBejxXhKjlMwuMzgAzPLQWKOSHZeZnMAmK3jSgsHfNfb6BCBWm/jUeyOKpcIzjQpRtZb69VQgZ6FV29U2Sq+8UXcHKCv0TTkWtvQVMEJYhaWtz1VKdC3olvCd3LF0WsRYzkXpIayDiwNThRoyN4KU44dobmstRaGDgNEVyiQjIH4pafOy3jFVH8er5iAe0bOV7hA4HofJSDj4J0hcH+wPgWfB1yxWlUkdLxkXMz6elcM/N1Km1WzZOd6Jcv7YnMVmD1Yj759zK2pwlJM3UgEYuNPKSB3AfMkHpv5vOHxjny/zpEDJxL+X+XIQXtgMdvkvVFc4HvxNDpRkh2JvCgZxRgRLwJxGfBngpv8gMUZweoHaw6BdRvtaqz/EzBfYdc6XFqHOVfiyVVLXH1yfYGF/UKLa5syC38bKyuKcMfBkNpHsS5hiF443xWTzqBNZkzzXVfUKa6UPC++IaI04KwspY8pI1VJOAbJcrUA8R4IyR6Lj9JVPk7h7JBufjLwg3leKfcG6jsFPCl3VVZcM8Craq0bImpqSOYVDrQsJZjuG/MJj3hMtwNQUIrOrJMxNVrBlZde5n0ZNTjsVnNaen+Kk0pcMymtQ/n2zLrzLArb5q0W+66AVCz4P8yQSXhQVYaW1+31N/bOTK7u4oxQWk1GVfOTXAXS1qH5okBNs4wKDWLAwXeVZaoAFguX59xY3mFX36mW18YEY7r0UgzsAptllk0por/7baGr42uHjHRYrEUqaRUp0XfOPkSkVpS6T91X9El0S7eMI7q9QgeuJKXcBJUq4j0h3rOSGH2887DWZOkVhVefJFhvrbKYbuqHyQx6c0RqE1QzNBpdr5DUjtXDU8VVsj4Z909Zpbw8AEkNuVF2MhfYCvQDR0GzpfSpL8s3zgG6hyPpz3uIfpFRDbc2TmBK7ulMr/Tx51iKCSUjth2kuFL3FpieXnKRhAKeM1kIc11epwPBe6ng1gW6IYQlAEZkpUL7KkzcFT+/p5OoCfPsqVIB4VzS0g3TuW9gng9TgHnVTRdivMktrz4vvOdb+W2y8MobhhyN9M2rBUFdABThC6kxZdfQOeWm5apn/Dav+mBN8bqqnvULdGFgMgNGR9EykL0WZVvWR0L+jNzoGBwUxHdrChF5Gcge8FN1w2KRVJCtYvYQ6lRPLU0lIcboEiUKAu0W3w3KCUCKo+rhK784kl7F4Pw1QqwGtXnuK+p3rlW/U5zC87J7sslq0Y6/Ta8r17FeoD5VSo6slEBkamlPK+LoUhnLyuqrzqvQIwwPz60R/3KCPkSxiI1BCeHS+Wr/APlskXkyyRUdHpvAUN+ccMY4JiZ4raw4p3wRjUAaTud8wYwUY38KBGTKJGc1s/NeUW/vhE0S8CS23Qlb6/3deD5lz9JRLNOcAt6LX1UFx7zDqDHzO1RYLNDeCFrI57i93Mvf/fTxx285T/7x0cUnn/7xs4uP37v45LfOk5+9e/H2W5d//87lo/edi//n9xc/+sPlb3558c8fOo8/fv/y0YeXH3zqPP79x5cfvXX5h/eowC/edq0h0gWwe/noo8sP333y7vvO5W/fB4jOk++/c/n9/3zxo18+/uSRc/HjRxc/+rVtX8laJdvglUwrvkRb16fwROPbtKrg5+vjduWjZHFqh98aHSQtkPwT4P+WsWk2Kw3AppRaVEcAl9fs18rZYtqYYARLZU0yMGyZ9g6Gk3FWWxxFU6XBpLiGMlYxfWHvH7IS5CCs2kA/DFXo2nJkZDYqtSL23XLYUTtc9Onr4JbzZqiCL6eqJQw5EioziML40nrTp/9ZBx5ecSTbzVuYUYKsMhGGL9oD7nYr3cHfGH2I24Z3A0wmIFo7iqbFgM4UNuxNv+E3KxwnRBB2nwOIAuPVQn7Lx5idbWC6bB7qPwDazZFbGFfYIdWO2kHXefnVb7z40l3nm8/df82z7I4Aa/Nwo7ec4H6yLBxP+lh8oAO2m1Eum7u+g+FQrKzabKuPCwsACsGxcHlLSlQ7QcSZtFjqKa8woJ4cWBGpvXwwTYTwWad3gb6lUXqlf7WLlivoSyXKK+OnHjCtPiVr4ebPjs/hHSvTcaLEAp2fX9FClb+fROXJFLOpZ1mQRUexSpRK7eU4uXuYRA4ealgQrWZgPveXB2FnV8VDRv84mUWLzchCmuOtheAKx4atrfjC1rYCxCwmbvYgWegwpsJXodP1dDhTDNg7lJfUmRFllHYijY1q6VhoGnI/y3wcAsY6RdM8uSPQ3W4ohnt23DMqkKPTsc8Qe4bfZsMrL8EaU7gNXpbInWGnMTAwRmeFvsE5joOvGZ3o+UATBgULNepSvVlHammA6WNJaUxgvBdufVTLOKHxdEAiiK2j/taqYsdeWbcVsAM8d/104Jn7gu3h1LcdsS4FRLX3DkKDH+VSekcJb03ZdekoKwetPoghV29Atd+K0NC/djyeTzCUYhnkneZGoGrTirCiaux1uSvIs5DYhrGwpQsa54U7MgOnyklw+iYhGIiUkgYC948H/QK6mLZvOtRLFb0TVm+2f5s+ClS8DrJrlebSZD9ROtUxHo/hqjEFwdXyPU78sS3+lS4asdSi5N4mzHnGGJav54z6C3Q5YPjwO0yKZJ/BwilI8XVCCkbsbdW6O50OvC0SKyp0q7yHq9KimV4cLbPjnLly1K9BLY99UUu0jxoiAki/GNfom4lgpmksI5OFSBYeGeYVR8IUVXFfXJfJmC9aDBZklEsN66UlRt3oh22saYVtjtxe5Lt7bm9P0AO3x824so9uT2UZdafJRBbYkW8pF4r8vWFflffXw8KRK6khogHZ39LcIxPluwuZDW1xdL4uzJFh7mlNR4/iXLjARg7fFGAGoWQsMcqEAK45kkJcRyxjWkCLiLGuD9OHkzfwI1SoYSCDsM/BmylSMv4z8NbGYNepLjBElN6jKHMy+jXW7VdrW67dvBUbqB3aTgU7lrYYg1yVts1YX/GPNgXEHFPkTMPQvxyrx9xtba+ItYQ8XClAAGoZlBsIvjX26BHsT9POBcAd3VazVxH6vWJTHckN1f5SNtNhvzGg/XTYb8KPEf5oDdTeOjL3laAi7S+C3TJgDPXu/0dUxyFtQvfNOG/1nGbTjorDPgth32jMVx1QE6fny7dHauwpNndM4zwfRqtxckWWqlvOfA/tduEMUQGEgfsp5pQyjhpZnoOGK775pBUqJ238UpPlNMnf2mop2slbwKaeyoyOPQugrZPWVq3T2WnfxA0s4KNkHuTA6olCfqccjFaEOBdZKWDWgCnM5+nwpDWEL27vpAWrKurDS0zHJoC544nb63RMxCyq5IidAqmU1RduzxU21Xi1kc7R0vENXi0KV3EH1fZdoV0BUTaJj4dj+MOVi7DFLcbL0vhjgtavcTo6dWgt6eb5lgM/lEMFKejQrCjGrUjWych4cL4DaSTtGrcXiDewQLMoO0WSG00XB1EY6HuFhRXtrIJxAuqah09DuYtR9bFFmHL8I7znjbj6lBuUXlJHk/2UclojCaGI9Ys8MDD/NkFZF8BedNKAvkTo4nU1/OVTwJeRAnvufQVnROpKI9rvDq8cLDmtjoxZhzkFR3gdwibw1hJJH/bYWCh1/l2pcLjFsUaktuEWR/ZJKfqOjttzi8KC0Fug4tPTmvCOzXv511peOcLP2r2FIUpQhpFSgxn9h7++2WxYH99cwXRjnvWgWY7dxjVurqtxE2tQel5UfvOawVOAT+g5yykvoYhMyE37vTJbY9FNf7lKny4+1qZEAOtTE3IBFVFaFrKDXCMmfPfui3/xrdeGL734jXvP3ftLysvtijg7cIR+ScEpcPYVpLgEtnujDLZZCbZhgG0JsKJGAWarW4bZqYTZNWA2GCaHXojIP7EEud2q6G23AnLjhobc6TJkVWhaAbhxTcDtUpfPdSI5MpCoUURxXwTq6ck7SUzGrawSvK+LzzpGI9XS/h2z+Xx5YBriZjFme8Ib2yx2MG00mRDSHSTZr+WwfabOAdqM0ADQ8WCeASOD1ktsX2/tc9z/B1t8m3yAHcAuetvtLfpwJ2wXvzRb8lOn8Ekx+6s0Vq4TMhQZsO6xdG1odXQQUjuGe7O7PoQ7njwiNd6Nhq3YfRGBUzqsukiHZcTGnk/wKhtdFX08LuvjeDQllwzuIrDjezCZ2sGIQsFionokzwl5bHBmWE62vFqitxBeslHuYzgD0KUpIFdJvNKyQ50K4EK5SP6S7C6k7sAB2hizB8L6oTkMGo4C3UCeF/q4GuFrmIJJslwTrL0QjPS2mqbtG2Wt8ZmbwsTDOaboi++KlXJ7Nh3q6zLA3JM8C2XOzjGXLS6lTN2jwt7I1F6qA77Zr7qBADIaU45RCIBr0tKP3YVzzoGXm7f05RyiVjNWeElCFnnDrHN43ipls1Lfr5Fr81aJuy7mKyNDWL+WkmdHwXjAHqCMaVC0lSUiEBbSIfCcqgC+7Jlobx87CL62H4BhbTWf3X5jnemACpR0XLbLJGKF/fFCEQOU166P4xtshxa5IzF7rlKHSOpnrAmu57Z590k4wyApeAf/DHS1AupinfVIS8E9NLoKuDbK0h/BFOA+3yG2QN7fBqP8CBkDwUNw/kncy37a9NOWn7b9tOOnXT/dZfeAB2mz1bzptxqt3XqjU282/abf8uHUaN3w2zd91Dk0sQyc0qrMDSjRgv9xoY7fafvNXSrUVIXg467fhA83qFDDb+/6N6lMS5Tp1hstv+Nji88iODgWO00AR4XautBNAE5gGlik3cZutbi5jioFRW5SIejBsyBrYcdbN6hQVxUCqDew2E3sOrTVQXBUZleVgZ52RM+hV7vY+Q5PwLOiDP4PJqnZwX7h6JvYXpMB3VCFAAL27yaNHcbVpVJU6KYqBGMCTgeL3kRQ7WexTzyX7YYu9azPPce5u4FFUJyFInK6n4UZx6lsU69uUHs3/CYXaqlCONW0tk0G1cFFoX6327oQri6OFScJOwQ/aOHaHVUGvjQFHDE0qP8sFZKzfaPeaMI8Pkvr2yVUwjaozK4uc4N6xOvGUwBvuNSzqhS21KAeteUsIT5RqRuqFI5IYBziCc1Tq0WFbupCN6lDbYFwiE27/o0Ciz1Oov10Therf2Im8z8j7+2XcvcoFi6PJkhGs4z0s4I6R+adfCSu+qTaZM/8uGd9lClf8kO6Ac7RgByOgsj7uvm458lWoj6WHSDMPf5pnfSRd7uDoj/qX5ZjeMQAsvp5z6u8LzYV9cVYezjQ0Tye0GD7sKEGOiuyEhk4jmIxli+eoCdGiD8qtN6MdjUzxL1abgmFrilcygiAhSIgAZoATkSgyxMOnWsVnc6PraIqcmVVYTrfZXE6kDh2ZKGYiDep0v9RxMoTM2IlAz9X1c6NieTc0Wh+MAR5vTbJyGdVWj0KTc48U5M8DqlIv89FBtu6CGY9JTfbWp+MCiZ+nf8OfF5oL0CVZBqBqGymXpGZnYFNhEHe4HS+uuHttlfFM5bzNqZCL4CWd4A4aKKJ4UGYP8xa0jxA8Ian4ViOoZzDnjPHj/vm4CoLzVbh64wU4mabbqxe502g3/ThZdhQSUJffxjWXq/PVngPJXoDb07rp1J1sVM75WDFFKtYtPUcpRUlXe2Q84njPM9TYMNw3K8/hAV+/eFARdVaEm2YoipvP5gCe/Fm7Tn/9KGfYeInDj/Zb0hnTYza/9y/21NZMfI8EyrPWu30YR2/UxRSoYyCQeVLs8DpQ9l3o5TYc62wWQd4OzkaAU6wpgz5UUEAzK1ZSoFpLDEuqAgaY4VRLK79Qqa3hKH1k+2m5KD9hc0EGxh3XtgmGYaNmcWwUyigZwSkJ5oOjeNkc5LjlshgFHavtGRRvLbFQd9obMiL0faLwQJZEPuWCnyBfrF15Bjr0UEcjQvDqR/ldR6Ro0ek5M670ehAUAMlWso4A2N2RaJjDaTGaQJnmuRXHed5oN8xW8Wi4CjXWKakZ8NuihtyAkQjxXwZp0YPhGn8IpuDAAr/K+iU14qc44l3OzTW4nqkQxg49oAnz1cSe5TxpMCHPyELtXW5BwOe53B4UfoqgUx7Cft4XiNptUjLPjGEx0Kin4mWG6uTJbMpxPVSI18lWFaKhUVfygohUSO0TnxSEDivK0b6xeAElfKkLlROKCFlycbaXBamhQL1R0RIKfIao6LarCB9Dkxz4VdoYuvT+AjdRaxtqbDEOcoFkgDI0XSV62AqtqFZIXu1eUptTuNo2VqNeo40vKk37YiU/H6Hs0ZwPknDGou6eM1+UEuMkD1Rk5ozW5PjD+KTJV7zcutqHj1z68gy/EaXMZftq86rHN3CEXx1YEXkuEIDyuM1txMFZKSKmp8jjaOM62l8Q76GvxUnbJiHBjdb0kwATojPYd8oN9rUM6wTHe2jGqsQovukf2jkeNKwB2bIR9mvc3PyoGxYdIOwMo8DRVmXZ9xVsyEc3vFn6bJMTaeMdVlVCoY11CGZxbzTJtNZWLRBm47erDbjBkMZAm7q3U3w+r3VgFH82k0UNPlmK9YnqyG70rXbKt4QmI3Z36zWCtWu3ZwVmdpsy/hgNWRWuKqVc5MQHYXrMtxaOCvNZoqoa6eLlaaWRxx80PpYkd+plFK2ur78vAGCSDtbXZ8/FmqfFwiptWOL9o7xCA553OVnh2jtKOiCZbmjywkgXFRCXFMWzT+5IHfdKF7XrXiVzezlQ11dp0lZA2KdIWY8UrT9mgY7dkCwa3CCy/l8OMFEgqSf9UX+dwClCKNMdgCMbmgoZ+TB5evzSXUWuNgh36HbtMwvUh+/glb4VXu6JFKUdmIpB3Ih7fHA7BoM5WzUM0aDdk2jgY/2SZouG8ePHBEnZU/Ikkls1VmSc2wTOWKx9qhw8dUTak/0EypI9BNrQPSzVHUMSg08db+tzhU6rycE5JWwrCSBUr55YvlyErxCv65Z3eqL4av+rdUswsB/0ZgC6o2iVR7nOxG7KQV8J4ie7HM8zBFtodipk5MvSZTn81FixXEDRAfSGloCtrEkPffiNz988t7vn7z7L87lRz+5/NGvnYvf/fDyg88v//CeiWbWyvXcJz976/IXHziPf/vry3/6+IoapP5yLz9864+fPf7kQ27OufjDo8v3f3lFTaELc2Wd3/z08v1HNfYSq8Ofyx+87V0BQunJXOjr448fQfFHl3+9tssWq+G+/IJzn3dToYzJMbhiEi4/fOfyh2VwhZNfjuXyRx/Cn1Lp4tntfhsDD1y++8PLD9+9fPSvpfLW4evipH7w+8e/h87808e0ouU+Fc8x9zX65Vz+20cXv3l08T9+ffmLt6oqiGPL/ffwt7Kw2P8CUTcg3OXvfnr5m/edi1//7vKDty8/eM9RGHj5wSOH/AAJER9//HeXf/+Oc/Grj6EV5+IX7wD2OIRG8J1wCQr/C/oI8tJevv/5xT+9LxYYvlz86IcXP/oo2IDF3ce/efvy548A6KPL33wqPBkRtX/4Hvkwwp8nb//yyaNPsWOtP37W/uNnHXgv+vc07fEeaP7HVsvZcVrt/9jpih2ATpIw5Mtf/U8J7lcf87zCqv8NOj/+E2wz6uYFekOKSo+u16zcQJf/7XuXH7wlNtDlz+DXo/+iXwhs4dn/5eN/g1H/+Nfw68m7nzrWZoNJefT4N1QQmrz8rz958rOfXtEDvf+ajYsf/RJbExvRxCHyLv2bPwCSy7WEhX/yf/0eJvrinffsybj45NPLnz0qNyudidif0LSpFvH7rYND3nf3LK2AeQtyVLwKZ8gqJuShSIJ2pEJviQLFHKaHRz34fx91kEDeZ2i+kcb7HLU2BPqcYewtmCsHpdkc/Y3Z3IIEVBmjFQ+BqkEJd8Zee2CP5Mi57dQxQHRRt0GQtBX1JELtp9vjYwK4L1SjKx0e2VDzjnZ7YmdDmXPPSsnEME13DruRAh8sm3Qv/uH9iw8/ww3PJPTyw+85l//4DpAw5/LvfwDEoWSranUN3fyK8ojoqgv4+vizz50nP3n/4pPfy42tEIzI9ce49xDxoFnAM/Hi4p8/d+BgePzpW4B4sO+cy0cfXfzqPz15l7Dw4lf/9uS//vDyb34rcA82xFtIDP6A9OJd2A2AnPDewm3abj9//+JvPxLe0LiJH//2HWrp/Q+hhIHLNtMvWYLnD+LRochijmFc5ylFQKfQGhPgZRFn8oP5sY5XL2cpkFFlo8Mq7JHs33V2AxkCHd0uacsQ9jp8Itnm0D/0Clgld84m1bixmEQj/++LX/0LnhZqymkCfw4n3ntEN3/wd1DOOCleidG62vmuYYrFiHDxC1jVnzPCvWvMvZ7xa1xKmJFn2JYDFSJS7rCuJkRsHfbTmxVjyDB7IMWH4VGO+T5oUXROQHgo3k4ODf2KTkurXipr2GI1U+Wi6+m3VRUllsQq3IV8Y4E3yasuar0uQtU3AwwTnitBmuXMl3bkHiQ6bo//ml8QQwUDBt/xybpwlSJeRWgf4zpjx7jFYINHddOy5i4Dw8zE8GbORPIAz2KyyYvfRL2uGQK9EFEmSoGhX8QjNO92duvCQ5xD3BjBgWxTYjgJcPMj5//Udg5GJq+nTr77xQwjfMNVcq2RhJ0yXcHkFLMV/WNG2K/MRGtEOZjEEU5JTnYEdN19lMxXhdS01zAruHba37VJer+geULB9sBKsrnZ9qCQNfNLtD0oZ8s0bA/E4Z3m8WhF+aMtJdy6NMd2ODMgnUOeyHLt5lqX09xvkdYxgpkPw72vFcz/XXFNNEQkMAeEVwI5RxqV+OGx/lI+Wglhy9pLM0UQkBiUA3PyJS4E77jWzdzA9F+U+1zeVJoRQYruhBYceVfZM+OKx0eh7p+6RER36FvOaJVVfTSVfItJqPcTQsNq5juA4dP7wr2CfZOgYesLBTwhjobVxaB/qmDBGVyyNhPF1AgtJIFjFeRRZZVRqQp0fk0NLE+5cl1yDYF/WYkllVdyj/gVaO9XIPOgUo87jqfLSPRgNEE16WJiqWfL+tFrOqoLXxUDm7IYyamBTMbdeusp1ahpHI+Hy+M5G1nLq/Q1yFZvrcc17Zb/tIiGmyOs3iwyxjIuVa5vzIwJ9v5Mi3xu5g1Ah60a8cn+fDr20/jYXwGvHbquuUPHIXyoQwHjEhEj94Tu5f/4AHhhcvkbS9Ma9/HH74Cgzi9vy5cXP/4ZyDRuaQ0n7hm1f95zzqCF3v75Gfbg3Pl/f/B3zhm0q9/UzqjVc+cM1fdjT33xuC1u6WkAcqc8V04JRnoE4mWMHOdHqyddH5aGFmPgj+Qvk5ZzeUt9w3Vw6bgO/4JJet8t17z88C1urIZ6Go/r4oJzXf61pq6loeSajCRcV/yuaPPvP778wd9ih1HRxxXLuMRAqt67l2//bVV3aG6di+99YIOuQEmey4r3JdATmKFHT/7hbRCUHanF/PmvL/7Lv17+/J9hvSmqyaT/4BnzSH3wzMA7xykTcIwo/4apkjEyyeyOTkeYTcbgpqUvYpoPk/EJOVME5PLcp59IqkszdKcxUHYBpnuK8IeWJyUB3Y8W+uyUuWVEa96dphWtQhWXBfpvDOr6N1AtHYPcPH0VPMkZypAMEmRYU12sNzVEGaJGvhDe+7KoMQo00ZIWepvmxSsGgTGmRTlFE0RUM+tcbdKsQM2BpzuGj7aF3xcRpyV/ZftRypOiyt5ABbaoqNGsrqEaESFBSfw8qoKpCuD5UgVBHkAAYlIFQH8f2d/5/MGwvPTD/CYlShahiTKan7XsaS0tZ/xUaHCNGmJtRSXxVDUIs5KKOlREXq+C9c1BoptGLOjFwxQEMYzLO0HH2vHEd1J0ntmbZ3m4W3Ck+ybsbVPI5rxGxxiImGKlcXzdGaAQR61mhkaEh6XkH+zIjIGe4THJYEdOgYaj5CicD6vtCJutL9F6kHu1hrG5tYkjMrokQyjpiLFTk/HhNkzeB43KsrGmZl91Eo52a8wnzaHvJNtN/HRMqkSaIAwyswycuyej6Wqs5nUvJr2Kg/6CuIra5TA9TOfHUtG4TuawY/Mt1osc1K1qoeOWk55UTSWZ9xqmiebc8CgxzmBqvgZAPn2yUkzeh3kBUQ6NX0VJzKOF4h0p6es0JucIcErczKImReZZiA3LMgwiXkypgGxTLtmW+lQxMDvtLiZzrC5M/AoVpl/eTmt9WeJPqCz92lhW8CNUWvImO80NFdQdPFVRT1Ap6K6rU8GvUO2K9whnbdsVzAnPX/n9xv5Yor6YVesVTVmlwajYUOruh89CXGbPTye+JZpuG0eOZ2/I0tXQSe8EQweICFzRYRyKkv0e6l0UdaRtJD6Z+e8oPjVUe1rxbD6E02U631eimfS61EE7YUF2KOfn9pilobE/9IdswnkYD3zTwlPU3gllmlxyBDCzEH+JQpRfWDUpW9KhYgVMq4xiJEL3iVFOpHHk0J+sG53MWGsHmxFD3aIgd57ZQFZdsIYl6wiInCVMHQr3vX+47XJYi0GIf6oL5Bi3l5ybVYA0aNLzG0GniyhxSEhhCK5if/MR0glkVl0J0551I235oHoYFoZgg9U7Wgqk0qfanl+1MVQvGB9leGyyNsaSpc5O4fwXMTaglbBPxxA3MPT5TOI2+r0bg0GxEbUl7GiWrC3hUqaeOMG5nQJ7isvh52N5hj0MBQXgEFZ1oTDFpcUYXzJ7NlQw02dbvm60esDm1eqNoLv1cOuhZyhnTLUMdoKsHH2ps5Faa+qu7JKlCaHiRmklIMirQ3ubcFrwfo0RJmg1PL/GWzVotvE3bdig2cLfYtuKJ7V5g8YNfK7YwkGzi18qNrKoY21nAjywhC3ZadiqIU0Hblq/vGn84jaR6YkpYWKz0aBoEehPUvtfaawejGbLGqUmXvq1jUN8zzHx9XeNPNE4WojNnACvtzylgP/Ibaf5BoeiIveNuVDMRGJ+KUUepqOvyFMrkl3kZprcPLYzYoikMZszYZw6gL/JDNF4s+dP64qYxNoQE0Yf2pdKNZgUCg6t3FE6KlENLd36yFQcNNnk08Nuo8ipj5YnYdV1lFwPbMImcuEVMpMWmbDfu7SMtWZXcto7O11FXQ0SsFG3yqrfcJNOWCtVSdyTmdvpO1swbxJKfUyKTlNl1tDk2FQ8lLISlyMbiqs5XDMMWmzuc9vyZ2RnhjIT12EmodLVYW3kw4LZnkJi6ktdLijslxMfCTCsaIbpe4sU3CTHklB5G9MW2AC7aO1ikHiLvPtnxh0ImchPp2HQvbElnCBhrH3tFzHwtoNOa2s5KTiQIWHEorb59TprenuAbo9TdkGnWyXDd0WIhJ0iFxX9rCivNSY0AesbpqnBfEDZMq82l2ecsEP5ag18xPIuvvfLqQJHOeWsxss5l45Ud1DOIAkgOBNj7nzdweInurB3OyxmJTwxcj2ZPVkko0OZpws4Vp8dH1EUFpJC1nPMkKT6si8juBTWnwcr7ii5ei1jux01UjlOO5AnUuGsMnjyuhY2ARRTg3QJIfgidRrvf3hh0shSvktBkUJzRpS0hLNbwKaBf2LhtjZNy8yw4YzeGTqQAWMszijKbfHf/hNZyv72/ct/+Pjy0YfurUL6tsi7RqcKu4E6Vezo03eNjdjQOvWDT9kQ1bmykyOpqbXo1jomXxPmdWSOF0sRfiHwRbZOkASS0cJXxeAsDNoNHR64UN5KTGROaske7OlneQMMKK5oy6BabFHBB5XtfGhc0mC+kw9+Ii7SCjT7aQZShcPFwf1pAwnDRnkgaD1cPZbr4iQBWo98Rgh0GU4SNn7txFL+0Xl2wohWIuYU+8A8zpjrxikJqQTX07x417NyfuzHxaKSiTcLEt8M7cZhLejsimNSdKnoatOoSiYJ/9kOWh27punJs7ZWs7ulh4RPqtPlw6Wm+lmJ6VVUqTz7T0t18Lbwj58JI+3Hn3345L13N5AbvPuhTwZsNG8juWM6n2ehloerxmCEKqGzxavfMHVwdE8u02+XcQn/gzHv6KBOCdab+oTVpkhvVp3g5kRLkx/j9K4jYM9f33X9qbR1vXVkwRqLPkLWN3IntGbTuwbpManEGpy5NjJIbxmgFe/+cAMaaA6BWXNeTN9SdV7j8PZBLMYwm2GR15H3scxrgKDVMzNgyYzRRZ6kgClrhzlx2alAjNM5M9rabp5fMe6EkyrpoCLl1jNSsx9i9oltw9sdaXiYmbTcJAGorNV3OHLZrI5XsC8lOyICI3vusquLdGsh9yA0UK9gNdDLA22tf/7Pggo4lz//IVrEX3z83uV733Mt6aWqZ+u5lyv6+PiTzx//68dkHP/Xv3Yuv/+9J99/37n4u4+cyx99dPnh++R78sHbwhJBeV99D025f/yIrMK5mSt7WDwLN/drYlS4/N37T957dPnfP3/8+4+xRZ4TcpjhPuqiZBiBK9x/8EzpoCb7iMu3/1Z43FzZ5aoT/KoV150mnzN0eUBnhXelX83lu+xXROXEfNKYPnkE8yl8FK7sWdWxcUXPbN82WHVhVgLj+uNnwjVJdwfwAAf84feEoxQ7XFw9YxYFu2quvv897Q+FHXr8mz9c/oH8rS4/Qjy++JdPyZVEoLOFdGqevoj6AMkX+kUjnhRvqpT+2nwvlJ4gYzYr0laXBvaL72njHfSq+uS3gBHk/UK7TGyyJz/+z7B0j3/3tutt6B5fYapeqWjc2BnrLSphr9E5w//vU7s/1k5nrzthYrWpf3xrqmcNI3c/zWRZzq2lObL6BNgFOxcpKNC6yw9/YvYLib5Koej88TPHDd6YJ3iPR82hz9Z6f3alIxBfg2i5zHI8QGlUAFLdVxRKxHgpgYGahqbOTNypGJmMSxUpujl0lYLHQ3XKE6vUuW4xc4XKf4f6Sbrw5IwGmLmzbEwKL66hX8QxfYn6T6nZiBebtt/aG1MhhaAviGUZhp3ZBBBEcCyy4WrNCLSEwI0ThjCNXOLEIWicfpKQk7cknRcX77xPpBt2xgdIy/+nczZaYGreXtCYnH/t8r23DF+1i59+fPHB50i+uso9WPi9IjGFU0ufCeRqC8j/r5/inrz4xc8v/uan0k30799BDyp54in3KW/9oEziw5ud3H6tzS0tCQUNUuOhmbSNCmk3w8nZC5oTNC60hynci6VP63ua3NFphiQGeJ6P3iL+htOTigPlk8+hBM49e56SP+xPP7/eEC1eBRmef3zkFD3ri2OShJOGAuvlF3yPq2tJcrZ2Anhe5SLT2YWD/u+fX3zyFh2yzORe/uj9i79+D30U3/uo0o+5lESjGJdPb2S3B3vMV8Sphz+k42ju9miy0GHp/P8DaPnbyg=='
_RUNTIME = _Path(_tempfile.gettempdir()) / "md_lotto_runtime_v58_integrated_convergence"
_marker = _RUNTIME / ".ready"
_RUNTIME_VERSION = "v5.8-integrated-convergence"
if (not _marker.exists()) or (_marker.read_text(encoding="utf-8", errors="ignore").strip() != _RUNTIME_VERSION):
    _RUNTIME.mkdir(parents=True, exist_ok=True)
    _files = _json.loads(_zlib.decompress(_b64.b64decode(_EMBEDDED)).decode("utf-8"))
    for _rel, _txt in _files.items():
        _p = _RUNTIME / _rel
        _p.parent.mkdir(parents=True, exist_ok=True)
        _p.write_text(_txt, encoding="utf-8")
    _marker.write_text(_RUNTIME_VERSION, encoding="utf-8")
_sys.path.insert(0, str(_RUNTIME))
import os as _os
_os.environ.setdefault("MD_LOTTO_DATA_DIR", str(_RUNTIME / "data"))

from pathlib import Path
import os, threading, time
from io import BytesIO
from zipfile import ZipFile, ZIP_DEFLATED
from xml.sax.saxutils import escape as _xml_escape
import pandas as pd
import streamlit as st
import plotly.express as px
from md_lotto.data import load_csv,sync_history,save_sqlite,dataset_status,save_sync_status,load_sync_status
from md_lotto.data import sync_incremental_official
from md_lotto.stats import number_stats,pair_stats,triple_stats,structure_summary,randomness_audit,fdr_summary
from md_lotto.optimizer import optimize_games, deterministic_top_games
from md_lotto.backtest import walk_forward,summarize_backtest,nested_walk_forward,strategy_tournament
from md_lotto.simulation import monte_carlo,theoretical_single_game,optimize_five_portfolio,converge_min_miss_portfolio
from md_lotto.ml import train_evaluate,walk_forward_ml
from md_lotto.diagnostics import recommendation_actual_diagnostics
from md_lotto.transitions import latest_transition_report, next_draw_adjustment_report, adaptive_priority_five

st.set_page_config(page_title='MD LOTTO 6/45', page_icon='🎯', layout='wide', initial_sidebar_state='collapsed')
ROOT=Path(__file__).parent
DATA_DIR=Path(os.getenv('MD_LOTTO_DATA_DIR', str(ROOT/'data')))
DATA_DIR.mkdir(parents=True,exist_ok=True)
path=DATA_DIR/'lotto_history.csv'; db=DATA_DIR/'lotto.db'; sp=DATA_DIR/'sync_status.json'
bundled=ROOT/'data'/'lotto_history.csv'
embedded_bundled=_RUNTIME/'data'/'lotto_history.csv'
if not path.exists():
    _seed_source=None
    if bundled.exists() and bundled.resolve()!=path.resolve():
        _seed_source=bundled
    elif embedded_bundled.exists() and embedded_bundled.resolve()!=path.resolve():
        _seed_source=embedded_bundled
    if _seed_source is not None:
        path.write_bytes(_seed_source.read_bytes())
_SYNC_LOCK=threading.Lock()

st.markdown(r"""
<style>
:root{--bg:#050814;--panel:#0a1020;--line:#1d2b46;--muted:#98a4b8;--blue:#1687ff;--green:#28d06f;--red:#ff4f6d;--violet:#9c5cff;--gold:#ffcc33}
html,body,[class*="css"]{font-family:Inter,Pretendard,"Noto Sans KR",system-ui,-apple-system,sans-serif}
.stApp{background:radial-gradient(circle at 15% 0%,rgba(22,135,255,.12),transparent 28%),radial-gradient(circle at 88% 15%,rgba(156,92,255,.10),transparent 26%),linear-gradient(180deg,#050814 0%,#070b15 100%);color:#f5f7fb}
.block-container{max-width:1120px;padding-top:.45rem;padding-bottom:6.2rem}[data-testid="stHeader"]{background:transparent}#MainMenu,footer{visibility:hidden}
.hero-shell{position:relative;overflow:hidden;padding:1.2rem 1.25rem 1.05rem;border-radius:24px;background:linear-gradient(135deg,rgba(29,12,28,.96),rgba(7,14,31,.96));border:1px solid #263556;box-shadow:0 18px 42px rgba(0,0,0,.35),inset 0 1px 0 rgba(255,255,255,.05);margin:.2rem 0 1rem}
.hero-shell:before{content:"";position:absolute;inset:-40% 35% 35% -20%;background:radial-gradient(circle,rgba(255,60,110,.22),transparent 60%);pointer-events:none}.brand-row{display:flex;align-items:center;gap:.75rem;position:relative;z-index:1}
.brand-target{width:56px;height:56px;border-radius:50%;display:grid;place-items:center;font-size:2rem;background:radial-gradient(circle,#fff 0 12%,#e53b49 13% 27%,#fff 28% 40%,#c80f21 41% 59%,#650713 60% 100%);box-shadow:0 7px 20px rgba(255,50,80,.32),inset 0 0 0 2px rgba(255,255,255,.55)}
.brand-title{font-size:clamp(1.8rem,5vw,2.55rem);font-weight:1000;letter-spacing:-.045em;line-height:1;background:linear-gradient(180deg,#fff,#eef1f7 56%,#b8beca);-webkit-background-clip:text;color:transparent;text-shadow:0 8px 20px rgba(0,0,0,.24)}.brand-sub{position:relative;z-index:1;color:#aeb8c9;margin:.65rem 0 0;font-size:.93rem}
.sync-ok,.sync-warn{display:flex;align-items:center;gap:1rem;padding:1rem 1.15rem;border-radius:18px;margin:.55rem 0 1.15rem;font-weight:800}.sync-ok{background:linear-gradient(90deg,rgba(18,82,50,.44),rgba(6,27,25,.72));border:1px solid rgba(45,214,112,.38)}.sync-warn{background:linear-gradient(90deg,rgba(104,62,11,.38),rgba(40,26,8,.70));border:1px solid rgba(255,180,55,.38)}.sync-icon{font-size:1.6rem}.sync-main{font-size:1.28rem}.sync-detail{color:#d7deea;font-weight:650;font-size:1.12rem}
.section-head{display:flex;align-items:center;justify-content:space-between;gap:.75rem;margin:1.15rem 0 .65rem}.section-title{font-size:1.52rem;font-weight:950}.date-chip{font-size:1rem;color:#b8dcff;padding:.48rem .78rem;border-radius:12px;background:#0b2242;border:1px solid #174d87}
.lotto-row{display:flex;gap:.56rem;flex-wrap:wrap;align-items:center;margin:.55rem 0 1rem;padding:.28rem 0 .9rem;perspective:1000px}.ball{--c1:#FFF06A;--c2:#FFC400;--c3:#9A4E00;position:relative;width:70px;height:70px;flex:0 0 70px;border-radius:50%;display:inline-flex;align-items:center;justify-content:center;
background:
radial-gradient(ellipse at 25% 14%,#ffffff 0 4%,rgba(255,255,255,.98) 5% 10%,rgba(255,255,255,.40) 13%,transparent 27%),
radial-gradient(circle at 35% 30%,var(--c1) 0 16%,var(--c2) 46%,var(--c3) 100%);
border:2px solid rgba(255,255,255,.95);
box-shadow:
inset 12px 13px 18px rgba(255,255,255,.52),
inset -15px -18px 24px rgba(0,0,0,.62),
inset 0 0 0 2px rgba(255,255,255,.20),
0 11px 18px rgba(0,0,0,.60);
filter:saturate(1.65) contrast(1.14)}
.ball:before{content:"";position:absolute;left:8%;top:5%;width:52%;height:24%;border-radius:50%;
background:linear-gradient(168deg,#fff 0%,rgba(255,255,255,.98) 30%,rgba(255,255,255,.30) 68%,transparent 100%);
transform:rotate(-23deg);opacity:1;z-index:4;pointer-events:none}.ball:after{content:"";position:absolute;left:13%;right:13%;bottom:-10px;height:12px;border-radius:50%;background:radial-gradient(ellipse,rgba(0,0,0,.72) 0%,rgba(0,0,0,.36) 48%,transparent 78%);filter:blur(4px);z-index:-1;pointer-events:none}
.ball-num{position:relative;z-index:5;display:flex;align-items:center;justify-content:center;width:72%;height:72%;border-radius:50%;
font-size:2.08rem;font-weight:1000;line-height:1;letter-spacing:-.06em;color:#fff;
-webkit-text-stroke:1.6px #06080c;text-shadow:0 3px 2px rgba(0,0,0,.95),0 0 5px rgba(0,0,0,.78);
background:radial-gradient(circle at 40% 28%,rgba(255,255,255,.10),rgba(255,255,255,.01) 48%,rgba(0,0,0,.16) 100%);
box-shadow:inset 0 1px 2px rgba(255,255,255,.25),inset 0 -2px 4px rgba(0,0,0,.30)}
.b1{--c1:#FFF06A;--c2:#FFC400;--c3:#9A4E00}.b2{--c1:#61C8FF;--c2:#0066FF;--c3:#00165E}.b3{--c1:#FF7770;--c2:#F00000;--c3:#650000}.b4{--c1:#FFFFFF;--c2:#AEB4BC;--c3:#30363D}.b5{--c1:#70FF86;--c2:#00B935;--c3:#003D12}.bonus{width:76px;height:76px;flex-basis:76px;box-shadow:inset 10px 12px 18px rgba(255,255,255,.35),inset -14px -18px 23px rgba(0,0,0,.47),0 0 0 3px #ffbd28,0 0 0 6px rgba(255,220,88,.22),0 14px 22px rgba(0,0,0,.48)}.bonus .ball-num{font-size:2.12rem}.bonus-label{font-size:2rem;font-weight:1000;color:#eef2f8;margin:0 .08rem;text-shadow:0 3px 5px #000}
.legend{display:flex;gap:.9rem;flex-wrap:wrap;padding:.55rem .7rem;border-radius:14px;border:1px solid #1b2a43;background:#090f1b;margin:-.15rem 0 1rem;color:#d5dbe5;font-size:.78rem}.legend span{display:flex;align-items:center;gap:.32rem}.dot{width:11px;height:11px;border-radius:50%}
.kpi-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:.65rem;margin:.65rem 0 1.1rem}.kpi{position:relative;overflow:hidden;border-radius:17px;padding:1rem 1rem 1.08rem;border:1px solid #24334e;background:linear-gradient(145deg,#0c1423,#08101c);min-height:122px;box-shadow:0 12px 26px rgba(0,0,0,.22)}.kpi:before{content:"";position:absolute;inset:0;background:radial-gradient(circle at 10% 0%,rgba(25,132,255,.18),transparent 45%)}.kpi.purple:before{background:radial-gradient(circle at 10% 0%,rgba(158,77,255,.20),transparent 48%)}.kpi.red:before{background:radial-gradient(circle at 10% 0%,rgba(255,65,106,.20),transparent 48%)}.kpi-label{position:relative;color:#c9d2e1;font-size:1rem;font-weight:800}.kpi-value{position:relative;font-size:2.12rem;font-weight:950;margin-top:.58rem}.kpi-value.redv{color:#ff5c7a}.kpi-sub{position:relative;font-size:.88rem;color:#8f9bb0;margin-top:.18rem}
.menu-title{font-size:1.38rem;font-weight:950;margin:.7rem 0 .7rem}.menu-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:.65rem;margin-bottom:1.15rem}.menu-card{border:1px solid #243450;border-radius:17px;padding:1rem .7rem;text-align:center;background:linear-gradient(160deg,#0d1728,#08111f);box-shadow:0 10px 24px rgba(0,0,0,.22);min-height:132px}.menu-card.blue{border-color:#155aa4;background:linear-gradient(160deg,#0c315f,#07182d)}.menu-card.green{border-color:#2e6f31;background:linear-gradient(160deg,#153b18,#08190d)}.menu-card.orange{border-color:#8b5117;background:linear-gradient(160deg,#4b270d,#1b1006)}.menu-card.violet{border-color:#67318b;background:linear-gradient(160deg,#351449,#16091f)}.menu-icon{font-size:2.05rem}.menu-name{font-size:1.18rem;font-weight:950;margin-top:.38rem}.menu-desc{font-size:.86rem;color:#c1cad8;margin-top:.24rem}
[data-testid="stMetric"]{border:1px solid #24334e!important;border-radius:15px!important;background:linear-gradient(145deg,#0c1423,#08101c)!important;padding:.75rem!important;box-shadow:0 10px 22px rgba(0,0,0,.18)}[data-testid="stMetricLabel"]{color:#aeb8c8}[data-testid="stMetricValue"]{color:#f7f9fc}.stButton>button{border-radius:12px!important;font-weight:800!important;border:1px solid #2b4772!important;background:linear-gradient(180deg,#123f73,#0b284b)!important;color:#fff!important;min-height:2.7rem}.stButton>button:hover{border-color:#41a1ff!important;box-shadow:0 8px 20px rgba(15,115,220,.22)!important}
[data-baseweb="tab-list"]{gap:.32rem;background:#070d17;border:1px solid #1c2940;padding:.42rem;border-radius:14px;overflow-x:auto}button[data-baseweb="tab"]{height:3.25rem;border-radius:11px;padding:0 1rem;color:#a6b0c0;font-weight:850;font-size:1.02rem;white-space:nowrap}button[data-baseweb="tab"][aria-selected="true"]{color:#38a9ff;background:linear-gradient(180deg,#102f57,#0a1b34);box-shadow:inset 0 0 0 1px #235e99}
.game-card{padding:.72rem;border:1px solid #22314c;border-radius:16px;margin:.55rem 0;background:linear-gradient(145deg,#0c1423,#080f1a);box-shadow:0 10px 24px rgba(0,0,0,.19)}.game-title{font-weight:900;margin-bottom:.2rem;color:#dfe7f3}.md-score{color:#ff617f}.small-note{font-size:.78rem;color:#8490a3}.game-card .lotto-row{margin:.4rem 0 .55rem;padding-bottom:.55rem}
@media(max-width:768px){.sync-ok,.sync-warn{padding:.95rem .9rem;gap:.72rem}.sync-icon{font-size:1.45rem}.sync-main{font-size:1.13rem}.sync-detail{font-size:.98rem}.section-title{font-size:1.30rem}.date-chip{font-size:.88rem;padding:.45rem .62rem}.kpi{padding:.85rem .75rem;min-height:112px}.kpi-label{font-size:.9rem}.kpi-value{font-size:1.82rem}.kpi-sub{font-size:.78rem}.menu-title{font-size:1.28rem}.menu-card{padding:.85rem .45rem;min-height:116px}.menu-icon{font-size:1.82rem}.menu-name{font-size:1.02rem}.menu-desc{font-size:.76rem}button[data-baseweb="tab"]{height:3rem;font-size:.94rem;padding:0 .78rem}.block-container{padding-left:.66rem;padding-right:.66rem;padding-top:.3rem;padding-bottom:6.5rem}.hero-shell{padding:1rem .9rem;border-radius:21px}.brand-target{width:48px;height:48px;font-size:1.65rem}.brand-title{font-size:1.72rem}.brand-sub{font-size:.82rem}.section-title{font-size:1.12rem}.date-chip{font-size:.72rem}.lotto-row{gap:.38rem;flex-wrap:nowrap}.ball{width:53px;height:53px;flex-basis:53px}.ball-num{width:74%;height:74%;font-size:1.60rem;-webkit-text-stroke:1.15px rgba(3,6,12,.94)}.bonus{width:59px;height:59px;flex-basis:59px}.bonus .ball-num{font-size:1.72rem}.bonus-label{font-size:1.55rem}.legend{gap:.55rem;font-size:.67rem;padding:.48rem .52rem}.dot{width:9px;height:9px}.kpi-grid{gap:.45rem}.kpi{min-height:101px;padding:.72rem .62rem}.kpi-label{font-size:.72rem}.kpi-value{font-size:1.48rem}.kpi-sub{font-size:.65rem}.menu-grid{gap:.4rem}.menu-card{padding:.64rem .35rem}.menu-icon{font-size:1.35rem}.menu-name{font-size:.82rem}.menu-desc{font-size:.60rem}.game-card .ball{width:43px;height:43px;flex-basis:43px}.game-card .ball-num{font-size:1.31rem}.game-card .lotto-row{gap:.25rem;flex-wrap:nowrap}.game-title{font-size:.9rem}[data-testid="stMetric"]{padding:.6rem!important}h2{font-size:1.25rem!important}h3{font-size:1.06rem!important}div[data-testid="stDataFrame"]{font-size:.76rem}}
@media(max-width:390px){.ball{width:50px;height:50px;flex-basis:50px}.ball-num{font-size:1.52rem}.lotto-row{gap:.29rem}.bonus{width:56px;height:56px;flex-basis:56px}.bonus .ball-num{font-size:1.64rem}.kpi-value{font-size:1.36rem}.game-card .ball{width:40px;height:40px;flex-basis:40px}.game-card .ball-num{font-size:1.21rem}}
.v36-badge{display:inline-block;margin-left:.42rem;padding:.14rem .40rem;border-radius:999px;background:#FFD000;color:#111;font-size:.68rem;font-weight:1000;vertical-align:middle}

/* ===== v3.8 MOBILE ONE-ROW FIT + VIVID GLOSSBALL OVERRIDE ===== */
@media (max-width: 640px){
  .lotto-row{
    display:flex!important;
    flex-wrap:nowrap!important;
    width:100%!important;
    max-width:100%!important;
    gap:4px!important;
    justify-content:space-between!important;
    align-items:center!important;
    overflow:visible!important;
    padding:.28rem 0 .72rem!important;
    margin:.45rem 0 .75rem!important;
  }
  .lotto-row>.ball{
    width:calc((100% - 20px)/6)!important;
    height:auto!important;
    aspect-ratio:1/1!important;
    max-width:50px!important;
    min-width:0!important;
    flex:0 1 calc((100% - 20px)/6)!important;
    box-sizing:border-box!important;
    border-width:2px!important;
  }
  .lotto-row>.ball .ball-num{
    width:76%!important;
    height:76%!important;
    font-size:clamp(1.35rem,6.1vw,1.72rem)!important;
    -webkit-text-stroke:1.25px #06080c!important;
  }
  .lotto-row>.bonus{
    width:calc((100% - 24px)/7)!important;
    max-width:46px!important;
    flex-basis:calc((100% - 24px)/7)!important;
  }
  .bonus-label{
    font-size:1.2rem!important;
    margin:0!important;
  }
}
@media (max-width: 390px){
  .lotto-row{gap:3px!important}
  .lotto-row>.ball{
    width:calc((100% - 15px)/6)!important;
    max-width:47px!important;
    flex-basis:calc((100% - 15px)/6)!important;
  }
  .lotto-row>.ball .ball-num{
    font-size:clamp(1.28rem,5.8vw,1.58rem)!important;
  }
}
/* Remove muted filter effects from the balls only */
.ball.b1,.ball.b2,.ball.b3,.ball.b4,.ball.b5{
  filter:saturate(1.75) contrast(1.15)!important;
}

.compact-audit-row{display:grid;grid-template-columns:repeat(3,1fr);gap:.55rem;margin:.45rem 0 .7rem}
.compact-audit{display:flex;align-items:center;justify-content:space-between;gap:.6rem;padding:.58rem .72rem;border:1px solid #24334e;border-radius:12px;background:#0a111e;min-height:54px}
.compact-audit span{font-size:.76rem;color:#9ea9ba;font-weight:700}.compact-audit b{font-size:.94rem;color:#f4f7fb;white-space:nowrap}
@media(max-width:768px){.compact-audit-row{gap:.35rem}.compact-audit{padding:.5rem .48rem;min-height:50px;display:block}.compact-audit span{display:block;font-size:.68rem}.compact-audit b{display:block;font-size:.86rem;margin-top:.16rem}}
</style>
""",unsafe_allow_html=True)

def ball_class(n): return 'b1' if n<=10 else 'b2' if n<=20 else 'b3' if n<=30 else 'b4' if n<=40 else 'b5'
def balls_html(nums,bonus=None):
    parts=[f'<span class="ball {ball_class(int(n))}"><span class="ball-num">{int(n)}</span></span>' for n in nums]
    if bonus is not None: parts += ['<span class="bonus-label">+</span>',f'<span class="ball {ball_class(int(bonus))} bonus"><span class="ball-num">{int(bonus)}</span></span>']
    return '<div class="lotto-row">'+''.join(parts)+'</div>'
def pct(v,d=2):
    try:return f'{float(v)*100:.{d}f}%'
    except:return '-'

def _xlsx_col_letter(n):
    s=''
    while n:
        n,rem=divmod(n-1,26)
        s=chr(65+rem)+s
    return s

def _xlsx_inline_cell(ref, value, style=0):
    if value is None or (isinstance(value,float) and pd.isna(value)):
        return f'<c r="{ref}" s="{style}"/>'
    if isinstance(value,(int,float)) and not isinstance(value,bool):
        return f'<c r="{ref}" s="{style}"><v>{value}</v></c>'
    txt=_xml_escape(str(value))
    return f'<c r="{ref}" t="inlineStr" s="{style}"><is><t>{txt}</t></is></c>'

def _history_xlsx_bytes(history_df, status_dict):
    d=history_df[['draw_no','draw_date','n1','n2','n3','n4','n5','n6','bonus']].copy()
    d=d.sort_values('draw_no').reset_index(drop=True)
    d['draw_date']=pd.to_datetime(d['draw_date']).dt.strftime('%Y-%m-%d')
    headers=['회차','추첨일','번호1','번호2','번호3','번호4','번호5','번호6','보너스']

    def sheet_xml(rows, widths, freeze=True, autofilter=None):
        max_cols=max(len(r) for r in rows)
        max_rows=len(rows)
        cols=''.join(
            f'<col min="{i}" max="{i}" width="{w}" customWidth="1"/>'
            for i,w in enumerate(widths,1)
        )
        xml_rows=[]
        for ri,row in enumerate(rows,1):
            cells=[]
            for ci,val in enumerate(row,1):
                style=1 if ri==1 else 0
                cells.append(_xlsx_inline_cell(f'{_xlsx_col_letter(ci)}{ri}',val,style))
            xml_rows.append(f'<row r="{ri}">'+''.join(cells)+'</row>')
        pane='<pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/>' if freeze else ''
        filt=f'<autoFilter ref="{autofilter}"/>' if autofilter else ''
        return ('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
                '<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">'
                f'<dimension ref="A1:{_xlsx_col_letter(max_cols)}{max_rows}"/>'
                f'<sheetViews><sheetView workbookViewId="0">{pane}</sheetView></sheetViews>'
                '<sheetFormatPr defaultRowHeight="18"/>'
                f'<cols>{cols}</cols><sheetData>{"".join(xml_rows)}</sheetData>{filt}</worksheet>')

    history_rows=[headers]
    for _,r in d.iterrows():
        history_rows.append([
            int(r.draw_no), str(r.draw_date),
            int(r.n1),int(r.n2),int(r.n3),int(r.n4),int(r.n5),int(r.n6),int(r.bonus)
        ])

    expected=list(range(1,int(d.draw_no.max())+1)) if len(d) else []
    actual=d.draw_no.astype(int).tolist()
    missing=sorted(set(expected)-set(actual))
    duplicate_count=int(d.draw_no.duplicated().sum())
    invalid_number_rows=0
    for _,r in d.iterrows():
        nums=[int(r[f'n{i}']) for i in range(1,7)]
        if len(set(nums))!=6 or not all(1<=x<=45 for x in nums) or int(r.bonus) in nums or not 1<=int(r.bonus)<=45:
            invalid_number_rows+=1

    audit_rows=[
        ['검증항목','결과'],
        ['파일 목적','MD LOTTO 앱이 실제 사용하는 전체 당첨이력 확인용'],
        ['최소 회차',int(d.draw_no.min()) if len(d) else '-'],
        ['최신 회차',int(d.draw_no.max()) if len(d) else '-'],
        ['총 데이터 행',int(len(d))],
        ['1회부터 연속 데이터','정상' if bool(status_dict.get('complete_from_draw1')) else '미완료'],
        ['누락 회차 수',len(missing)],
        ['누락 회차','없음' if not missing else ', '.join(map(str,missing[:100]))],
        ['중복 회차 수',duplicate_count],
        ['번호/보너스 유효성 오류 행',invalid_number_rows],
        ['최신 추첨일',str(status_dict.get('latest_date') or '-')],
        ['주의','이 파일은 앱 내부 분석에 사용되는 현재 데이터의 복사본입니다. 추천 확률을 의미하지 않습니다.'],
    ]

    content_types='''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/worksheets/sheet2.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/><Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/><Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/></Types>'''
    root_rels='''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/></Relationships>'''
    workbook='''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="전체 당첨이력" sheetId="1" r:id="rId1"/><sheet name="데이터 검증" sheetId="2" r:id="rId2"/></sheets></workbook>'''
    wb_rels='''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet2.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>'''
    styles='''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="10"/><name val="Arial"/></font><font><b/><color rgb="FFFFFFFF"/><sz val="10"/><name val="Arial"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF17365D"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border><left/><right/><top/><bottom/><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="2"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1"><alignment horizontal="center"/></xf></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>'''
    core='''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:title>MD LOTTO 전체 당첨이력 검증</dc:title><dc:creator>MD LOTTO</dc:creator></cp:coreProperties>'''
    app_xml='''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties"><Application>MD LOTTO</Application></Properties>'''

    s1=sheet_xml(history_rows,[10,14,9,9,9,9,9,9,9],True,f'A1:I{len(history_rows)}')
    s2=sheet_xml(audit_rows,[25,65],True,None)

    out=BytesIO()
    with ZipFile(out,'w',ZIP_DEFLATED) as z:
        z.writestr('[Content_Types].xml',content_types)
        z.writestr('_rels/.rels',root_rels)
        z.writestr('docProps/core.xml',core)
        z.writestr('docProps/app.xml',app_xml)
        z.writestr('xl/workbook.xml',workbook)
        z.writestr('xl/_rels/workbook.xml.rels',wb_rels)
        z.writestr('xl/styles.xml',styles)
        z.writestr('xl/worksheets/sheet1.xml',s1)
        z.writestr('xl/worksheets/sheet2.xml',s2)
    return out.getvalue()

def render_backtest_summary(s):
    c=st.columns(4); c[0].metric('테스트 회차',f"{int(s.get('tests',0)):,}"); c[1].metric('MD 평균 최고 적중',f"{s.get('md_best_mean',0):.2f}개"); c[2].metric('랜덤 평균 최고 적중',f"{s.get('random_div_best_mean',0):.2f}개"); c[3].metric('우위 근거','있음' if s.get('evidence_of_edge') else '없음')
    st.caption(f"승 {s.get('head_to_head_wins',0)} · 패 {s.get('losses',0)} · 무 {s.get('ties',0)} · Sign test p={s.get('sign_test_p_value',1):.4f}")
    if 'md_realized_roi' in s:
        a,b,c=st.columns(3); a.metric('총 구매비',f"₩{s.get('md_total_cost',0):,.0f}"); b.metric('과거 지급액',f"₩{s.get('md_total_payout',0):,.0f}"); c.metric('과거 ROI',pct(s.get('md_realized_roi',0),1))

@st.cache_data(ttl=1800,show_spinner=False)
def cloud_sync_tick(_bucket):
    with _SYNC_LOCK:
        try:
            d,ss=sync_history(path,verify_official_count=3); save_sqlite(d,db); save_sync_status(ss,sp); return ss
        except Exception as e:return {'ok':False,'error':str(e),'using_cached_data':path.exists()}

@st.cache_data(show_spinner=False, max_entries=10)
def cached_mobile_backtest(latest_draw, tests):
    _df=load_csv(path)
    return walk_forward(_df,start_train=300,max_tests=tests,sample_combos=1500,random_reps=50)

@st.cache_data(show_spinner=False, max_entries=6)
def cached_recommendation_diagnostics(latest_draw, tests, games, sample_combos):
    _df=load_csv(path)
    return recommendation_actual_diagnostics(
        _df,start_train=300,max_tests=tests,games=games,
        sample_combos=sample_combos,pool_size=20,max_overlap=3
    )

@st.cache_data(show_spinner=False, max_entries=8)
def cached_mobile_ml_holdout(latest_draw):
    return train_evaluate(load_csv(path))

@st.cache_data(show_spinner=False, max_entries=8)
def cached_mobile_ml_walk_forward(latest_draw, tests):
    return walk_forward_ml(load_csv(path),start_train=300,max_tests=tests)

# SAFE BOOT: render immediately from embedded/validated local history.
# External sync is manual so a slow/blocked network can never leave the app blank.
if not path.exists():
    st.error('내장 데이터 파일을 준비하지 못했습니다. 앱을 다시 배포해 주세요.')
    st.stop()
df=load_csv(path)

# v4.0 DATA RECOVERY:
# 1) On a fresh runtime, restore full 1..latest history when possible.
# 2) Then check official local_max+1 for newly published draws.
if not st.session_state.get('_full_history_checked_v58'):
    st.session_state['_full_history_checked_v58']=True
    if len(df) and int(df.draw_no.min())>1:
        try:
            with st.spinner('전체 회차 데이터를 복구·동기화하는 중입니다...'):
                df,_full_status=sync_history(path,verify_official_count=2)
                st.session_state['startup_sync_status']=_full_status
                save_sync_status(_full_status,sp)
        except Exception as _e:
            st.session_state['startup_sync_status']={'ok':False,'error':str(_e),'using_cached_data':True}

if not st.session_state.get('_official_incremental_checked_v58'):
    st.session_state['_official_incremental_checked_v58']=True
    try:
        df,_inc_status=sync_incremental_official(path,max_new=6,timeout=5)
        st.session_state['incremental_sync_status']=_inc_status
    except Exception as _e:
        st.session_state['incremental_sync_status']={'ok':False,'error':str(_e)}

df=load_csv(path)
status=dataset_status(df)
ns=number_stats(df)
latest=df.iloc[-1]

# Invalidate results that were created for a previous draw.
_current_draw=int(latest.draw_no)
_previous_basis=st.session_state.get('_analysis_basis_draw_v58')
if _previous_basis is not None and int(_previous_basis)!=_current_draw:
    for _k in ('md_games','md_recommendation_record','last_bt','corr_reg_diag','sim_optimizer_result','md_sim_final_games'):
        st.session_state.pop(_k,None)
st.session_state['_analysis_basis_draw_v58']=_current_draw

ss=st.session_state.get('startup_sync_status') or load_sync_status(sp) or {'ok':True,'using_cached_data':True}
nums=[int(latest[f'n{i}']) for i in range(1,7)]; bonus=int(latest.bonus)

st.markdown('<div class="hero-shell"><div class="brand-row"><div class="brand-target">🎯</div><div class="brand-title">MD LOTTO 6/45 <span class="v36-badge">v5.8 INTEGRATED</span></div></div><div class="brand-sub">과거 데이터·확률·조합 최적화를 연구하는 개인용 분석 도구</div></div>',unsafe_allow_html=True)
if ss.get('ok') and status.get('complete_from_draw1'):
    st.markdown(f'<div class="sync-ok"><span class="sync-icon">✅</span><span class="sync-main">전체 데이터 정상</span><span class="sync-detail">· 1회 ~ {status.get("max_draw")}회 · 연속성 확인</span></div>',unsafe_allow_html=True)
elif not status.get('complete_from_draw1'):
    st.markdown(f'<div class="sync-warn"><span class="sync-icon">⚠️</span><span class="sync-main">전체이력 복구 필요</span><span class="sync-detail">· 현재 {status.get("min_draw")}회 ~ {status.get("max_draw")}회만 보유 · 추천 잠금</span></div>',unsafe_allow_html=True)
else:
    st.markdown('<div class="sync-warn"><span class="sync-icon">⚠️</span><span class="sync-main">온라인 최신 확인 실패</span><span class="sync-detail">· 저장된 전체 검증 데이터를 사용 중입니다.</span></div>',unsafe_allow_html=True)
st.markdown(f'<div class="section-head"><div class="section-title">🏆 제 {int(latest.draw_no)}회 최신 당첨번호</div><div class="date-chip">추첨일 {latest.draw_date.strftime("%Y-%m-%d")}</div></div>',unsafe_allow_html=True)
st.markdown(balls_html(nums,bonus),unsafe_allow_html=True)
st.markdown('<div class="legend"><span><i class="dot" style="background:#f2b400"></i>1-10</span><span><i class="dot" style="background:#1687ff"></i>11-20</span><span><i class="dot" style="background:#ed3547"></i>21-30</span><span><i class="dot" style="background:#9da2aa"></i>31-40</span><span><i class="dot" style="background:#38b44b"></i>41-45</span><span><i class="dot" style="background:#ed3547"></i>보너스</span></div>',unsafe_allow_html=True)
st.markdown(f'<div class="kpi-grid"><div class="kpi"><div class="kpi-label">📊 분석 회차</div><div class="kpi-value">{len(df):,}</div><div class="kpi-sub">총 분석 데이터</div></div><div class="kpi purple"><div class="kpi-label">🗓️ 최신 회차</div><div class="kpi-value">{int(latest.draw_no)}회</div><div class="kpi-sub">가장 최근 회차</div></div><div class="kpi red"><div class="kpi-label">📅 최신 추첨일</div><div class="kpi-value redv" style="font-size:1.28rem">{latest.draw_date.strftime("%Y-%m-%d")}</div><div class="kpi-sub">자동 동기화 기준</div></div></div>',unsafe_allow_html=True)
st.markdown('<div class="menu-title">✨ 주요 분석 메뉴</div><div class="menu-grid"><div class="menu-card blue"><div class="menu-icon">🎲</div><div class="menu-name">번호 추천</div><div class="menu-desc">최적 번호 조합</div></div><div class="menu-card green"><div class="menu-icon">📊</div><div class="menu-name">FDR 분석</div><div class="menu-desc">패턴·확률 검증</div></div><div class="menu-card orange"><div class="menu-icon">🎯</div><div class="menu-name">백테스트</div><div class="menu-desc">과거 성과 검증</div></div><div class="menu-card violet"><div class="menu-icon">🧠</div><div class="menu-name">AI 진단</div><div class="menu-desc">종합 인사이트</div></div></div>',unsafe_allow_html=True)


st.markdown('### 📥 전체 당첨이력 직접 검증')
if status.get('complete_from_draw1'):
    _audit_xlsx=_history_xlsx_bytes(df,status)
    _xlsx_name=f'MD_LOTTO_1_to_{int(status["max_draw"])}_history_audit.xlsx'
    st.download_button(
        '📊 1회~최신회차 전체 데이터 Excel 다운로드',
        data=_audit_xlsx,
        file_name=_xlsx_name,
        mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        use_container_width=True
    )
    st.caption(f'Excel에 1회~{int(status["max_draw"])}회 전체 당첨번호와 별도 「데이터 검증」 시트가 포함됩니다. 총 {int(status["draws"]):,}회 · 누락 없음.')
else:
    st.warning('현재는 전체 1회~최신회차 이력이 복구되지 않아 Excel 다운로드를 잠갔습니다. 불완전 데이터를 전체 데이터처럼 보여주지 않기 위한 안전장치입니다.')
    st.caption('사이드바 → 「🔄 지금 최신 데이터 확인」 실행 후 전체이력 정상 표시가 나오면 다운로드 버튼이 활성화됩니다.')

with st.sidebar:
    st.header('데이터 관리')
    if status.get('complete_from_draw1') and ss.get('ok'):
        st.success(f"1회~{status.get('max_draw')}회 전체이력 확인")
    elif status.get('complete_from_draw1'):
        st.warning(f"저장된 1회~{status.get('max_draw')}회 사용 중 · 온라인 확인 실패")
    else:
        st.error(f"전체이력 미완료 · {status.get('min_draw')}~{status.get('max_draw')}회")
    st.caption('연속 전체이력 정상' if status.get('complete_from_draw1') else '추천 전 전체이력 복구가 필요합니다.')
    if st.button('🔄 지금 최신 데이터 확인',use_container_width=True):
        with st.spinner('전체 회차와 최신 회차를 확인하는 중입니다...'):
            try:
                _df,_st=sync_history(path,verify_official_count=2)
                st.session_state['startup_sync_status']=_st
                save_sync_status(_st,sp)
                _df,_inc=sync_incremental_official(path,max_new=6,timeout=6)
                st.session_state['incremental_sync_status']=_inc
                for _k in ('md_games','md_recommendation_record','last_bt','corr_reg_diag'):
                    st.session_state.pop(_k,None)
            except Exception as _e:
                st.session_state['startup_sync_status']={'ok':False,'error':str(_e),'using_cached_data':True}
        st.rerun()
    st.caption('동기화 실패 시 기존 검증 데이터는 보존됩니다.')
if not status['complete_from_draw1']: st.error(f"현재 데이터는 {status['min_draw']}~{status['max_draw']}회({status['draws']}회분)만 있습니다. 전체 1회~최신회차 복구 전에는 추천·시뮬레이션을 잠급니다.")

tabs=st.tabs(['🏠 대시보드','🎲 번호 추천','📊 FDR 분석','🏆 백테스트','🧠 AI 진단','🔎 오차 진단'])
with tabs[0]:
    st.subheader('데이터·무작위성 진단'); audit=randomness_audit(df); struct=structure_summary(df)
    st.markdown(
        f'''<div class="compact-audit-row">
        <div class="compact-audit"><span>전체 회차</span><b>{status['draws']:,}</b></div>
        <div class="compact-audit"><span>연속 데이터</span><b>{'정상' if status['contiguous'] else '점검 필요'}</b></div>
        <div class="compact-audit"><span>균등성 검정</span><b>{'특이점 없음' if audit.get('p_value',0)>=.05 else '검토 필요'}</b></div>
        </div>''',
        unsafe_allow_html=True
    )
    st.caption(f"번호합 평균 {struct.get('sum_mean',0):.1f} · 10~90% 범위 {struct.get('sum_q10',0):.0f}~{struct.get('sum_q90',0):.0f} · 흔한 홀수 개수 {struct.get('odd_mode','-')}개")
    _lr=latest_transition_report(df)
    if _lr.get('available'):
        st.info(f"최근 {_lr['previous_draw']}회→{_lr['current_draw']}회 변화: 직전번호 재등장 {int(_lr['current_features']['overlap_prev'])}개 · 연속수 {int(_lr['current_features']['consecutive_pairs'])}쌍 · 번호합 {int(_lr['previous_features']['sum'])}→{int(_lr['current_features']['sum'])}")

    _today=pd.Timestamp.now(tz='Asia/Seoul').tz_localize(None).normalize()
    _one_year_ago=_today-pd.Timedelta(days=365)
    _recent=df[(df['draw_date']>=_one_year_ago)&(df['draw_date']<=_today)].copy()
    _counts={n:0 for n in range(1,46)}
    for _,_r in _recent.iterrows():
        for _i in range(1,7):
            _counts[int(_r[f'n{_i}'])]+=1
    _chart=pd.DataFrame({'번호':list(range(1,46)),'최근 1년 출현':[_counts[n] for n in range(1,46)]})
    _chart['번호대']=_chart['번호'].map(lambda n:'1-10' if n<=10 else '11-20' if n<=20 else '21-30' if n<=30 else '31-40' if n<=40 else '41-45')
    st.markdown('#### 최근 1년 번호별 출현 빈도')
    st.caption(f"{_one_year_ago.strftime('%Y-%m-%d')} ~ {_today.strftime('%Y-%m-%d')} · 본번호 6개 기준 · 번호대별 색상 적용")
    _color_map={'1-10':'#F2B400','11-20':'#4F7FEA','21-30':'#D84C5A','31-40':'#AEB4BC','41-45':'#63B35D'}
    fig=px.bar(_chart,x='번호',y='최근 1년 출현',color='번호대',color_discrete_map=_color_map,category_orders={'번호대':['1-10','11-20','21-30','31-40','41-45']},hover_data={'번호':True,'최근 1년 출현':True,'번호대':True})
    fig.update_layout(margin=dict(l=0,r=0,t=15,b=0),height=350,paper_bgcolor='rgba(0,0,0,0)',plot_bgcolor='rgba(0,0,0,0)',font_color='#aeb8c8',legend_title_text='번호대',xaxis=dict(dtick=1),yaxis_title='출현 횟수')
    st.plotly_chart(fig,use_container_width=True)
with tabs[1]:
    _adj=next_draw_adjustment_report(df)
    if _adj.get('available'):
        _tr=_adj['transition']; _pf=_adj.get('profile',{})
        st.markdown('### 🔁 전회차 대비 변화와 다음회차 보완')
        st.caption(f"{_tr['previous_draw']}회 → {_tr['current_draw']}회 실제 당첨번호 변화 분석")
        _cols=st.columns(4)
        _cols[0].metric('직전번호 재등장',f"{int(_tr['current_features']['overlap_prev'])}개")
        _cols[1].metric('연속수 Pair',f"{int(_tr['current_features']['consecutive_pairs'])}쌍")
        _cols[2].metric('번호합',f"{int(_tr['current_features']['sum'])}")
        _cols[3].metric('홀수',f"{int(_tr['current_features']['odd'])}개")
        with st.expander('무엇이 달라졌고 다음 회차에 어떻게 반영하는지 보기'):
            for _line in _tr.get('explanations',[]): st.write('• '+_line)
            st.markdown('**다음회차 보완책**')
            for _line in _adj.get('actions',[]): st.write('→ '+_line)
            _cg=_tr.get('current_consecutive_gap',0); _ag=_tr.get('historical_consecutive_avg_gap')
            if pd.notna(_ag): st.caption(f"연속수 과거 평균 출현간격 약 {_ag:.1f}회 · 현재 연속수 미출현 간격 {_cg}회")
    subt=st.tabs(['추천 조합','번호 분석','시뮬레이션'])
    with subt[0]:
        st.info('패턴 인텔리전스 모드: 전체 과거패턴 + 최근 회차 변화 + 연속수 주기 + 유사상태 다음회차 흐름을 종합해 우선순위 5조합만 제시합니다.')
        if st.button('🎯 이번 회차 우선순위 5조합 만들기',type='primary',use_container_width=True):
            if not status.get('complete_from_draw1'):
                st.error('전체 과거회차 데이터가 아직 복구되지 않았습니다. 21개 내장 Seed만으로는 패턴이 왜곡될 수 있어 추천을 중단합니다. 사이드바의 「지금 최신 데이터 확인」으로 전체 회차를 먼저 복구해 주세요.')
            else:
                with st.spinner('과거 전체패턴과 최근 회차 변화까지 종합 분석하는 중...'):
                    st.session_state['md_games']=adaptive_priority_five(df,ns,pool_size=20,max_overlap=3)
                    st.session_state['md_recommendation_record']={
                        'target_draw':int(latest.draw_no)+1,
                        'created_from_draw':int(latest.draw_no),
                        'games':[list(map(int,c)) for c in st.session_state['md_games'].combo.tolist()],
                        'mode':'V5_8_INTEGRATED_PRIORITY5'
                    }
        games=st.session_state.get('md_games')
        _rec_basis=st.session_state.get('md_recommendation_record') or {}
        if games is not None and len(games) and int(_rec_basis.get('created_from_draw',-1))!=int(latest.draw_no):
            st.session_state.pop('md_games',None)
            st.session_state.pop('md_recommendation_record',None)
            games=None
            st.info('새 당첨회차가 반영되어 이전 추천은 자동 폐기했습니다. 이번 회차 기준으로 다시 생성해 주세요.')
        if games is not None and len(games):
            for i,row in games.iterrows():
                _scenario=str(row.get('scenario',f'{i+1}순위'))
                _reason=str(row.get('reason','전체 패턴 종합'))
                st.markdown(
                    f'<div class="game-card"><div class="game-title">{int(row.get("rank",i+1))}순위 · {_scenario} '
                    f'<span class="md-score">· 종합평가 {float(row.get("priority_score",0)):.1f}</span></div>'
                    f'{balls_html(row.combo)}'
                    f'<div class="small-note">{_reason}</div></div>',
                    unsafe_allow_html=True
                )
            st.caption(f"분석 후보 조합 수: {int(games.attrs.get('evaluated_combinations',0)):,}개 · 최종 제안은 5조합")
            st.caption('※ 순위는 과거 패턴을 참고한 프로그램 내부 우선순위이며 실제 당첨확률 순위가 아닙니다.')
        else: st.info('「이번 회차 우선순위 5조합 만들기」를 누르세요.')
    with subt[1]:
        view=ns[['number','count_all','count_20','count_50','count_100','count_300','current_gap','mean_gap','z_score']].copy(); view.columns=['번호','전체','최근20','최근50','최근100','최근300','현재 미출현','평균 간격','Z-score']; st.dataframe(view,use_container_width=True,hide_index=True); st.caption('Hot/Cold와 Gap은 과거 상태를 설명할 뿐 “나올 차례”를 의미하지 않습니다.')
    with subt[2]:
        st.info('목표: 5조합 모두가 3개 미만으로 끝나는 「시뮬레이션 미당첨률」을 후보공간 안에서 가능한 한 낮추는 조합을 찾습니다. 후보 수와 반복 횟수를 단계적으로 늘리고, 개선이 멈추면 자동 종료합니다.')
        if st.button('🧠 통합 최적화 시뮬레이션 실행',use_container_width=True,type='primary'):
            if not status.get('complete_from_draw1'):
                st.error('전체 과거회차 복구 후 실행해 주세요.')
            else:
                with st.spinner('FDR 패턴검증 → 백테스트 → AI 진단 → 후보확대 → 미당첨률 최소화 탐색 중...'):
                    _fdr=fdr_summary(df)
                    _bt=cached_mobile_backtest(int(latest.draw_no),30)
                    _bts=summarize_backtest(_bt) if _bt is not None and len(_bt) else {}
                    _ml=cached_mobile_ml_holdout(int(latest.draw_no))

                    # FDR/백테스트/AI는 번호를 "확정"하지 않고 과적합 방지용 검증 게이트로 사용.
                    _evidence={
                        'fdr_pair_sig':int(_fdr.get('pair_fdr_significant',0)),
                        'fdr_triple_sig':int(_fdr.get('triple_fdr_significant',0)),
                        'backtest':_bts,
                        'ml':_ml,
                    }
                    _batches=[]
                    for _n in (24,36,48):
                        _cdf=deterministic_top_games(df,ns,games=_n,pool_size=22,max_overlap=5)
                        _batches.append(_cdf.combo.tolist())
                    _simopt=converge_min_miss_portfolio(_batches,ns,stages=(10000,25000,50000),max_overlap=3)
                    _simopt['evidence']=_evidence
                    st.session_state['sim_optimizer_result']=_simopt
                    # 최종 추천 화면에서도 통합 최적화 결과를 사용할 수 있게 연결.
                    st.session_state['md_sim_final_games']=[list(g) for g in _simopt['selected_games']]

        _so=st.session_state.get('sim_optimizer_result')
        if _so:
            st.markdown('### 🎯 통합 분석이 선택한 최종 5조합')
            for _i,_g in enumerate(_so['selected_games'],1):
                st.markdown(f'<div class="game-card"><div class="game-title">{_i}순위 · 통합 최적화</div>{balls_html(_g)}<div class="small-note">FDR·백테스트·AI 진단은 과적합 검증에 사용하고, 최종 선택은 반복 시뮬레이션의 3개+ 커버리지와 조합 분산을 기준으로 결정</div></div>',unsafe_allow_html=True)

            _miss=100*_so['miss_rate_pattern']; _fairmiss=100*_so['miss_rate_fair']
            _c=st.columns(3)
            _c[0].metric('패턴모델 미당첨률',f'{_miss:.2f}%')
            _c[1].metric('패턴모델 3개+ 커버리지',f"{100*_so['pattern_model']['any3plus']:.2f}%")
            _c[2].metric('패턴모델 4개+ 커버리지',f"{100*_so['pattern_model']['any4plus']:.2f}%")
            st.markdown('#### 🔄 자동 반복 최적화 과정')
            _hist=pd.DataFrame(_so.get('convergence_history',[]))
            if len(_hist):
                _hist['미당첨률(패턴)']=_hist['miss_rate_pattern'].map(lambda x:f'{100*x:.2f}%')
                _hist['3개+']=_hist['any3plus_pattern'].map(lambda x:f'{100*x:.2f}%')
                _hist['4개+']=_hist['any4plus_pattern'].map(lambda x:f'{100*x:.3f}%')
                st.dataframe(_hist[['stage','simulations','candidate_count','미당첨률(패턴)','3개+','4개+']].rename(columns={'stage':'단계','simulations':'가상추첨','candidate_count':'후보조합'}),use_container_width=True,hide_index=True)
            st.success(f"자동 종료 기준: {_so.get('stopping_reason','탐색 완료')}")

            _ev=_so.get('evidence',{})
            st.markdown('#### 🔬 FDR · 백테스트 · AI가 하는 역할')
            st.write(f"**FDR 분석:** 우연한 Pair/Triple 패턴을 걸러냅니다. 현재 FDR 유의 Pair {_ev.get('fdr_pair_sig',0)}개, Triple {_ev.get('fdr_triple_sig',0)}개.")
            _ml=_ev.get('ml') or {}
            if _ml.get('available'):
                st.write(f"**AI 진단:** 시간순 Holdout으로 과거패턴 모델의 일반화 여부를 검사합니다. AUC {_ml.get('roc_auc_out_of_sample',0):.3f}, 기본모델보다 Log-loss 우수: {'예' if _ml.get('beats_constant_logloss') else '아니오'}.")
            else:
                st.write('**AI 진단:** 현재 데이터 조건에서 유효한 Holdout 결과가 없어 번호 가중치를 강화하지 않았습니다.')
            st.write('**백테스트:** 과거 각 시점에서 미래 데이터를 보지 않고 추천전략을 재현해 랜덤 대비 성과가 지속되는지 검사합니다. 성과가 약하면 해당 패턴을 당첨확률 상승 근거로 과대평가하지 않습니다.')
            st.caption(f"공정 무작위 모델에서 같은 5조합의 3개+ 미적중률은 이번 시뮬레이션에서 약 {_fairmiss:.2f}%였습니다. 이는 번호 선택으로 1등의 수학적 확률을 높였다는 뜻이 아닙니다.")
            st.metric('5게임 1등 이론확률',f"1 / {round(1/_so['theoretical_first_probability_5tickets']):,}")
            st.warning('중요: 로또 추첨이 공정하고 독립적이라면 서로 다른 5게임의 1등 이론확률은 번호 구성과 무관하게 동일합니다. 여기서 최소화하는 “미당첨률”은 연구용 시뮬레이션 목적함수이며 실제 미래 당첨확률 보장이 아닙니다.')
with tabs[2]:
    st.info('FDR은 우연히 자주 나온 Pair·Triple을 걸러 과적합을 줄이는 검증 게이트입니다. 통합 시뮬레이션이 약한 패턴을 당첨확률 상승 근거로 오인하지 않도록 사용합니다.')
    if st.button('🔬 전체 FDR 검정 실행',use_container_width=True):
        with st.spinner('검정 중...'): f=fdr_summary(df)
        c=st.columns(4); c[0].metric('Pair 검사',f"{f.get('pair_tests',0):,}"); c[1].metric('Pair 유의',f"{f.get('pair_fdr_significant',0):,}"); c[2].metric('Triple 검사',f"{f.get('triple_tests',0):,}"); c[3].metric('Triple 유의',f"{f.get('triple_fdr_significant',0):,}")
    ps=pair_stats(df,with_tests=True).head(50).copy(); ps['번호쌍']=ps.apply(lambda r:f"{int(r.a):02d}-{int(r.b):02d}",axis=1); st.dataframe(ps[['번호쌍','count','expected','lift','fdr_q_value']].rename(columns={'count':'출현','expected':'기대','lift':'배율','fdr_q_value':'FDR q'}),use_container_width=True,hide_index=True)
    ts=triple_stats(df,min_count=2,with_tests=True).head(50).copy(); ts['번호 3개']=ts.apply(lambda r:f"{int(r.a):02d}-{int(r.b):02d}-{int(r.c):02d}",axis=1); st.dataframe(ts[['번호 3개','count','expected','fdr_q_value']].rename(columns={'count':'출현','expected':'기대','fdr_q_value':'FDR q'}),use_container_width=True,hide_index=True)
with tabs[3]:
    st.info('백테스트는 과거 시점별로 추천전략을 재현해 미래정보 누출 없이 검증합니다. 랜덤 대비 우위가 반복되지 않으면 그 전략을 최종 추천의 강한 근거로 사용하지 않습니다.')
    btabs=st.tabs(['일반 백테스트','고급 검증','ROI'])
    with btabs[0]:
        tests=st.slider('최근 테스트 회차',10,150,30,10,key='bt_tests')
        if st.button('📈 백테스트 실행',use_container_width=True):
            with st.spinner('검증 중...'): st.session_state['last_bt']=cached_mobile_backtest(int(latest.draw_no),tests)
        bt=st.session_state.get('last_bt');
        if bt is not None and len(bt): render_backtest_summary(summarize_backtest(bt)); st.caption('우위 근거가 없으면 랜덤보다 낫다고 해석하지 않습니다.')
    with btabs[1]:
        mode=st.radio('검증 방식',['Nested Walk-forward','Strategy Tournament'],horizontal=True)
        if mode=='Nested Walk-forward':
            nt=st.slider('Outer 테스트 회차',5,40,12,key='nested_tests')
            if st.button('🧪 Nested 검증 실행',use_container_width=True):
                with st.spinner('검증 중...'): bt=nested_walk_forward(df,start_train=360,max_tests=nt,inner_draws=16,sample_combos=1000,random_reps=60)
                render_backtest_summary(summarize_backtest(bt)); st.dataframe(bt,use_container_width=True,hide_index=True)
        elif st.button('🏁 전략 토너먼트 실행',use_container_width=True):
            with st.spinner('전략 비교 중...'): tour=strategy_tournament(df,start_train=300,max_tests=30,sample_combos=1400)
            st.dataframe(tour,use_container_width=True,hide_index=True)
    with btabs[2]:
        if status.get('has_prize_data'):
            st.info('실제 과거 등위별 당첨금을 이용한 연구용 백테스트입니다. 미래 수익을 보장하지 않습니다.')
            if st.button('💰 ROI 백테스트 실행',use_container_width=True):
                with st.spinner('계산 중...'): bt=walk_forward(df,start_train=300,max_tests=50,sample_combos=1800,random_reps=80)
                render_backtest_summary(summarize_backtest(bt))
        else: st.warning('현재 데이터에 등위별 당첨금 필드가 없습니다.')
        probs=theoretical_single_game(); labels={'1st':'1등','2nd':'2등','3rd':'3등','4th':'4등','5th':'5등'}; st.dataframe(pd.DataFrame([{'등위':labels[k],'확률':pct(v,6),'약 1 / N':f"1 / {round(1/v):,}"} for k,v in probs.items()]),use_container_width=True,hide_index=True)
with tabs[4]:
    st.info('AI 진단은 번호를 점치는 기능이 아니라 과거패턴이 미지의 회차에도 유지되는지 시간순으로 검증하는 안전장치입니다. 성능이 기본모델보다 나쁘면 가중치를 강화하지 않습니다.')
    st.subheader('AI 진단 · 시간순 검증'); c1,c2=st.columns(2)
    if c1.button('시간순 Holdout',use_container_width=True):
        r=cached_mobile_ml_holdout(int(latest.draw_no))
        if r.get('available'): c=st.columns(3); c[0].metric('AUC',f"{r['roc_auc_out_of_sample']:.3f}"); c[1].metric('Model Log-loss',f"{r['log_loss_out_of_sample']:.4f}"); c[2].metric('기본보다 우수','예' if r['beats_constant_logloss'] else '아니오')
    if c2.button('완전 Walk-forward',use_container_width=True):
        ml_mode=st.radio('AI 검증 속도',['빠른 진단 (10회)','정밀 진단 (30회)'],horizontal=True,key='ml_speed_mobile')
        ml_tests=10 if ml_mode.startswith('빠른') else 30
        with st.spinner(f'회차별 재학습 중... ({ml_tests}회)'): r=cached_mobile_ml_walk_forward(int(latest.draw_no),ml_tests)
        if r.get('available'): rows=r.pop('rows',[]); c=st.columns(3); c[0].metric('테스트',r['tests']); c[1].metric('평균 AUC',f"{r['mean_auc']:.3f}"); c[2].metric('평균 Top6 적중',f"{r['mean_top6_hits']:.2f}개"); st.caption(f"평균 Log-loss {r['mean_log_loss']:.4f} · 기본 {r['mean_baseline_log_loss']:.4f}")
    st.markdown('---'); st.markdown('**사용 원칙**\n- AI가 기본 확률보다 실제로 좋아지는지 검증하는 연구 기능입니다.\n- 결과가 좋지 않으면 AI 예측 신호로 사용하지 않습니다.\n- MD Score는 당첨확률이 아닙니다.')

with tabs[5]:
    st.subheader('추천번호 ↔ 실제 당첨번호 · 상관/회귀 오차 진단')
    st.info('과거 각 회차 직전 데이터만으로 추천을 다시 생성한 뒤 실제 당첨번호와 비교합니다. 상관계수와 회귀계수는 원인 진단용이며 당첨확률 자체를 의미하지 않습니다.')

    dc1,dc2=st.columns(2)
    diag_tests=dc1.select_slider('진단 회차',['빠른 10회','표준 20회','정밀 30회'],value='표준 20회')
    diag_games=dc2.select_slider('회차당 추천 게임',[5,7,10],value=5)
    _dt=10 if diag_tests.startswith('빠른') else 20 if diag_tests.startswith('표준') else 30
    _samples=500 if _dt==10 else 800 if _dt==20 else 1000

    if st.button('🔎 상관·회귀 오차 진단 실행',use_container_width=True,type='primary'):
        with st.spinner(f'{_dt}개 과거 회차를 시간순으로 재생성·비교하는 중...'):
            st.session_state['corr_reg_diag']=cached_recommendation_diagnostics(int(latest.draw_no),_dt,diag_games,_samples)

    dr=st.session_state.get('corr_reg_diag')
    if dr and dr.get('available'):
        c=st.columns(4)
        _nc=dr.get('number_exposure_vs_win_corr')
        c[0].metric('진단 회차',f"{dr.get('tests',0)}회")
        c[1].metric('추천노출↔당첨 상관','-' if pd.isna(_nc) else f"{_nc:+.3f}")
        c[2].metric('평균 최고 적중',f"{dr.get('mean_best_hits',0):.2f}개")
        c[3].metric('평균 총 적중',f"{dr.get('mean_total_hits',0):.2f}개")

        if pd.notna(_nc):
            if abs(_nc)<.10:
                st.warning('추천 노출과 실제 당첨의 상관이 매우 약합니다. 현재 자료만으로 예측 우위를 주장할 근거가 부족합니다.')
            elif _nc>0:
                st.success('양(+)의 상관이 관찰됐지만, 표본 밖 Walk-forward와 랜덤 기준을 함께 통과해야 신호로 취급할 수 있습니다.')
            else:
                st.warning('음(-)의 상관이 관찰됐습니다. 현재 추천 가중치를 강화하면 안 됩니다.')

        st.markdown('#### 원인 분석 · 실제 구조와 추천 구조의 차이')
        mc=dr.get('mismatch_correlations',{})
        _names={'abs_gap_sum':'번호합 차이','abs_gap_odd':'홀짝 차이','abs_gap_low':'저·고번호 차이','abs_gap_range':'번호범위 차이','abs_gap_buckets':'구간분산 차이'}
        mdf=pd.DataFrame([{'요인':_names.get(k,k),'적중과 상관':v} for k,v in mc.items() if pd.notna(v)])
        if len(mdf):
            mdf['적중과 상관']=mdf['적중과 상관'].map(lambda x:f"{x:+.3f}")
            st.dataframe(mdf,use_container_width=True,hide_index=True)

        mr=dr.get('mismatch_regression',{})
        pr=dr.get('pre_regression',{})
        rc=st.columns(2)
        rc[0].metric('구조차이 회귀 R²','-' if not mr.get('available') else f"{mr.get('r2',0):.3f}")
        rc[1].metric('사전점수 회귀 R²','-' if not pr.get('available') else f"{pr.get('r2',0):.3f}")
        st.caption('R²가 낮으면 현재 변수들이 적중 차이를 충분히 설명하지 못한다는 뜻입니다. 높은 R²도 미래 예측력을 자동으로 의미하지 않습니다.')

        st.markdown('#### 프로그램이 제시하는 원인과 대책')
        for x in dr.get('causes',[]):
            st.markdown(f"**• {x['factor']}** · 상관 {x['correlation']:+.3f}\n\n→ {x['action']}")
        weak=dr.get('weak_signals',[])
        if weak:
            st.markdown('**가중치 점검 필요 항목**')
            for x in weak[:4]:
                st.caption(f"• {x['factor']} ({x['correlation']:+.3f}) → {x['action']}")

        st.markdown('#### 회차별 진단 원자료')
        raw=dr.get('rows')
        if raw is not None and len(raw):
            show=raw[['draw_no','best_hits','total_hits','avg_md_score','abs_gap_sum','abs_gap_odd','abs_gap_low','abs_gap_range']].copy()
            show.columns=['회차','최고 적중','총 적중','평균 MD Score','번호합 차이','홀짝 차이','저·고 차이','범위 차이']
            st.dataframe(show.sort_values('회차',ascending=False),use_container_width=True,hide_index=True)

    rec=st.session_state.get('md_recommendation_record')
    if rec:
        td=int(rec.get('target_draw',0))
        if td<=int(latest.draw_no) and td in set(df.draw_no.astype(int)):
            rr=df[df.draw_no.astype(int)==td].iloc[-1]
            win={int(rr[f'n{i}']) for i in range(1,7)}
            hs=[len(set(g)&win) for g in rec.get('games',[])]
            st.markdown('#### 이번 세션에서 저장된 추천 ↔ 실제 결과')
            st.write(f"대상 {td}회 · 최고 적중 {max(hs) if hs else 0}개 · 전체 게임 적중 합 {sum(hs)}개")
        else:
            st.caption(f"현재 세션 추천 기록: {td}회 대상 · 실제 추첨 후 이 탭에서 바로 비교할 수 있습니다.")

    st.markdown('---')
    st.caption('해석 원칙: 상관관계는 인과관계가 아닙니다. 회귀분석은 과거 오차를 설명하는 도구이며, 가중치 변경은 반드시 Nested Walk-forward와 랜덤 기준 비교를 통과한 경우에만 적용합니다.')


st.caption('MD LOTTO 6/45 · v5.8 Integrated · 모든 특정 6개 조합의 1등 확률은 동일합니다.')
